# -*- coding: utf-8 -*-
"""FD_draft.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1El9RaCeZo_w7-_mvTBirG6wC92WwuuMT
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from multiprocessing import Pool
from functools import partial
import numpy as np
import pandas as pd
import torch
from scipy.interpolate import interp1d
import cvxpy as cp
from scipy.stats import truncnorm
import time

# ---------------------------
# Data Splitting
# ---------------------------
def split_data_k_folds(data, k):
    n = len(data)
    indices = np.arange(n)
    np.random.shuffle(indices)
    fold_size = n // k
    for i in range(k):
        test_indices = indices[i*fold_size:(i+1)*fold_size]
        train_indices = np.setdiff1d(indices, test_indices)
        yield data.iloc[train_indices].reset_index(drop=True), data.iloc[test_indices].reset_index(drop=True)

# ---------------------------
# First–Order Basis Functions
# ---------------------------
def create_cumulative_indicators_ge(series, grid_points, prefix):
    """
    For each grid point g, return an indicator function 1{series >= g}.
    """
    indicators_dict = {}
    counter = 1
    for g in grid_points:
        counter += 1
        colname = f"{prefix}_ge_{g:.4f}_{counter}"
        indicators_dict[colname] = (series >= g).astype(int)
    return pd.DataFrame(indicators_dict, index=series.index)

def create_basis_functions(data, grid_points, prefix='W1',smoothness_order=1):
    """
    Create first–order basis functions defined as (x-g)_+ = max(0, x-g)
    by combining the cumulative indicator with a linear shift.
    Returns a torch tensor.
    """
    if smoothness_order == 1:
      # For each knot g, define basis function = 1{x >= g}*(x - g)
      basis_cols = []
      for g in grid_points:
          basis_col = np.where(data[prefix] >= g, data[prefix] - g, 0)
          basis_cols.append(basis_col)
      basis_array = np.array(basis_cols).T  # shape: (n_samples, K)
      return torch.tensor(basis_array, dtype=torch.float32)
    elif smoothness_order == 0:
      indicators = create_cumulative_indicators_ge(data[prefix], grid_points, prefix=prefix)
      # You could combine with other features if needed.
      basis_df = pd.concat([indicators], axis=1)
      return torch.tensor(basis_df.values, dtype=torch.float32)
    else:
        raise ValueError("order must be 0 (zero–order) or 1 (first–order).")


# ---------------------------
# NPMLE Density Estimation for Full Data
# ---------------------------
def estimate_density_npmle(data, threshold=1e-4, norm_constraint=3,smoothness_order=1):
    """
    Estimate density using a nonparametric MLE (NPMLE) with first–order HAL basis.

    Data is assumed complete with column 'W1'.

    Returns a dictionary with:
      - optimized_theta: CVXPY solution before pruning.
      - pruned_theta: theta after pruning small coefficients.
      - estimated_density: density evaluated on an evaluation grid.
      - grid_midpoints: midpoints of evaluation grid intervals.
      - grid_points_hal_selected: the knots (after pruning).
      - theta_selected: nonzero coefficients (excluding intercept).
      - b_jk: basis evaluated on the evaluation grid.
      - delta_j: interval widths.
      - grid_eval: evaluation grid endpoints.
    """
    n_samples = len(data)
    # Use all unique values in W1 as candidate knots; include 0 and 1.
    grid_points_hal = np.unique(np.concatenate(([0], data['W1'].values, [1])))

    #Knot points are selected as the percentiles.
    # Compute the number of percentiles as the nearest integer of 10*sqrt(n_samples)
    num_percentiles = int(np.rint(10 * np.sqrt(n_samples)))
    grid_points_hal = np.percentile(grid_points_hal, np.linspace(0, 100, num_percentiles))


    # Build the basis for the data
    basis_tensor = create_basis_functions(data, grid_points_hal,smoothness_order=smoothness_order)
    b_ik = basis_tensor.numpy()

    # Create an evaluation grid (e.g., 200 endpoints) and compute midpoints
    grid_eval = np.linspace(0, 1, 200)
    grid_midpoints = (grid_eval[:-1] + grid_eval[1:]) / 2
    data_grid = pd.DataFrame({'W1': grid_midpoints})
    basis_grid_tensor = create_basis_functions(data_grid, grid_points_hal,smoothness_order=smoothness_order)
    b_jk = basis_grid_tensor.numpy()

    K = len(grid_points_hal) + 1  # including intercept
    theta = cp.Variable(K)

    # Objective: - sum log f(W1) + n log Z
    first_term = -cp.sum(theta[0] + b_ik @ theta[1:])
    delta_j = grid_eval[1:] - grid_eval[:-1]
    log_delta_j = np.log(delta_j)
    log_density_grid = theta[0] + b_jk @ theta[1:]
    log_terms = log_delta_j + log_density_grid
    log_Z = cp.log_sum_exp(log_terms)
    second_term = n_samples * log_Z
    loss = first_term + second_term

    # Constrain L1–norm of coefficients (excluding intercept)
    constraints = [cp.norm1(theta[1:]) <= norm_constraint]
    prob = cp.Problem(cp.Minimize(loss), constraints)
    try:
        prob.solve(solver="ECOS")
    except Exception as e:
        print("ECOS solver failed: ", e, "\nUsing SCS instead.")
        prob.solve(solver="SCS")

    # Prune small coefficients
    theta_pruned = np.copy(theta.value)
    theta_pruned[1:] = np.where(np.abs(theta.value[1:]) > threshold, theta.value[1:], 0)
    non_zero_indices = np.nonzero(theta_pruned)[0]

    # Use the knots corresponding to nonzero coefficients (excluding intercept)
    grid_points_hal_selected = grid_points_hal[non_zero_indices[1:] - 1]

    # Augment the evaluation grid with the selected knots and re-sort
    grid_eval = np.sort(np.unique(np.concatenate((grid_eval, grid_points_hal_selected))))
    grid_midpoints = (grid_eval[:-1] + grid_eval[1:]) / 2
    data_grid = pd.DataFrame({'W1': grid_midpoints})
    basis_grid_tensor = create_basis_functions(data_grid, grid_points_hal,smoothness_order=smoothness_order)
    b_jk = basis_grid_tensor.numpy()
    delta_j = grid_eval[1:] - grid_eval[:-1]

    b_jk_pruned = b_jk[:, non_zero_indices[1:] - 1]
    theta_selected = theta_pruned[non_zero_indices[1:]]
    estimated_log_density = theta_pruned[0] + b_jk_pruned @ theta_selected
    estimated_density = np.exp(estimated_log_density)
    estimated_density /= np.sum(estimated_density * delta_j)
    theta_value = theta_pruned[non_zero_indices]

    return {
        "theta_value": theta_value,          # store entire vector for pruned theta including intercept
        "optimized_theta": theta.value,
        "pruned_theta": theta_pruned,
        "estimated_density": estimated_density,
        "grid_midpoints": grid_midpoints,
        "grid_points_hal_selected": grid_points_hal_selected,
        "theta_selected": theta_selected,
        "b_jk": b_jk_pruned,
        "delta_j": delta_j,
        "grid_eval": grid_eval
    }

# ---------------------------
# Total Log-Likelihood for Full Data
# ---------------------------
def compute_total_log_likelihood_full(data, results):
    """
    Compute the total log-likelihood for full (uncensored) data.
    Data is assumed to have column 'W1'.
    """
    estimated_density = results['estimated_density']
    grid_midpoints = results['grid_midpoints']
    density_interp = interp1d(grid_midpoints, estimated_density, kind='linear',
                               bounds_error=False, fill_value=(estimated_density[0], estimated_density[-1]))
    x = data['W1'].values
    return np.sum(np.log(density_interp(x)))

# ---------------------------
# Cross-Validation for Full Data HAL
# ---------------------------
def compute_validation_risk_for_lambda(args):
    lamb, data, k, threshold,smoothness_order = args
    risks = []
    for train, valid in split_data_k_folds(data, k):
        res = estimate_density_npmle(train, threshold=threshold, norm_constraint=lamb,smoothness_order=smoothness_order)
        risk = compute_total_log_likelihood_full(valid, res)
        risks.append(risk)
    return lamb, np.mean(risks)

def CV_full_HAL(data, k, lambda_values, threshold=1e-4, n_jobs=-1,smoothness_order=1):
    args = [(lamb, data, k, threshold, smoothness_order) for lamb in lambda_values]
    if n_jobs == 1:
        results = [compute_validation_risk_for_lambda(arg) for arg in args]
    else:
        with Pool(processes=n_jobs if n_jobs != -1 else None) as pool:
            results = pool.map(compute_validation_risk_for_lambda, args)
    mean_risks = dict(results)
    best_lambda = max(mean_risks, key=mean_risks.get)
    return best_lambda, mean_risks

# ---------------------------
# Survival Function Estimation for Full Data
# ---------------------------
from scipy.integrate import cumulative_trapezoid

def compute_survival_from_density_full(estimator_dict, grid_eval=None):
    """
    Compute the survival function S(t)=1-CDF(t) from the estimated density for a first–order HAL estimator.

    This function uses the trapezoidal rule to integrate the (smooth) estimated density.
    It returns the survival function evaluated on the grid_eval endpoints.

    Parameters
    ----------
    estimator_dict : dict
        Output from the first–order HAL estimator (e.g., estimate_density_npmle adapted for first–order HAL).
        Must contain:
            - 'estimated_density': the estimated density evaluated on grid_midpoints.
            - 'grid_midpoints': the midpoints of the evaluation grid where density is evaluated.
    grid_eval : array-like, optional
        The evaluation grid endpoints over [0,1]. If not provided, defaults to
        estimator_dict['grid_eval'] if available or np.linspace(0, 1, 1000).

    Returns
    -------
    survival : np.ndarray
        The survival function evaluated on grid_eval.
    grid_eval : np.ndarray
        The evaluation grid used.
    """
    if grid_eval is None:
        grid_eval = estimator_dict.get('grid_eval', np.linspace(0, 1, 1000))
    # Here, we assume the density is estimated at grid_midpoints.
    grid_mid = estimator_dict['grid_midpoints']
    density = estimator_dict['estimated_density']
    # To evaluate the CDF on the grid_eval, interpolate the estimated density to grid_eval.
    # This yields an array of the same length as grid_eval.
    density_on_eval = np.interp(grid_eval, grid_mid, density, left=density[0], right=density[-1])
    # Use cumtrapz with initial=0 to compute the cumulative integral (CDF)
    cdf = cumulative_trapezoid(density_on_eval, grid_eval, initial=0)
    # Normalize the CDF (to be exactly 1 at the right end)
    cdf /= cdf[-1]
    survival = 1 - cdf
    return survival, grid_eval



# ---------------------------
# True Density for Evaluation
# ---------------------------
def compute_true_density(grid_points, mean=0.5, std=0.1, lower=0, upper=1):
    a, b = (lower-mean)/std, (upper-mean)/std
    return truncnorm.pdf(grid_points, a, b, loc=mean, scale=std)

# Function to generate T following truncated normal distribution in range [0, 1]
def generate_truncated_normal(n_samples, mean=0.5, std=0.1, lower=0, upper=1):
    a, b = (lower - mean) / std, (upper - mean) / std
    T = truncnorm.rvs(a, b, loc=mean, scale=std, size=n_samples)
    return T

##############################################
# Poinwise confidence intervals for the density (Helper functions)
##############################################

##############################################
# 1. Compute individual score contributions (Full Data)
##############################################

def compute_individual_score(row, final_results,smoothness_order=1):
    """
    For full data (i.e. no censoring), compute the score contribution for a single observation.

    The score is given by:
        s_i = φ(W1_i) - E[φ(X)],
    where the expectation is computed over the integration grid using the estimated density.

    Parameters:
    -----------
    row : Series
        A row from the full data containing at least the column "W1".
    final_results : dict
        Dictionary from your NPMLE that includes:
          - "grid_midpoints": 1D array of grid midpoints used for integration.
          - "estimated_density": estimated density on those midpoints.
          - "delta_j": grid interval lengths.
          - "grid_points_hal_selected": the selected HAL knots.
          - "b_jk": basis functions evaluated on the integration grid (each row corresponds to a grid point).

    Returns:
    --------
    score : 1D numpy array (length = number of selected basis functions)
    """
    # For full data, we use the value in "W1"
    W1 = row['W1']
    # Compute the expectation E[φ(X)] on the grid:
    E_phi = np.sum(final_results["b_jk"].T * final_results["estimated_density"] * final_results["delta_j"], axis=1)
    # Evaluate the basis at the observation:
    df_W1 = pd.DataFrame({'W1': [W1]})
    phi_W1 = create_basis_functions(df_W1, final_results["grid_points_hal_selected"],smoothness_order=smoothness_order).numpy().flatten()
    score = phi_W1 - E_phi
    return score

##############################################
# 2. Estimate the covariance matrix of β̂
##############################################

def estimate_covariance_beta(data, final_results,ridge=1e-6, smoothness_order=1):
    """
    Estimate the covariance matrix of the (non-intercept) coefficients β̂.

    Here we form the individual score vectors (one per observation) and then estimate
    the Fisher information as the average outer product:

         Î = (1/n) ∑ s_i s_i^T,

    and finally use (asymptotically)

         Cov(β̂) ≈ Î⁻¹ / n.

    Parameters:
    -----------
    data : DataFrame
        The full data with column "W1".
    final_results : dict
        The NPMLE result (from estimate_density_npmle) containing the necessary keys.

    Returns:
    --------
    cov_beta : 2D numpy array of shape (p, p), where p = number of selected basis functions.
    """
    scores = []
    for _, row in data.iterrows():
        s = compute_individual_score(row, final_results,smoothness_order=smoothness_order)
        scores.append(s)
    scores = np.array(scores)  # shape: (n, p)
    n = scores.shape[0]

    # Estimate the expected outer product: Î = (1/n)*∑ s_i s_i^T.
    I_hat = np.dot(scores.T, scores) / n
    I_hat_reg = I_hat + (ridge/np.sqrt(I_hat.shape[0]))  * np.eye(I_hat.shape[0])
    try:
        cov_beta = np.linalg.inv(I_hat_reg) / n
    except np.linalg.LinAlgError:
        cov_beta = np.linalg.pinv(I_hat_reg) / n
    return cov_beta


##############################################
# 3. Estimate the density at an arbitrary x
##############################################

def estimated_density_at(x, final_results):
    """
    For any x in [0,1] (or within the region of interest), return the estimated density.
    Here a linear interpolation is used on the grid midpoints stored in final_results.

    Parameters:
    -----------
    x : float or array-like
        Evaluation point(s).
    final_results : dict
        Must contain "grid_midpoints" and "estimated_density".

    Returns:
    --------
    f_x : float or array of estimated density values.
    """
    f_interp = interp1d(final_results["grid_midpoints"], final_results["estimated_density"],
                        kind="linear", bounds_error=False, fill_value="extrapolate")
    return f_interp(x)

##############################################
# 4. Compute the gradient of the density
##############################################

def compute_grad_f(x, final_results,smoothness_order=1):
    """
    Compute the gradient of the estimated density at x with respect to the non-intercept coefficients.

    That is, compute
         grad_f(x) = f(x) * [φ(x) - E[φ(X)]],
    where:
         - f(x) is the estimated density at x,
         - φ(x) is the HAL basis vector evaluated at x,
         - E[φ(X)] is the expectation of the basis function vector computed over the integration grid.

    Parameters:
    -----------
    x : float
        The evaluation point.
    final_results : dict
        Must contain:
          - "grid_points_hal_selected": the selected HAL knots.
          - "b_jk": basis functions evaluated on the integration grid.
          - "estimated_density": estimated density on the integration grid.
          - "delta_j": grid interval lengths.

    Returns:
    --------
    grad_f : 1D numpy array, the gradient of f at x with respect to β.
    """
    # Evaluate f(x)
    f_x = estimated_density_at(x, final_results)
    # Evaluate basis at x:
    df_x = pd.DataFrame({'W1': [x]})
    phi_x = create_basis_functions(df_x, final_results["grid_points_hal_selected"],smoothness_order=smoothness_order).numpy().flatten()
    # Compute the expectation E[φ(X)]:
    E_phi = np.sum(final_results["b_jk"].T * final_results["estimated_density"] * final_results["delta_j"], axis=1)
    grad_f = f_x * (phi_x - E_phi)
    return grad_f

##############################################
# 5. Use the delta method to compute variance
##############################################

def compute_density_variance(x, final_results, cov_beta,smoothness_order=1):
    """
    Compute the approximate variance of the estimated density at x via the delta method.

    Given that
         f(x) = exp(θ₀ + φ(x)^Tβ) / Z,
    its gradient with respect to β is
         grad_f(x) = f(x) * [φ(x) - E[φ(X)]],
    so that
         Var(f(x)) ≈ grad_f(x)^T Cov(β̂) grad_f(x).

    Parameters:
    -----------
    x : float
        The evaluation point.
    final_results : dict
        Must contain the required keys.
    cov_beta : 2D numpy array
        Estimated covariance matrix of β̂.

    Returns:
    --------
    var_f : float, the estimated variance of f(x).
    """
    grad_f_val = compute_grad_f(x, final_results,smoothness_order=smoothness_order)
    var_f = np.dot(grad_f_val, np.dot(cov_beta, grad_f_val))
    return var_f

##############################################
# 6. Construct confidence intervals for a grid of x's
##############################################

def density_confidence_interval(x_values, final_results, cov_beta, alpha=0.05,smoothness_order=1):
    """
    For each evaluation point in x_values, compute the estimated density,
    its standard error (via the delta method), and the (1-α)% confidence interval.

    Parameters:
    -----------
    x_values : array-like
        Points at which to compute the inference.
    final_results : dict
        The NPMLE result from the full data estimation.
    cov_beta : 2D numpy array
        Estimated covariance matrix of β̂.
    alpha : float
        Significance level (default 0.05 for 95% CIs).

    Returns:
    --------
    results_df : DataFrame with columns:
         'x'       : evaluation point,
         'density' : estimated density f(x),
         'se'      : standard error,
         'lower'   : lower CI bound,
         'upper'   : upper CI bound.
    """
    z = norm.ppf(1 - alpha / 2)
    results = []
    for x in x_values:
        f_x = estimated_density_at(x, final_results)
        var_f = compute_density_variance(x, final_results, cov_beta,smoothness_order=smoothness_order)
        se = np.sqrt(var_f)
        lower = f_x - z * se
        upper = f_x + z * se
        results.append({'x': x, 'density': f_x, 'se': se, 'lower': lower, 'upper': upper})
    return pd.DataFrame(results)

from scipy.stats import norm

##############################################
# Poinwise confidence intervals for the survival (Helper functions)
##############################################

##############################################
# Precompute the Density Gradient on a Fine Uniform Grid
##############################################

def precompute_grad_f_grid(final_results, grid_size=1000,smoothness_order=1):
    """
    Precompute the gradient of the estimated density f(x) on a uniform grid over [0,1].

    Parameters:
      final_results : dict, the HAL estimation result (contains keys used in compute_grad_f)
      grid_size : int, number of points in the uniform grid (default: 1000)

    Returns:
      grid : numpy array of shape (grid_size,), the uniform grid points over [0,1]
      grad_f_grid : numpy array of shape (grid_size, p), where p is the number of non-intercept coefficients,
                    containing grad_f(x) at each grid point.
      delta : float, the uniform grid spacing.
    """
    grid = np.linspace(0, 1, grid_size)
    grad_f_list = []
    for x in grid:
        grad_f_list.append(compute_grad_f(x, final_results,smoothness_order=smoothness_order))
    grad_f_grid = np.array(grad_f_list)  # shape: (grid_size, p)
    delta = grid[1] - grid[0]
    return grid, grad_f_grid, delta

##############################################
# Compute the Survival Gradient Using the Precomputed Grid
##############################################

def compute_grad_S_from_precomputed(x0, grid, grad_f_grid, delta):
    """
    Given a precomputed uniform grid and corresponding grad_f values,
    compute the survival gradient:
         ∇_β S(x0) = ∫_{x0}^1 ∇_β f(y) dy,
    by summing the precomputed gradients for grid points >= x0.

    Parameters:
      x0 : float, evaluation point.
      grid : numpy array, the precomputed uniform grid over [0,1].
      grad_f_grid : numpy array, precomputed gradient values at each grid point.
      delta : float, uniform grid spacing.

    Returns:
      grad_S : 1D numpy array, the approximate gradient vector of S(x0).
    """
    mask = grid >= x0
    grad_S = np.sum(grad_f_grid[mask], axis=0) * delta
    return grad_S

##############################################
# Survival Function and Variance via Delta Method
##############################################

def estimated_survival_at(x0, final_results):
    """
    Estimate the survival function S(x0) = ∫_{x0}^1 f(y) dy using a Riemann sum
    on the original integration grid.
    """
    grid = final_results["grid_midpoints"]
    f = final_results["estimated_density"]
    delta = final_results["delta_j"]
    mask = grid >= x0
    return np.sum(f[mask] * delta[mask])

def compute_survival_variance_precomputed(x0, final_results, cov_beta, grid, grad_f_grid, delta):
    """
    Compute the approximate variance of the survival function S(x0) using the precomputed
    survival gradient and the delta method.

    Var(S(x0)) ≈ (∇_β S(x0))ᵀ · Cov(β) · (∇_β S(x0))
    """
    grad_S = compute_grad_S_from_precomputed(x0, grid, grad_f_grid, delta)
    return np.dot(grad_S, np.dot(cov_beta, grad_S))

def survival_confidence_interval_precomputed(x_values, final_results, cov_beta, grid, grad_f_grid, delta, alpha=0.05):
    """
    For each evaluation point x0 in x_values, compute the survival function S(x0)
    and its (1-α)% confidence interval using the delta method with precomputed gradients.
    """
    z = norm.ppf(1 - alpha/2)
    results = []
    for x0 in x_values:
        S_x0 = estimated_survival_at(x0, final_results)
        var_S = compute_survival_variance_precomputed(x0, final_results, cov_beta, grid, grad_f_grid, delta)
        se = np.sqrt(np.maximum(var_S, 0))
        lower = S_x0 - z * se
        upper = S_x0 + z * se
        results.append({'x': x0, 'survival': S_x0, 'se': se, 'lower': lower, 'upper': upper})
    return pd.DataFrame(results)

##############################################
# Targeting Step
##############################################

# Helper function to create targeting basis /clever covariates
def create_cumulative_indicators_g(series, grid_points, prefix):
    """
    Create cumulative greater-or-equal indicators based on unequally spaced grid.

    Parameters:
    - series: pd.Series
    - grid_points: array-like, shape (K+1,)
    - prefix: str, prefix for indicator column names

    Returns:
    - indicators: pd.DataFrame
    """
    indicators_dict = {}
    id = 1
    for value in grid_points:
        id += 1
        indicator_col = f"{prefix}_g_{value:.4f}_{id}"
        indicators_dict[indicator_col] = (series > value).astype(int)
    indicators = pd.DataFrame(indicators_dict, index=series.index)

    return indicators

# Generate basis functions for data and evaluation grid
def create_targeting_basis_functions(data_long_train, grid_points, prefix='W1'):
    indicators = create_cumulative_indicators_g(data_long_train['W1'], grid_points, prefix=prefix)
    basis_df = pd.concat([indicators], axis=1)
    basis_tensor = torch.tensor(basis_df.values, dtype=torch.float32)
    return basis_tensor

# Targeting maximum likelihood

def targeting_M_step(targeting_points, uncensored_augmented, results, old_theta, norm_constraint=20):
    """
    This function performs an M-step update for a density model that has the form
       f(x) = exp(linear_predictor) / Z,
    where the linear predictor is the sum of two parts:
      (i) a “hal‐basis” part with an intercept and coefficients given by old_theta,
     (ii) a new “targeting‐basis” part with free coefficients (α) that are optimized.

    Only the targeting basis coefficients are updated; the intercept and the hal‐basis
    coefficients (old_theta) are kept fixed.

    Parameters
    ----------
    targeting_points : array-like
        The locations at which the targeting basis functions are defined.
    uncensored_augmented : DataFrame
        A pandas DataFrame containing the uncensored data points.
        (Note: weights are forced to be 1 for each observation in this version.)
    results : dict
        A dictionary containing (at least) the key "grid_points_hal_selected" with the
        hal design grid.
    old_theta : array-like
        The current (fixed) parameter vector for the intercept and hal basis functions.
        Here, old_theta[0] is the intercept and old_theta[1:] are the hal coefficients.
    norm_constraint : float, optional
        L1-norm constraint for the targeting coefficient(s) (default is 20).

    Returns
    -------
    updated_results : dict
        A dictionary with updated parameters and estimated density on a fine grid.
    """

    # ----------------------------
    # 1. Design matrix construction
    # ----------------------------
    start_time_m_design = time.time()

    # Use the hal grid from the previous iteration
    grid_points_hal_selected = results['grid_points_hal_selected']
    grid_points_hal = grid_points_hal_selected  # for hal-basis
    uncensored_data = uncensored_augmented

    # Create hal basis design matrix for uncensored data
    # (Assumes create_basis_functions returns a torch.Tensor)
    basis_tensor = create_basis_functions(uncensored_data, grid_points_hal)
    b_ik = basis_tensor.detach().numpy()  # shape: (n_data, n_hal_basis)

    # Create targeting basis design matrix for uncensored data
    basis_tensor_targeting = create_targeting_basis_functions(uncensored_data, targeting_points)
    b_ik_targeting = basis_tensor_targeting.numpy()  # shape: (n_data, n_targeting_basis)
    if b_ik_targeting.ndim == 1:
        b_ik_targeting = b_ik_targeting[:, None]

    # Create an evaluation grid (here 200 points) for computing the normalization constant.
    grid_eval = np.linspace(0, 1, 200)
    combined_grid = np.concatenate((grid_eval, grid_points_hal_selected))
    filtered_grid = combined_grid[combined_grid >= 0]
    filtered_grid = np.unique(filtered_grid)
    grid_eval = np.sort(filtered_grid)

    # Compute midpoints for integration
    grid_midpoints = (grid_eval[:-1] + grid_eval[1:]) / 2
    data_grid = pd.DataFrame({'W1': grid_midpoints})

    # Evaluate hal basis on the integration grid
    basis_grid_tensor = create_basis_functions(data_grid, grid_points_hal)
    b_jk = basis_grid_tensor.numpy()  # shape: (n_grid, n_hal_basis)

    # Evaluate targeting basis on the integration grid
    basis_grid_tensor_targeting = create_targeting_basis_functions(data_grid, targeting_points)
    b_jk_targeting = basis_grid_tensor_targeting.numpy()  # shape: (n_grid, n_targeting_basis)
    if b_jk_targeting.ndim == 1:
        b_jk_targeting = b_jk_targeting[:, None]

    end_time_m_design = time.time()
    m_step_time_design = end_time_m_design - start_time_m_design
    print(f"M-step Design Matrix Calculation time (sec): {m_step_time_design:.4f}")

    # ----------------------------
    # 2. Set up the optimization problem
    # ----------------------------
    start_time_m_optimize = time.time()

    # Compute the fixed (hal-basis) part of the linear predictor:
    #   fixed = intercept + (hal_basis dot old_hal_coefficients)
    # For uncensored data:
    fixed_data = old_theta[0] + np.dot(b_ik, old_theta[1:])
    # For the integration grid:
    fixed_grid = old_theta[0] + np.dot(b_jk, old_theta[1:])

    # --- Set weights to 1 by default ---
    weights_M = np.ones(len(uncensored_data))
    n_samples_weighted = np.sum(weights_M)

    # Compute the widths (delta) for integration and their logarithms
    delta_j = grid_eval[1:] - grid_eval[:-1]
    log_delta_j = np.log(delta_j)

    # The only free parameter is the targeting basis coefficient vector.
    # Its dimension is determined by the number of targeting basis functions.
    r = b_ik_targeting.shape[1]
    alpha = cp.Variable(r)

    # Define the full linear predictor by adding the targeting part:
    # For data points:
    L_data = fixed_data + b_ik_targeting @ alpha  # shape: (n_data,)
    # For grid points:
    L_grid = fixed_grid + b_jk_targeting @ alpha    # shape: (n_grid,)

    # Formulate the (negative) log-likelihood.
    # Data term:  -sum_i weights[i] * (fixed + targeting_effect)
    data_term = -cp.sum(cp.multiply(weights_M, L_data))
    # Normalization term:  n_samples_weighted * log_sum_exp( log(delta_j) + L_grid )
    norm_term = n_samples_weighted * cp.log_sum_exp(log_delta_j + L_grid)
    loss = data_term + norm_term

    # Optionally, we include a norm constraint on the targeting coefficients.
    constraints = [cp.norm1(alpha) <= norm_constraint]

    objective = cp.Minimize(loss)
    problem = cp.Problem(objective, constraints)

    # Warm start: initialize alpha (you may change this if you have a previous guess)
    alpha.value = np.zeros(r)

    # Solve the optimization problem (here using the ECOS solver)
    try:
        problem.solve(solver="ECOS")
    except Exception as e:
        print("ECOS solver failed in IPCW_HAL_init, falling back to SCS:", e)
        problem.solve(solver="SCS")

    end_time_m_optimize = time.time()
    m_step_time_optimize = end_time_m_optimize - start_time_m_optimize
    print(f"M-step CVXPY optimize time (sec): {m_step_time_optimize:.4f}")

    # ----------------------------
    # 3. Compute the estimated density on a fine grid
    # ----------------------------
    # Retrieve the optimized targeting coefficients
    theta_targeting = alpha.value

    # The fixed hal-basis parameters remain the same:
    theta_intercept = old_theta[0]
    theta_selected = old_theta[1:]

    # Now, evaluate the density on a fine grid (here 2000 points)
    grid_eval = np.linspace(0, 1, 2000)
    combined_grid = np.concatenate((grid_eval, grid_points_hal_selected))
    filtered_grid = combined_grid[combined_grid >= 0]
    filtered_grid = np.unique(filtered_grid)
    grid_eval_full = np.sort(filtered_grid)



    grid_midpoints_full = (grid_eval_full[:-1] + grid_eval_full[1:]) / 2
    data_grid_full = pd.DataFrame({'W1': grid_midpoints_full})

    # Evaluate hal basis on the fine grid
    basis_grid_tensor_full = create_basis_functions(data_grid_full, grid_points_hal)
    b_jk_full = basis_grid_tensor_full.numpy()

    # Evaluate targeting basis on the fine grid
    basis_grid_tensor_targeting_full = create_targeting_basis_functions(data_grid_full, targeting_points)
    b_jk_targeting_full = basis_grid_tensor_targeting_full.numpy()
    if b_jk_targeting_full.ndim == 1:
        b_jk_targeting_full = b_jk_targeting_full[:, None]

    delta_j_full = grid_eval_full[1:] - grid_eval_full[:-1]

    # The estimated log-density is the sum of the fixed (hal) part and the optimized targeting part.
    estimated_log_density = theta_intercept + b_jk_full @ theta_selected + b_jk_targeting_full @ theta_targeting
    estimated_density = np.exp(estimated_log_density)
    estimated_density /= np.sum(estimated_density * delta_j_full)  # Normalize so it integrates to 1

    # ----------------------------
    # 4. Package and return results
    # ----------------------------
    updated_results = {
        "old_theta": old_theta,               # fixed intercept and hal-basis coefficients
        "theta_targeting": theta_targeting,     # newly optimized targeting coefficients
        "theta_intercept": theta_intercept,
        "theta_selected": theta_selected,
        "estimated_density": estimated_density,
        "grid_midpoints": grid_midpoints_full,
        "grid_points_hal_selected": grid_points_hal_selected,
        "b_jk": b_jk_full,
        "b_jk_targeting": b_jk_targeting_full,
        "delta_j": delta_j_full,
        "grid_eval": grid_eval_full,
        "targeting_points": targeting_points
    }

    return updated_results

# Single Experiment Function
# ---------------------------
def run_single_experiment(seed, n_samples=1000,
                          evaluation_points=np.linspace(0.02, 0.98, 20),
                          candidate_lambdas=[55, 60, 65, 70],smoothness_order=1,ridge=1e-6,targeting_points=np.linspace(0.02, 0.98, 20)):
    """
    Run one experiment:
      - Simulate full (uncensored) data using a truncated normal.
      - Use 5-fold CV to select the best lambda.
      - Estimate density using first–order HAL NPMLE.
      - Compute the plug–in survival function.
      - Evaluate density on the evaluation grid (by interpolation).

    Returns a dictionary with:
      "estimated_density": density evaluated on evaluation_points,
      "survival": survival probabilities evaluated on the grid,
      "best_lambda": the best lambda chosen by CV,
      "evaluation_points": the evaluation grid.
    """
    np.random.seed(seed)
    T = generate_truncated_normal(n_samples)
    # For full data, we simply let W1 = T.
    data = pd.DataFrame({'W1': T})

    k = 5
    best_lambda, cv_risks = CV_full_HAL(data, k, candidate_lambdas, threshold=1e-4, n_jobs=1,smoothness_order=smoothness_order)

    init_res = estimate_density_npmle(data, threshold=1e-4, norm_constraint=best_lambda,smoothness_order=smoothness_order)

    # Evaluate density by linear interpolation on the midpoints.
    init_density_eval = np.interp(evaluation_points, init_res['grid_midpoints'], init_res['estimated_density'])

    # Compute survival function (using a step-function approximation)
    survival, grid_surv = compute_survival_from_density_full(init_res)
    init_surv_probs = np.interp(evaluation_points, grid_surv, survival, left=1.0, right=0.0)


    cov_beta = estimate_covariance_beta(data, init_res, ridge = ridge, smoothness_order=smoothness_order)
    ci_density_df = density_confidence_interval(evaluation_points, init_res, cov_beta, alpha=0.05,smoothness_order=smoothness_order)
    initial_density_se=ci_density_df['se']
    
    grid, grad_f_grid, delta = precompute_grad_f_grid(init_res, grid_size=1000,smoothness_order=smoothness_order)
    surv_ci_df = survival_confidence_interval_precomputed(evaluation_points, init_res, cov_beta, grid, grad_f_grid, delta, alpha=0.05)
    initial_survival_se=surv_ci_df['se']

    # Compute the standard error for the survival using the eic, 1(T> x) - E[1(T > X)]
    # Note: the standard error is computed as the sample standard deviation of the EIC divided by sqrt(n)
    # where n is the number of observations.
    EIC_matrix = np.zeros((data.shape[0], len(evaluation_points)))
    for i, x0 in enumerate(evaluation_points):
        EIC_matrix[:, i] = 1 * (data['W1'] > x0) - estimated_survival_at(x0, init_res)
    initial_survival_se_eic = np.std(EIC_matrix, axis=0, ddof=1) / np.sqrt(data.shape[0])
    


    ##Targeting
    targeted_fit = targeting_M_step(targeting_points=targeting_points,
                                    uncensored_augmented = data,
                                    results =init_res,
                                    old_theta = init_res.get("theta_value", None),
                                    norm_constraint=5*best_lambda)


    # Evaluate density by linear interpolation on the midpoints.
    final_density_eval = np.interp(evaluation_points, targeted_fit['grid_midpoints'], targeted_fit['estimated_density'])

    # Compute survival function after targeting (using a step-function approximation)
    survival, grid_surv = compute_survival_from_density_full(targeted_fit)
    final_surv_probs = np.interp(evaluation_points, grid_surv, survival, left=1.0, right=0.0)

    #Now, get the EIC matrix
    # Build the basis for the data
    basis_tensor = create_basis_functions(data, targeting_points,smoothness_order=0)
    b_ik_targeting = basis_tensor.numpy()
    survival_targeting=np.interp(targeting_points, grid_surv, survival, left=1.0, right=0.0)
    EIC_matrix=b_ik_targeting - survival_targeting
    final_survival_se = np.std(EIC_matrix, axis=0, ddof=1)/np.sqrt(EIC_matrix.shape[0])

    # Compute the standard error for the density estimates using the eic, 1(T> x) - E[1(T > X)]
    # Note: the standard error is computed as the sample standard deviation of the EIC divided by sqrt(n)
    # where n is the number of observations.
    EIC_matrix = np.zeros((data.shape[0], len(evaluation_points)))
    for i, x0 in enumerate(evaluation_points):
        EIC_matrix[:, i] = 1 * (data['W1'] > x0) - estimated_survival_at(x0, targeted_fit)
    final_survival_se_eic = np.std(EIC_matrix, axis=0, ddof=1) / np.sqrt(data.shape[0])

    return {
        "initial_density": init_density_eval,
        "final_density": final_density_eval,
        "initial_density_se": initial_density_se,
        "initial_survival": init_surv_probs,
        "final_survival": final_surv_probs,
        "initial_survival_se": initial_survival_se,
        "initial_survival_se_eic": initial_survival_se_eic,
        "final_survival_se": final_survival_se,
        "final_survival_se_eic": final_survival_se_eic,
        "best_lambda": best_lambda,
        "evaluation_points": evaluation_points,
        "cv_risks": cv_risks
    }

# ---------------------------
# Multiple Experiment Runner
# ---------------------------
def run_multiple_experiments(n_experiments=10, n_samples=1000,
                             evaluation_points=np.linspace(0.02, 0.98, 20),
                             candidate_lambdas=[55, 60, 65, 70],
                             n_jobs=-1,smoothness_order=1,
                             ridge=1e-6,targeting_points=np.linspace(0.02, 0.98, 20)):
    seeds = [12776 + i for i in range(n_experiments)]
    experiment_func = partial(run_single_experiment, n_samples=n_samples,
                              evaluation_points=evaluation_points,
                              candidate_lambdas=candidate_lambdas,smoothness_order=smoothness_order,
                              ridge=ridge, targeting_points=targeting_points)
    with Pool(processes=n_jobs if n_jobs != -1 else None) as pool:
        results = pool.map(experiment_func, seeds)

    # Assemble density and survival estimates into DataFrames (rows: evaluation points, columns: experiments)
    exp_ids = [f"Exp_{i+1}" for i in range(n_experiments)]
    init_density_df = pd.DataFrame(np.column_stack([res["initial_density"] for res in results]),
                                   index=evaluation_points, columns=exp_ids)
    final_density_df = pd.DataFrame(np.column_stack([res["final_density"] for res in results]),
                                    index=evaluation_points, columns=exp_ids)
    init_survival_df = pd.DataFrame(np.column_stack([res["initial_survival"] for res in results]),
                                    index=evaluation_points, columns=exp_ids)
    final_survival_df = pd.DataFrame(np.column_stack([res["final_survival"] for res in results]),
                                     index=evaluation_points, columns=exp_ids)
    init_density_df_se = pd.DataFrame(np.column_stack([res["initial_density_se"] for res in results]),
                                    index=evaluation_points, columns=exp_ids)
    init_survival_df_se = pd.DataFrame(np.column_stack([res["initial_survival_se"] for res in results]),
                                    index=evaluation_points, columns=exp_ids)
    init_survival_df_se_eic = pd.DataFrame(np.column_stack([res["initial_survival_se_eic"] for res in results]),
                                    index=evaluation_points, columns=exp_ids)
    final_survival_df_se = pd.DataFrame(np.column_stack([res["final_survival_se"] for res in results]),
                                    index=evaluation_points, columns=exp_ids)
    final_survival_df_se_eic = pd.DataFrame(np.column_stack([res["final_survival_se_eic"] for res in results]),
                                    index=evaluation_points, columns=exp_ids)
    best_lambda_df = pd.DataFrame({
        "Experiment": exp_ids,
        "Best_Lambda": [res["best_lambda"] for res in results]
    })
    return init_density_df, final_density_df, init_survival_df, final_survival_df, init_density_df_se, init_survival_df_se,init_survival_df_se_eic, final_survival_df_se,final_survival_df_se_eic, best_lambda_df

# Define parameters
n_samples = 3200
candidate_lambdas_1 = [60, 65, 70, 80]
candidate_lambdas_0 = [3, 5, 8, 10]

smoothness_order = 1
ridge = 1e-6
n_experiments = 500
candidate_lambdas = candidate_lambdas_1

# Run experiments with the given parameters
init_density_df, final_density_df, init_survival_df, final_survival_df, \
init_density_df_se, init_survival_df_se, init_survival_df_se_eic, final_survival_df_se, final_survival_df_se_eic,\
best_lambda_df = run_multiple_experiments(n_experiments=n_experiments,
                                          n_samples=n_samples,
                                          evaluation_points=np.linspace(0.02, 0.98, 20),
                                          smoothness_order=smoothness_order,
                                          candidate_lambdas=candidate_lambdas,
                                          ridge=ridge,
                                          targeting_points=np.linspace(0.02, 0.98, 20))

# Create a base file name incorporating the parameter values
base_name = f"out/hal_n{n_samples}_smooth{smoothness_order}_ridge{ridge}"

# Save DataFrames to CSV files with modified file names
init_density_df.to_csv(f"{base_name}_initial_density.csv", index=True)
final_density_df.to_csv(f"{base_name}_final_density.csv", index=True)
init_survival_df.to_csv(f"{base_name}_initial_survival.csv", index=True)
final_survival_df.to_csv(f"{base_name}_final_survival.csv", index=True)
init_density_df_se.to_csv(f"{base_name}_initial_density_se.csv", index=True)
init_survival_df_se.to_csv(f"{base_name}_initial_survival_se.csv", index=True)
init_survival_df_se_eic.to_csv(f"{base_name}_initial_survival_se_eic.csv", index=True)
final_survival_df_se.to_csv(f"{base_name}_final_survival_se.csv", index=True)
final_survival_df_se_eic.to_csv(f"{base_name}_final_survival_se_eic.csv", index=True)
best_lambda_df.to_csv(f"{base_name}_best_lambda.csv", index=False)

# Produce a bar chart of candidate lambda selection frequency
counts = [ (best_lambda_df["Best_Lambda"] == lam).sum() for lam in candidate_lambdas ]
plt.figure(figsize=(8, 6))
plt.bar(candidate_lambdas, counts, color="skyblue", edgecolor="black")
plt.xlabel("Candidate Lambda Value")
plt.ylabel("Frequency of Selection")
plt.title("Frequency of Best Lambda Selection Across Experiments")
plt.xticks(candidate_lambdas)
plt.tight_layout()
plt.savefig(f"{base_name}_lambda_frequency.png")
plt.show()

print("Saved CSV files and lambda frequency plot.")