# -*- coding: utf-8 -*-
"""IC_Draft.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3O-aK0c7ciygoVXFcse1VJghQ4wkD51
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import cvxpy as cp
from scipy.stats import truncnorm
from multiprocessing import Pool
from functools import partial
import time

# -----------------------------
# Data Generation and Pre‐processing
# -----------------------------
def generate_truncated_normal(n_samples, mean=0.5, std=0.1, lower=0, upper=1):
    a, b = (lower - mean) / std, (upper - mean) / std
    return truncnorm.rvs(a, b, loc=mean, scale=std, size=n_samples)

def generate_inspection_intervals(n_samples, n_intervals=3):
    inspection_times = np.sort(np.random.uniform(0, 1, (n_samples, n_intervals)), axis=1)
    inspection_times = np.hstack([np.zeros((n_samples, 1)), inspection_times, np.ones((n_samples, 1))])
    return inspection_times

def convert_to_interval_censored_data(T, intervals):
    L, R = [], []
    for i, t in enumerate(T):
        left_idx = np.searchsorted(intervals[i], t, side='right') - 1
        L.append(intervals[i][left_idx])
        R.append(intervals[i][left_idx + 1])
    return pd.DataFrame({"L": L, "R": R})

def midpoint_imputation(data, L_col='L', R_col='R', impute_col='W1'):
    df = data.copy()
    df[impute_col] = 0.5 * (df[L_col] + df[R_col])
    return df

def uniform_imputation(data, L_col='L', R_col='R', impute_col='W1'):
    df = data.copy()
    L_vals = df[L_col].values
    R_vals = df[R_col].values
    T_imputed = np.array([
        np.random.uniform(low=L_vals[i], high=R_vals[i]) if R_vals[i] > L_vals[i] else L_vals[i]
        for i in range(len(df))
    ])
    df[impute_col] = T_imputed
    return df

# -----------------------------
# HAL Basis and Likelihood Functions (First–Order HAL)
# -----------------------------
def create_hal_basis_1d(x, knots,smoothness_order=1):
    """
    Create a 1st–order HAL basis.
    For each knot g, the basis is (x - g)_+ = max(0, x-g).
    x and knots should be torch tensors.
    """
    if smoothness_order == 1:
      x_col = x.unsqueeze(1)
      knots_row = knots.unsqueeze(0)
      basis = (x_col - knots_row).clamp(min=0)
      return basis
    elif smoothness_order == 0:
      x_col = x.unsqueeze(1)
      knots_row = knots.unsqueeze(0)
      indicator = (x_col >= knots_row).float()
      return indicator
    else:
        raise ValueError("order must be 0 (zero–order) or 1 (first–order).")


def interval_nll(theta, basis_mid, delta_j, L, R, midpoints):
    n = L.shape[0]
    J = midpoints.shape[0]
    intercept = theta[0]
    coefs = theta[1:]
    log_density_j = intercept + basis_mid.matmul(coefs)
    log_terms_j = log_density_j + torch.log(delta_j)
    logZ = torch.logsumexp(log_terms_j, dim=0)
    big_neg = -1e10
    mask = (midpoints.unsqueeze(0) >= L.unsqueeze(1)) & (midpoints.unsqueeze(0) < R.unsqueeze(1))
    log_terms_2D = log_terms_j.unsqueeze(0).expand(n, J)
    masked_log_terms_2D = torch.where(mask, log_terms_2D, big_neg * torch.ones_like(log_terms_2D))
    partial_sums = torch.logsumexp(masked_log_terms_2D, dim=1)
    nll = -torch.sum(partial_sums) + n * logZ
    return nll

def create_cumulative_indicators_ge(series, grid_points, prefix):
    indicators_dict = {}
    counter = 1
    for value in grid_points:
        counter += 1
        indicator_col = f"{prefix}_ge_{value:.4f}_{counter}"
        indicators_dict[indicator_col] = (series >= value).astype(int)
    return pd.DataFrame(indicators_dict, index=series.index)

def create_basis_functions(data, grid_points, smoothness_order=1,prefix='W1'):
    """
    Create basis functions for HAL.
    For each grid point g, compute (data[prefix] - g)_+.
    Returns a torch tensor of shape (n_samples, len(grid_points)).
    """
    if smoothness_order == 1:
      K = len(grid_points)
      basis_cols = []
      for g in grid_points:
          basis_col = np.maximum(data[prefix].values - g, 0)
          basis_cols.append(basis_col)
      basis_array = np.array(basis_cols).T
      return torch.tensor(basis_array, dtype=torch.float32)
    elif smoothness_order == 0:
      indicators = create_cumulative_indicators_ge(data[prefix], grid_points, prefix=prefix)
      basis_df = pd.concat([indicators], axis=1)
      return torch.tensor(basis_df.values, dtype=torch.float32)
    else:
        raise ValueError("order must be 0 (zero–order) or 1 (first–order).")


def interval_gradient_HAL_init(data, threshold=1e-4, norm_constraint=3,smoothness_order=1):
    """
    Compute an initial density estimate using first–order HAL.
    Returns a dictionary with the estimated density, grid midpoints, and parameters.
    """
    n_samples = len(data)
    grid_points_hal = np.unique(np.concatenate(([0], data['W1'].values, [1])))

    #Knot points are selected as the percentiles.
    # Compute the number of percentiles as the nearest integer of 10*sqrt(n_samples)
    num_percentiles = int(np.rint(10 * np.sqrt(len(data))))
    grid_points_hal = np.percentile(grid_points_hal, np.linspace(0, 100, num_percentiles))


    basis_tensor = create_basis_functions(data, grid_points_hal,smoothness_order=smoothness_order)
    b_ik = basis_tensor.detach().numpy()

    grid_eval = np.linspace(0, 1, 200)
    grid_midpoints = (grid_eval[:-1] + grid_eval[1:]) / 2
    data_grid = pd.DataFrame({'W1': grid_midpoints})
    basis_grid_tensor = create_basis_functions(data_grid, grid_points_hal,smoothness_order=smoothness_order)
    b_jk = basis_grid_tensor.numpy()

    K = len(grid_points_hal) + 1
    theta = cp.Variable(K)
    first_term = -cp.sum(theta[0] + b_ik @ theta[1:])
    delta_j = grid_eval[1:] - grid_eval[:-1]
    log_delta_j = np.log(delta_j)
    log_density_grid = theta[0] + b_jk @ theta[1:]
    log_terms = log_delta_j + log_density_grid
    log_Z = cp.log_sum_exp(log_terms)
    second_term = n_samples * log_Z
    loss = first_term + second_term
    constraints = [cp.norm1(theta[1:]) <= norm_constraint]
    objective = cp.Minimize(loss)
    problem = cp.Problem(objective, constraints)
    try:
        problem.solve(solver="ECOS")
    except Exception as e:
        print("ECOS solver failed in IPCW_HAL_init, falling back to SCS:", e)
        problem.solve(solver="SCS")

    theta_pruned = np.copy(theta.value)
    theta_pruned[1:] = np.where(np.abs(theta.value[1:]) > threshold, theta.value[1:], 0)
    non_zero_indices = np.nonzero(theta_pruned)[0]

    grid_eval = np.linspace(0, 1, 200)
    grid_points_hal_selected = grid_points_hal[non_zero_indices[1:] - 1]
    grid_eval = np.sort(np.unique(np.concatenate((grid_eval, grid_points_hal_selected))))
    grid_midpoints = (grid_eval[:-1] + grid_eval[1:]) / 2
    data_grid = pd.DataFrame({'W1': grid_midpoints})
    basis_grid_tensor = create_basis_functions(data_grid, grid_points_hal,smoothness_order=smoothness_order)
    b_jk = basis_grid_tensor.numpy()
    delta_j = grid_eval[1:] - grid_eval[:-1]

    b_jk_pruned = b_jk[:, non_zero_indices[1:] - 1]
    theta_pruned_values = theta_pruned[non_zero_indices[1:]]
    estimated_log_density = theta_pruned[0] + b_jk_pruned @ theta_pruned_values
    estimated_density = np.exp(estimated_log_density)
    estimated_density /= np.sum(estimated_density * delta_j)

    theta_value = theta_pruned[non_zero_indices]
    return {
        "theta_value": theta_value,
        "optimized_theta": theta.value,
        "pruned_theta": theta_pruned,
        "theta_intercept": theta.value[0],
        "estimated_density": estimated_density,
        "grid_midpoints": grid_midpoints,
        "grid_points_hal_selected": grid_points_hal_selected,
        "theta_selected": theta_pruned_values,
        "b_jk": b_jk_pruned,
        "delta_j": delta_j,
        "grid_eval": grid_eval
    }

def calculate_kl_divergence(true_density, estimated_density, grid_points):
    grid_spacing = np.diff(grid_points)
    grid_spacing = np.append(grid_spacing, grid_spacing[-1])
    normalized_true_density = true_density / np.sum(true_density * grid_spacing)
    normalized_estimated_density = estimated_density / np.sum(estimated_density * grid_spacing)
    epsilon = 1e-10
    normalized_true_density = np.maximum(normalized_true_density, epsilon)
    normalized_estimated_density = np.maximum(normalized_estimated_density, epsilon)
    kl_divergence = np.sum(normalized_true_density * np.log(normalized_true_density / normalized_estimated_density) * grid_spacing)
    return kl_divergence

def compute_total_log_likelihood(data, results):
    theta_param = torch.tensor(results['theta_value'], dtype=torch.float32)
    basis_mid_t = torch.tensor(results['b_jk'], dtype=torch.float32)
    delta_j = torch.tensor(results['delta_j'], dtype=torch.float32)
    L_t = torch.tensor(data["L"].values, dtype=torch.float32)
    R_t = torch.tensor(data["R"].values, dtype=torch.float32)
    midpoints_t = torch.tensor(results['grid_midpoints'], dtype=torch.float32)
    total_log_likelihood = -interval_nll(theta_param, basis_mid_t, delta_j, L_t, R_t, midpoints_t)
    return total_log_likelihood.item()

def split_data_k_folds(data, k):
    n = len(data)
    indices = np.arange(n)
    np.random.shuffle(indices)
    fold_size = n // k
    for i in range(k):
        test_indices = indices[i*fold_size:(i+1)*fold_size]
        train_indices = np.setdiff1d(indices, test_indices)
        data_train = data.iloc[train_indices].reset_index(drop=True)
        data_valid = data.iloc[test_indices].reset_index(drop=True)
        yield data_train, data_valid

def compute_validation_risk_for_lambda(args):
    lamb, data, k, threshold,smoothness_order = args
    validation_risks = []
    for data_train, data_valid in split_data_k_folds(data, k):
        hal_results = interval_gradient_HAL_init(data_train, threshold=threshold, norm_constraint=lamb,smoothness_order=smoothness_order)
        log_likelihood = compute_total_log_likelihood(data_valid, hal_results)
        validation_risks.append(log_likelihood)
    mean_risk = np.mean(validation_risks)
    return lamb, mean_risk

# --- Updated CV_interval_HAL ---
def CV_interval_HAL(data, k, lambda_values, threshold=1e-4, n_jobs=-1,smoothness_order=1):
    """
    Perform k-fold cross-validation for HAL across candidate lambda values.
    When n_jobs==1, run serially to avoid nested pools.
    Returns the best lambda and a dictionary of mean validation risks.
    """
    args = [(lamb, data, k, threshold,smoothness_order) for lamb in lambda_values]
    if n_jobs == 1:
        results = [compute_validation_risk_for_lambda(arg) for arg in args]
    else:
        with Pool(processes=n_jobs if n_jobs != -1 else None) as pool:
            results = pool.map(compute_validation_risk_for_lambda, args)
    mean_validation_risks = dict(results)
    best_lambda = max(mean_validation_risks, key=mean_validation_risks.get)
    return best_lambda, mean_validation_risks

# -----------------------------
# Survival Function and Interpolation (First–Order Integration)
# -----------------------------
def precompute_global_cdf(theta_selected, grid_points_hal_selected, n_grid=500,smoothness_order=1):
    linspace_grid = np.linspace(0, 1, n_grid)
    combined_grid = np.concatenate((linspace_grid, grid_points_hal_selected))
    global_grid = np.unique(combined_grid)
    global_grid = np.sort(global_grid)
    midpoints = (global_grid[:-1] + global_grid[1:]) / 2
    midpoints_t = torch.tensor(midpoints, dtype=torch.float32)
    knots_t = torch.tensor(grid_points_hal_selected, dtype=torch.float32)
    basis_tensor = create_hal_basis_1d(midpoints_t, knots_t,smoothness_order=smoothness_order)
    b_jk = basis_tensor.numpy()
    estimated_log_density = b_jk @ theta_selected
    estimated_density = np.exp(estimated_log_density)
    delta = global_grid[1:] - global_grid[:-1]
    integral = np.sum(estimated_density * delta)
    estimated_density /= integral
    cdf_values = np.cumsum(estimated_density * delta)
    cdf_values[-1] = 1.0
    global_grid_right = global_grid[1:]
    return global_grid_right, cdf_values

def truncated_invert_sampling_interval(L, R, global_grid, global_cdf, num_samples=5):
    cdf_L = np.interp(L, global_grid, global_cdf)
    cdf_R = np.interp(R, global_grid, global_cdf)
    if cdf_R <= cdf_L:
        return np.full(num_samples, L)
    random_probs = cdf_L + (cdf_R - cdf_L) * np.random.rand(num_samples)
    samples = np.interp(random_probs, global_cdf, global_grid)
    return samples

def E_step(data, result, num_samples=5, n_grid=500,smoothness_order=1):
    censored_data = data.copy()
    theta_selected = result['theta_selected']
    grid_points_hal_selected = result['grid_points_hal_selected']
    global_grid, global_cdf = precompute_global_cdf(theta_selected, grid_points_hal_selected, n_grid=n_grid,smoothness_order=smoothness_order)
    imputed_samples_list = []
    start_loop = time.time()
    for idx, row in censored_data.iterrows():
        L, R = row['L'], row['R']
        samples = truncated_invert_sampling_interval(L, R, global_grid, global_cdf, num_samples=num_samples)
        samples_df = pd.DataFrame({
            'L': L,
            'R': R,
            'weights': 1/num_samples,
            'T': samples
        })
        imputed_samples_list.append(samples_df)
    end_loop = time.time()
    print(f"E-step sampling loop time: {end_loop - start_loop:.4f} sec")
    if imputed_samples_list:
        imputed_data = pd.concat(imputed_samples_list, ignore_index=True)
    else:
        imputed_data = pd.DataFrame(columns=['L', 'R', 'weights', 'T'])
    imputed_data['W1'] = imputed_data['T']
    return imputed_data

def M_step(uncensored_augmented, results, old_theta, norm_constraint=20,smoothness_order=1):
    start_time_m_design = time.time()
    grid_points_hal_selected = results['grid_points_hal_selected']
    grid_points_hal = grid_points_hal_selected
    uncensored_data = uncensored_augmented
    uncensored_t = torch.tensor(uncensored_data['W1'].values, dtype=torch.float32)
    knots_t = torch.tensor(grid_points_hal, dtype=torch.float32)
    basis_tensor = create_hal_basis_1d(uncensored_t, knots_t,smoothness_order=smoothness_order)
    b_ik = basis_tensor.detach().numpy()
    grid_eval = np.linspace(0, 1, 200)
    combined_grid = np.concatenate((grid_eval, grid_points_hal_selected))
    filtered_grid = np.unique(combined_grid)
    grid_eval = np.sort(filtered_grid)
    grid_midpoints = (grid_eval[:-1] + grid_eval[1:]) / 2
    data_grid = pd.DataFrame({'W1': grid_midpoints})
    grid_midpoints_t = torch.tensor(grid_midpoints, dtype=torch.float32)
    knots_t_grid = torch.tensor(grid_points_hal, dtype=torch.float32)
    basis_grid_tensor = create_hal_basis_1d(grid_midpoints_t, knots_t_grid,smoothness_order=smoothness_order)
    b_jk = basis_grid_tensor.numpy()
    end_time_m_design = time.time()
    m_step_time_design = end_time_m_design - start_time_m_design
    print(f"M-step Design Matrix Calculation time (sec): {m_step_time_design:.4f}")
    start_time_m_optimize = time.time()
    K = len(grid_points_hal) + 1
    theta = cp.Variable(K)
    weights_M = uncensored_data['weights'].values
    n_samples_weighted = np.sum(weights_M)
    first_term = -cp.sum(cp.multiply(theta[0] + b_ik @ theta[1:], weights_M))
    delta_j = grid_eval[1:] - grid_eval[:-1]
    log_delta_j = np.log(delta_j)
    log_density_grid = theta[0] + b_jk @ theta[1:]
    log_terms = log_delta_j + log_density_grid
    log_Z = cp.log_sum_exp(log_terms)
    second_term = n_samples_weighted * log_Z
    loss = first_term + second_term
    constraints = [cp.norm1(theta) <= norm_constraint]
    objective = cp.Minimize(loss)
    problem = cp.Problem(objective, constraints)
    if old_theta is not None:
        theta.value = old_theta
    try:
        problem.solve(solver="ECOS", warm_start=True)
    except Exception as e:
        print("ECOS solver failed: ", e, "\nUsing SCS instead.")
        problem.solve(solver="SCS", warm_start=True)
    end_time_m_optimize = time.time()
    m_step_time_optimize = end_time_m_optimize - start_time_m_optimize
    print(f"M-step CVXPY optimize time (sec): {m_step_time_optimize:.4f}")
    theta_value = theta.value
    theta_intercept = theta_value[0]
    theta_selected = theta_value[1:]
    grid_eval_fine = np.linspace(0, 1, 1000)
    grid_midpoints_fine = (grid_eval_fine[:-1] + grid_eval_fine[1:]) / 2
    data_grid_fine = pd.DataFrame({'W1': grid_midpoints_fine})
    grid_midpoints_fine_t = torch.tensor(grid_midpoints_fine, dtype=torch.float32)
    knots_t_fine = torch.tensor(grid_points_hal, dtype=torch.float32)
    basis_fine_tensor = create_hal_basis_1d(grid_midpoints_fine_t, knots_t_fine,smoothness_order=smoothness_order)
    b_jk_fine = basis_fine_tensor.numpy()
    delta_j_fine = grid_eval_fine[1:] - grid_eval_fine[:-1]
    estimated_log_density = theta_intercept + b_jk_fine @ theta_selected
    estimated_density = np.exp(estimated_log_density)
    estimated_density /= np.sum(estimated_density * delta_j_fine)
    updated_results = {
        "theta_value": theta_value,
        "theta_selected": theta_selected,
        "theta_intercept": theta_intercept,
        "estimated_density": estimated_density,
        "grid_midpoints": grid_midpoints_fine,
        "grid_points_hal_selected": grid_points_hal_selected,
        "b_jk": b_jk_fine,
        "delta_j": delta_j_fine,
        "grid_eval": grid_eval_fine
    }
    return updated_results

def EM_HAL_algorithm(data, initial_results, tolerance=1e-6, max_iterations=100, num_samples=5, norm_constraint=20,smoothness_order=1):
    iteration = 0
    previous_log_likelihood = None
    log_likelihoods = []
    current_results = initial_results
    initial_log_likelihood = compute_total_log_likelihood(data, current_results)
    print(f"Initial Log-Likelihood: {initial_log_likelihood}")
    log_likelihoods.append(initial_log_likelihood)
    while iteration < max_iterations:
        print(f"Iteration {iteration + 1}")
        start_time_e = time.time()
        uncensored_augmented = E_step(data, current_results, num_samples=num_samples,smoothness_order=smoothness_order)
        end_time_e = time.time()
        e_step_time = end_time_e - start_time_e
        print(f"E-step time (sec): {e_step_time:.4f}")
        start_time_m = time.time()
        old_theta = current_results.get("theta_value", None)
        updated_results = M_step(uncensored_augmented, current_results, old_theta=old_theta, norm_constraint=norm_constraint,smoothness_order=smoothness_order)
        end_time_m = time.time()
        m_step_time = end_time_m - start_time_m
        print(f"M-step time (sec): {m_step_time:.4f}")
        total_log_likelihood = compute_total_log_likelihood(data, updated_results)
        print(f"Total Log-Likelihood: {total_log_likelihood}")
        log_likelihoods.append(total_log_likelihood)
        if previous_log_likelihood is not None:
            log_likelihood_difference = total_log_likelihood - previous_log_likelihood
            print(f"Log-Likelihood Difference: {log_likelihood_difference}")
            if abs(log_likelihood_difference) < tolerance:
                print(f"Convergence achieved at iteration {iteration + 1}")
                break
        previous_log_likelihood = total_log_likelihood
        current_results = updated_results
        iteration += 1
    print("EM algorithm completed.")
    final_results = current_results
    return final_results, log_likelihoods


# ---------------------------
# Survival Function Estimation
# ---------------------------
def compute_survival_from_density(estimator_dict, smoothness_order=1, grid_eval=None):
    """
    Compute the survival function from the estimated density in a numerically stable manner
    using the trapezoidal rule.
    """
    if grid_eval is None:
        grid_eval = estimator_dict.get('grid_eval', np.linspace(0, 1, 1000))

    # Create the design matrix on the evaluation grid
    data_grid = pd.DataFrame({'W1': grid_eval})
    knots = estimator_dict['grid_points_hal_selected']
    basis_tensor = create_basis_functions(data_grid, knots, smoothness_order)
    b_jk = basis_tensor.numpy()

    # Get parameters (with fallbacks)
    theta_intercept = estimator_dict.get('theta_intercept', estimator_dict['theta_value'][0])
    theta_selected = estimator_dict.get('theta_selected', estimator_dict['theta_value'][1:])

    # Compute log-density and then stabilize by subtracting the maximum
    log_density = theta_intercept + b_jk @ theta_selected
    log_density_stable = log_density - np.max(log_density)
    density = np.exp(log_density_stable)

    # Normalize density using the trapezoidal rule
    delta = np.diff(grid_eval)
    integral = np.trapz(density, grid_eval)
    if integral <= 0:
        raise ValueError("Total integral of the density is non-positive.")
    density /= integral

    # Compute the cumulative distribution function (CDF) using the trapezoidal rule
    cdf = np.cumsum((density[:-1] + density[1:]) / 2 * delta)
    cdf = np.insert(cdf, 0, 0)  # start at 0
    cdf /= cdf[-1]  # ensure the CDF ends at 1

    survival = 1 - cdf
    return survival, grid_eval


def compute_survival_probabilities(estimator_dict, evaluation_points, grid_eval=None,smoothness_order=1):
    survival, grid_eval = compute_survival_from_density(estimator_dict, grid_eval=grid_eval,smoothness_order=smoothness_order)
    survival_probs = np.interp(evaluation_points, grid_eval, survival, left=1.0, right=0.0)
    return survival_probs

import numpy as np
import pandas as pd
from scipy.interpolate import interp1d
from scipy.stats import norm
import torch
import matplotlib.pyplot as plt

##############################################
# Poinwise confidence intervals for the density (Helper functions)
##############################################


##############################################
# 1. Compute individual score contributions (Interval-Censored)
##############################################

def compute_individual_score_interval(row, final_results):
    """
    For interval-censored data, compute the score contribution for one observation.

    The score is defined as:
         s_i = E[φ(X) | L_i ≤ X ≤ R_i] - E[φ(X)],
    where the full expectation E[φ(X)] is computed over the entire integration grid,
    and the conditional expectation is computed using only the grid points in [L_i, R_i].

    Parameters:
      row : a row from the data DataFrame (must contain 'L' and 'R')
      final_results : dict, output from your HAL estimation (e.g. interval_gradient_HAL_init)
                      that contains:
                          - "grid_midpoints": 1D numpy array of integration grid midpoints,
                          - "estimated_density": estimated density at these midpoints,
                          - "delta_j": grid interval widths,
                          - "grid_points_hal_selected": the selected knots,
                          - "b_jk": basis functions evaluated on the integration grid.

    Returns:
      score : 1D numpy array (length = number of selected basis functions)
    """
    L = row['L']
    R = row['R']
    # Full expectation of the basis functions:
    E_phi = np.sum(final_results["b_jk"].T * final_results["estimated_density"] * final_results["delta_j"], axis=1)

    # Find grid points within the interval [L, R]
    grid = final_results["grid_midpoints"]
    mask = (grid >= L) & (grid <= R)

    if np.sum(mask) == 0:
        # If no grid points fall into [L, R], we fall back to E_phi.
        cond_exp = E_phi
    else:
        num = np.sum(final_results["b_jk"][mask].T * final_results["estimated_density"][mask] * final_results["delta_j"][mask], axis=1)
        den = np.sum(final_results["estimated_density"][mask] * final_results["delta_j"][mask])
        cond_exp = num / den

    return cond_exp - E_phi

##############################################
# 2. Estimate the covariance matrix of β̂ (Interval-Censored)
##############################################

def estimate_covariance_beta_interval(data, final_results, ridge=1e-6, smoothness_order=1):
    """
    NOTE: THE SMOOTHNESS_ORDER IS ONLY FOR CONVENIENCE AND NOT USED HERE
    Estimate the asymptotic covariance matrix of the non-intercept coefficients β̂
    for interval-censored data by computing the individual score vectors and then
    forming the (inverse) Fisher information.

    That is, if s_i is the score for observation i then define
         I_hat = (1/n) ∑ s_i s_i^T,
    and approximate
         Cov(β̂) ≈ I_hat⁻¹ / n.

    Parameters:
      data : DataFrame with columns 'L' and 'R'
      final_results : dict, output from your HAL estimation (e.g., interval_gradient_HAL_init)

    Returns:
      cov_beta : 2D numpy array (p x p), where p is the number of selected basis functions.
    """
    scores = []
    for _, row in data.iterrows():
        s = compute_individual_score_interval(row, final_results)
        scores.append(s)
    scores = np.array(scores)  # shape (n, p)
    n = scores.shape[0]


    # Form the Fisher information matrix estimate
    I_hat = np.dot(scores.T, scores) / n
    # Add the ridge (regularization) term
    I_hat_reg = I_hat + (ridge/np.sqrt(I_hat.shape[0]))  * np.eye(I_hat.shape[0])  

    try:
        cov_beta = np.linalg.inv(I_hat_reg) / n
    except np.linalg.LinAlgError:
        cov_beta = np.linalg.pinv(I_hat_reg) / n
    return cov_beta

##############################################
# 3. Estimate the density at an arbitrary x
##############################################

def estimated_density_at(x, final_results):
    """
    For any x in [0,1] (or the region of interest), return the estimated density.
    This is done via linear interpolation on the grid midpoints.

    Parameters:
      x : float or array-like, evaluation point(s)
      final_results : dict, must contain "grid_midpoints" and "estimated_density"

    Returns:
      f_x : float or array of density values
    """
    f_interp = interp1d(final_results["grid_midpoints"], final_results["estimated_density"],
                        kind="linear", bounds_error=False, fill_value="extrapolate")
    return f_interp(x)

##############################################
# 4. Compute the gradient of the density
##############################################

def compute_grad_f(x, final_results,smoothness_order):
    """
    Compute the gradient of the estimated density at x with respect to the non-intercept
    coefficients. For interval-censored data the gradient is still defined as
         grad_f(x) = f(x) * [φ(x) - E[φ(X)]],
    where E[φ(X)] is computed over the integration grid.

    Parameters:
      x : float, the evaluation point
      final_results : dict, must contain:
                    - "grid_points_hal_selected": selected HAL knots,
                    - "b_jk": basis functions evaluated on the integration grid,
                    - "estimated_density": estimated density on the grid,
                    - "delta_j": grid interval widths.

    Returns:
      grad_f : 1D numpy array (gradient vector)
    """
    # Get density at x
    f_x = estimated_density_at(x, final_results)

    # Evaluate basis functions at x
    df_x = pd.DataFrame({'W1': [x]})
    phi_x = create_basis_functions(df_x, final_results["grid_points_hal_selected"],smoothness_order=smoothness_order).numpy().flatten()

    # Full expectation of basis functions over the grid:
    E_phi = np.sum(final_results["b_jk"].T * final_results["estimated_density"] * final_results["delta_j"], axis=1)

    return f_x * (phi_x - E_phi)

##############################################
# 5. Compute density variance via the delta method
##############################################

def compute_density_variance(x, final_results, cov_beta,smoothness_order):
    """
    Compute the approximate variance of the estimated density at x using the delta method.

    That is, if
         f(x) = exp(θ₀ + φ(x)^Tβ) / Z,
    then its gradient with respect to β is
         grad_f(x) = f(x) [φ(x) - E[φ(X)]],
    and hence
         Var(f(x)) ≈ grad_f(x)^T · Cov(β̂) · grad_f(x).

    Parameters:
      x : float, the evaluation point
      final_results : dict, contains necessary quantities
      cov_beta : 2D numpy array, covariance matrix of β̂

    Returns:
      var_f : float, the approximate variance of f(x)
    """
    grad = compute_grad_f(x, final_results,smoothness_order=smoothness_order)
    return np.dot(grad, np.dot(cov_beta, grad))

##############################################
# 6. Construct Confidence Intervals for Density
##############################################

def density_confidence_interval(x_values, final_results, cov_beta, alpha=0.05,smoothness_order=1):
    """
    For each evaluation point in x_values, compute the estimated density,
    its standard error (via the delta method), and then construct a (1-α)% confidence interval.

    Parameters:
      x_values : array-like of evaluation points
      final_results : dict, output from your interval-censored HAL estimation
      cov_beta : 2D numpy array, estimated covariance matrix of β̂
      alpha : float, significance level (default 0.05 for 95% CI)

    Returns:
      results_df : DataFrame with columns 'x', 'density', 'se', 'lower', and 'upper'
    """
    z = norm.ppf(1 - alpha/2)
    results = []
    for x in x_values:
        f_x = estimated_density_at(x, final_results)
        var_f = compute_density_variance(x, final_results, cov_beta,smoothness_order=smoothness_order)
        se = np.sqrt(var_f)
        lower = f_x - z * se
        upper = f_x + z * se
        results.append({'x': x, 'density': f_x, 'se': se, 'lower': lower, 'upper': upper})
    return pd.DataFrame(results)

##############################################
# Precompute the Density Gradient on a Fine Uniform Grid
##############################################

def precompute_grad_f_grid(final_results, grid_size=1000,smoothness_order=1):
    """
    Precompute the gradient of the estimated density f(x) on a uniform grid over [0,1].

    Parameters:
      final_results : dict, the HAL estimation result (contains keys used in compute_grad_f)
      grid_size : int, number of points in the uniform grid (default: 1000)

    Returns:
      grid : numpy array of shape (grid_size,), the uniform grid points over [0,1]
      grad_f_grid : numpy array of shape (grid_size, p), where p is the number of non-intercept coefficients,
                    containing grad_f(x) at each grid point.
      delta : float, the uniform grid spacing.
    """
    grid = np.linspace(0, 1, grid_size)
    grad_f_list = []
    for x in grid:
        grad_f_list.append(compute_grad_f(x, final_results,smoothness_order=smoothness_order))
    grad_f_grid = np.array(grad_f_list)  # shape: (grid_size, p)
    delta = grid[1] - grid[0]
    return grid, grad_f_grid, delta

##############################################
# Compute the Survival Gradient Using the Precomputed Grid
##############################################

def compute_grad_S_from_precomputed(x0, grid, grad_f_grid, delta):
    """
    Given a precomputed uniform grid and corresponding grad_f values,
    compute the survival gradient:
         ∇_β S(x0) = ∫_{x0}^1 ∇_β f(y) dy,
    by summing the precomputed gradients for grid points >= x0.

    Parameters:
      x0 : float, evaluation point.
      grid : numpy array, the precomputed uniform grid over [0,1].
      grad_f_grid : numpy array, precomputed gradient values at each grid point.
      delta : float, uniform grid spacing.

    Returns:
      grad_S : 1D numpy array, the approximate gradient vector of S(x0).
    """
    mask = grid >= x0
    grad_S = np.sum(grad_f_grid[mask], axis=0) * delta
    return grad_S

##############################################
# Survival Function and Variance via Delta Method
##############################################

def estimated_survival_at(x0, final_results):
    """
    Estimate the survival function S(x0) = ∫_{x0}^1 f(y) dy using a Riemann sum
    on the original integration grid.
    """
    grid = final_results["grid_midpoints"]
    f = final_results["estimated_density"]
    delta = final_results["delta_j"]
    mask = grid >= x0
    return np.sum(f[mask] * delta[mask])

def compute_survival_variance_precomputed(x0, final_results, cov_beta, grid, grad_f_grid, delta):
    """
    Compute the approximate variance of the survival function S(x0) using the precomputed
    survival gradient and the delta method.

    Var(S(x0)) ≈ (∇_β S(x0))ᵀ · Cov(β) · (∇_β S(x0))
    """
    grad_S = compute_grad_S_from_precomputed(x0, grid, grad_f_grid, delta)
    return np.dot(grad_S, np.dot(cov_beta, grad_S))

def survival_confidence_interval_precomputed(x_values, final_results, cov_beta, grid, grad_f_grid, delta, alpha=0.05):
    """
    For each evaluation point x0 in x_values, compute the survival function S(x0)
    and its (1-α)% confidence interval using the delta method with precomputed gradients.
    """
    z = norm.ppf(1 - alpha/2)
    results = []
    for x0 in x_values:
        S_x0 = estimated_survival_at(x0, final_results)
        var_S = compute_survival_variance_precomputed(x0, final_results, cov_beta, grid, grad_f_grid, delta)
        se = np.sqrt(np.maximum(var_S, 0))
        lower = S_x0 - z * se
        upper = S_x0 + z * se
        results.append({'x': x0, 'survival': S_x0, 'se': se, 'lower': lower, 'upper': upper})
    return pd.DataFrame(results)

def run_single_experiment(seed, n_samples=1000, n_intervals=5,
                          evaluation_points=np.linspace(0, 1, 100),
                          candidate_lambdas=[55, 60, 65, 70],
                          smoothness_order=1,
                          ridge=0):
    """
    Runs one experiment:
      - Generates data and performs uniform imputation.
      - Performs CV (using candidate lambdas around 60) to select the best lambda.
      - Computes an initial density estimate via first–order HAL.
      - Refines the estimate via the EM algorithm.
      - Evaluates both the initial and final estimates for density and survival probabilities at evaluation_points.
    Returns a dictionary with:
      "initial_density": 1D array (len(evaluation_points)) from initial HAL,
      "final_density": 1D array from the EM refinement,
      "initial_survival": 1D array of plug–in survival (initial),
      "final_survival": 1D array of plug–in survival (final),
      "best_lambda": the selected lambda,
      "evaluation_points": the evaluation grid.
    """
    np.random.seed(seed)
    T = generate_truncated_normal(n_samples)
    intervals = generate_inspection_intervals(n_samples, n_intervals)
    data = convert_to_interval_censored_data(T, intervals)
    data = uniform_imputation(data)

    k = 5
    best_lambda, cv_risks = CV_interval_HAL(data, k, candidate_lambdas, threshold=1e-4, n_jobs=1,smoothness_order=smoothness_order)

    initial_results = interval_gradient_HAL_init(data, threshold=1e-4, norm_constraint=best_lambda,smoothness_order=smoothness_order)
    final_results, _ = EM_HAL_algorithm(data, initial_results, tolerance=0.05, max_iterations=100, num_samples=200,\
                                        norm_constraint=best_lambda*5,smoothness_order=smoothness_order)

    # Evaluate initial and final density estimates (linear interpolation)
    initial_density = np.interp(evaluation_points, initial_results["grid_midpoints"], initial_results["estimated_density"])
    final_density = np.interp(evaluation_points, final_results["grid_midpoints"], final_results["estimated_density"])

    # Evaluate plug–in survival probabilities
    initial_survival = compute_survival_probabilities(initial_results, evaluation_points,smoothness_order=smoothness_order)
    final_survival = compute_survival_probabilities(final_results, evaluation_points,smoothness_order=smoothness_order)


    cov_beta = estimate_covariance_beta_interval(data, initial_results, ridge = ridge,smoothness_order=smoothness_order)
    ci_density_df = density_confidence_interval(evaluation_points, initial_results, cov_beta, alpha=0.05,smoothness_order=smoothness_order)
    initial_density_se=ci_density_df['se']
    grid, grad_f_grid, delta = precompute_grad_f_grid(initial_results, grid_size=1000,smoothness_order=smoothness_order)
    surv_ci_df = survival_confidence_interval_precomputed(evaluation_points, initial_results, cov_beta, grid, grad_f_grid, delta, alpha=0.05)
    initial_survival_se=surv_ci_df['se']

    cov_beta = estimate_covariance_beta_interval(data, final_results, ridge = ridge,smoothness_order=smoothness_order)
    ci_density_df = density_confidence_interval(evaluation_points, final_results, cov_beta, alpha=0.05,smoothness_order=smoothness_order)
    final_density_se=ci_density_df['se']
    grid, grad_f_grid, delta = precompute_grad_f_grid(final_results, grid_size=1000,smoothness_order=smoothness_order)
    surv_ci_df = survival_confidence_interval_precomputed(evaluation_points, final_results, cov_beta, grid, grad_f_grid, delta, alpha=0.05)
    final_survival_se=surv_ci_df['se']

    return {
            "initial_density": initial_density,
            "final_density": final_density,
            "initial_density_se": initial_density_se,
            "final_density_se": final_density_se,
            "initial_survival": initial_survival,
            "final_survival": final_survival,
            "initial_survival_se": initial_survival_se,
            "final_survival_se": final_survival_se,
            "best_lambda": best_lambda,
            "evaluation_points": evaluation_points,
            "cv_risks": cv_risks
    }



def run_multiple_experiments(n_experiments=3, n_samples=1000, n_intervals=5,
                                      evaluation_points=np.linspace(0.02, 0.98, 20),
                                      candidate_lambdas=[55, 60, 65, 70],
                                      n_jobs=-1,
                                      smoothness_order=1,
                                      ridge=0):
    """
    Runs multiple experiments in parallel and returns:
      - initial_density_df: DataFrame (rows: evaluation points, columns: experiments) for initial density.
      - final_density_df: DataFrame for final density.
      - initial_survival_df: DataFrame for initial survival.
      - final_survival_df: DataFrame for final survival.
      - best_lambda_df: DataFrame with one row per experiment for the selected best lambda.
    """
    seeds = [12776 + i for i in range(n_experiments)]
    experiment_func = partial(run_single_experiment, n_samples=n_samples, n_intervals=n_intervals,
                                evaluation_points=evaluation_points, candidate_lambdas=candidate_lambdas,smoothness_order=smoothness_order,ridge=ridge)
    with Pool(processes=n_jobs if n_jobs != -1 else None) as pool:
        results = pool.map(experiment_func, seeds)

    # Extract arrays for each estimator
    initial_density_arr = np.column_stack([res["initial_density"] for res in results])
    final_density_arr = np.column_stack([res["final_density"] for res in results])
    initial_survival_arr = np.column_stack([res["initial_survival"] for res in results])
    final_survival_arr = np.column_stack([res["final_survival"] for res in results])

    initial_density_se_arr = np.column_stack([res["initial_density_se"] for res in results])
    final_density_se_arr = np.column_stack([res["final_density_se"] for res in results])
    initial_survival_se_arr = np.column_stack([res["initial_survival_se"] for res in results])
    final_survival_se_arr = np.column_stack([res["final_survival_se"] for res in results])

    experiments = [f"Exp_{i+1}" for i in range(n_experiments)]

    initial_density_df = pd.DataFrame(initial_density_arr, index=evaluation_points, columns=experiments)
    final_density_df = pd.DataFrame(final_density_arr, index=evaluation_points, columns=experiments)
    initial_survival_df = pd.DataFrame(initial_survival_arr, index=evaluation_points, columns=experiments)
    final_survival_df = pd.DataFrame(final_survival_arr, index=evaluation_points, columns=experiments)

    initial_density_df_se = pd.DataFrame(initial_density_se_arr, index=evaluation_points, columns=experiments)
    final_density_df_se = pd.DataFrame(final_density_se_arr, index=evaluation_points, columns=experiments)
    initial_survival_df_se = pd.DataFrame(initial_survival_se_arr, index=evaluation_points, columns=experiments)
    final_survival_df_se = pd.DataFrame(final_survival_se_arr, index=evaluation_points, columns=experiments)

    best_lambda_df = pd.DataFrame({
        "Experiment": experiments,
        "Best_Lambda": [res["best_lambda"] for res in results]
    })




    return  initial_density_df, final_density_df, initial_survival_df, final_survival_df,initial_density_df_se,final_density_df_se, initial_survival_df_se, final_survival_df_se, best_lambda_df

# Define parameters
n_samples = 1600
smoothness_order = 1
ridge = 1e-6
n_experiments = 500
candidate_lambdas_1 = [60, 65, 70, 80]
candidate_lambdas_0 = [3, 5, 8, 10]

candidate_lambdas = candidate_lambdas_1

# Run experiments with the given parameters
init_density_df, final_density_df, init_survival_df, final_survival_df, \
init_density_df_se, final_density_df_se, init_survival_df_se, final_survival_df_se, \
best_lambda_df = run_multiple_experiments(n_experiments=n_experiments,
                                          n_samples=n_samples,
                                          evaluation_points=np.linspace(0.02, 0.98, 20),
                                          smoothness_order=smoothness_order,
                                          candidate_lambdas=candidate_lambdas,
                                          ridge=ridge)

# Create a base file name incorporating the parameter values
base_name = f"out/hal_n{n_samples}_smooth{smoothness_order}_ridge{ridge}"

# Save DataFrames to CSV files with modified file names
init_density_df.to_csv(f"{base_name}_initial_density.csv", index=True)
final_density_df.to_csv(f"{base_name}_final_density.csv", index=True)
init_survival_df.to_csv(f"{base_name}_initial_survival.csv", index=True)
final_survival_df.to_csv(f"{base_name}_final_survival.csv", index=True)
init_density_df_se.to_csv(f"{base_name}_initial_density_se.csv", index=True)
final_density_df_se.to_csv(f"{base_name}_final_density_se.csv", index=True)
init_survival_df_se.to_csv(f"{base_name}_initial_survival_se.csv", index=True)
final_survival_df_se.to_csv(f"{base_name}_final_survival_se.csv", index=True)
best_lambda_df.to_csv(f"{base_name}_best_lambda.csv", index=False)

# Produce a bar chart of candidate lambda selection frequency
counts = [ (best_lambda_df["Best_Lambda"] == lam).sum() for lam in candidate_lambdas ]
plt.figure(figsize=(8, 6))
plt.bar(candidate_lambdas, counts, color="skyblue", edgecolor="black")
plt.xlabel("Candidate Lambda Value")
plt.ylabel("Frequency of Selection")
plt.title("Frequency of Best Lambda Selection Across Experiments")
plt.xticks(candidate_lambdas)
plt.tight_layout()
plt.savefig(f"{base_name}_lambda_frequency.png")
plt.show()

print("Saved CSV files and lambda frequency plot.")

final_density_df_se