# -*- coding: utf-8 -*-
"""Uncensored_Normal_V1_Target_1order_EM_HAL_BIVARIATE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1upMHvYhQnPt9GLmxYpsGLDCk_TEu8OXk
"""

import numpy as np
import pandas as pd
import cvxpy as cp
import matplotlib.pyplot as plt
from multiprocessing import Pool, cpu_count
from scipy.special import logsumexp
from mpl_toolkits.mplot3d import Axes3D  # for 3D plots
import plotly.graph_objects as go
from scipy.stats import multivariate_normal

# =============================================================================
# Helper functions for Integration Grids and Weights
# =============================================================================
def compute_integration_weights(grid_1d):
    """
    Given a sorted 1D array grid_1d, compute integration weights
    using a trapezoidal–like rule.
    """
    grid_1d = np.asarray(grid_1d)
    n = len(grid_1d)
    if n == 1:
        return np.array([1.0])
    dx = np.diff(grid_1d)
    w = np.empty(n)
    w[0] = dx[0] / 2
    w[-1] = dx[-1] / 2
    if n > 2:
        w[1:-1] = (dx[:-1] + dx[1:]) / 2
    return w

def get_integration_grid(integration_grid_T1=None, integration_grid_T2=None, n_points=50):
    """
    If integration_grid_T1 and integration_grid_T2 (1D arrays) are provided,
    create the Cartesian product (as a DataFrame) and compute the outer–product
    of integration weights.
    Otherwise, use a uniform grid over [0,1] with n_points.
    Returns: (grid_df, t1_vals, t2_vals, weights)
      - grid_df is a DataFrame with columns 'T1' and 'T2'
      - t1_vals, t2_vals are the 1D grid arrays
      - weights is a 2D array of the same shape as the grid (for integration).
    """
    if integration_grid_T1 is None or integration_grid_T2 is None:
        # Use uniform grid
        t1_vals = np.linspace(0, 1, n_points)
        t2_vals = np.linspace(0, 1, n_points)
        T1, T2 = np.meshgrid(t1_vals, t2_vals)
        grid_df = pd.DataFrame({'T1': T1.ravel(), 'T2': T2.ravel()})
        dT = 1/(n_points - 1)
        weights = np.full((n_points, n_points), dT * dT)
        return grid_df, t1_vals, t2_vals, weights
    else:
        integration_grid_T1 = np.asarray(integration_grid_T1)
        integration_grid_T2 = np.asarray(integration_grid_T2)
        T1, T2 = np.meshgrid(integration_grid_T1, integration_grid_T2)
        grid_df = pd.DataFrame({'T1': T1.ravel(), 'T2': T2.ravel()})
        w1 = compute_integration_weights(integration_grid_T1)
        w2 = compute_integration_weights(integration_grid_T2)
        weights = np.outer(w2, w1)
        return grid_df, integration_grid_T1, integration_grid_T2, weights

# =============================================================================
# 1. Basis Functions and Density Evaluation
# =============================================================================
def create_bivariate_basis_functions(data, grid_T1, grid_T2, interaction_pairs=None, selected_indices=None):
    """
    Build the design matrix for a first–order HAL bivariate model.
    (Same as your original code.)
    """
    n = data.shape[0]
    intercept = np.ones((n, 1))
    T1_basis = np.column_stack([ ((data['T1'] >= t).astype(int)) * (data['T1'] - t) for t in grid_T1 ])
    T2_basis = np.column_stack([ ((data['T2'] >= t).astype(int)) * (data['T2'] - t) for t in grid_T2 ])
    if interaction_pairs is not None:
        interaction_basis = np.column_stack([
            (((data['T1'] >= t1).astype(int)) * (data['T1'] - t1)) *
            (((data['T2'] >= t2).astype(int)) * (data['T2'] - t2))
            for t1, t2 in interaction_pairs
        ])
    else:
        interaction_list = []
        for t1 in grid_T1:
            for t2 in grid_T2:
                interaction_list.append(
                    (((data['T1'] >= t1).astype(int)) * (data['T1'] - t1)) *
                    (((data['T2'] >= t2).astype(int)) * (data['T2'] - t2))
                )
        interaction_basis = np.column_stack(interaction_list) if interaction_list else np.empty((n, 0))
    X_full = np.hstack([intercept, T1_basis, T2_basis, interaction_basis])
    if selected_indices is not None:
        return X_full[:, selected_indices]
    else:
        return X_full

def evaluate_joint_density(data, theta, grid_T1, grid_T2, interaction_pairs=None, selected_indices=None):
    """
    Evaluate the (unnormalized) joint density f(T1,T2)=exp(Xθ) at the rows of data.
    """
    X = create_bivariate_basis_functions(data, grid_T1, grid_T2, interaction_pairs, selected_indices)
    return np.exp(X @ theta)

# =============================================================================
# 2. Uniform Imputation for Initial Fitting
# =============================================================================
def impute_uniform_bivariate(data):
    data = data.copy()
    imputed_T1 = data['T1_tilde'].copy()
    imputed_T2 = data['T2_tilde'].copy()
    mask1 = data['delta1'] == 0
    imputed_T1[mask1] = data.loc[mask1, 'T1_tilde'] + (1 - data.loc[mask1, 'T1_tilde']) * np.random.rand(mask1.sum())
    mask2 = data['delta2'] == 0
    imputed_T2[mask2] = data.loc[mask2, 'T2_tilde'] + (1 - data.loc[mask2, 'T2_tilde']) * np.random.rand(mask2.sum())
    data_imputed = data.copy()
    data_imputed['T1'] = imputed_T1
    data_imputed['T2'] = imputed_T2
    return data_imputed

# =============================================================================
# 3. Create Evaluation Grid (for plotting only)
# =============================================================================
def create_evaluation_grid(n_points=50):
    t1_vals = np.linspace(0, 1, n_points)
    t2_vals = np.linspace(0, 1, n_points)
    T1, T2 = np.meshgrid(t1_vals, t2_vals)
    grid = pd.DataFrame({'T1': T1.ravel(), 'T2': T2.ravel()})
    return grid, t1_vals, t2_vals

# =============================================================================
# 4. Initial Fit with L1–Constraint and Pruning (CV Stage)
# =============================================================================
def initial_fit_bivariate(data, norm_constraint, grid_T1, grid_T2, interaction_pairs,
                          threshold=1e-4, n_points=50, integration_grid_T1=None, integration_grid_T2=None):
    """
    (a) Impute missing values uniformly.
    (b) Fit the full model using all basis functions.
    (c) Prune coefficients whose absolute value is below threshold.
    """
    data_imputed = impute_uniform_bivariate(data)
    X = create_bivariate_basis_functions(data_imputed, grid_T1, grid_T2, interaction_pairs)
    n, p = X.shape
    # Use the supplied integration grid (or uniform grid if None)
    grid_eval, int_t1, int_t2, weights = get_integration_grid(integration_grid_T1, integration_grid_T2, n_points)
    X_grid = create_bivariate_basis_functions(grid_eval, grid_T1, grid_T2, interaction_pairs)
    area_elements = weights.ravel()  # flatten the weight matrix
    theta = cp.Variable(p)
    data_term = -cp.sum(X @ theta)
    # Use constant weights in the cvxpy log-sum-exp term:
    log_terms = X_grid @ theta + cp.Constant(np.log(area_elements))
    log_Z = cp.log_sum_exp(log_terms)
    norm_term = n * log_Z
    objective = cp.Minimize(data_term + norm_term)
    constraints = [cp.norm1(theta[1:]) <= norm_constraint]
    prob = cp.Problem(objective, constraints)
    prob.solve(solver="SCS")
    theta_fitted = theta.value
    selected_indices = [0] + [i for i in range(1, p) if abs(theta_fitted[i]) >= threshold]
    theta_pruned = theta_fitted[selected_indices]
    return {
        "theta_full": theta_fitted,
        "theta_pruned": theta_pruned,
        "selected_indices": np.array(selected_indices),
        "grid_T1": grid_T1,
        "grid_T2": grid_T2,
        "interaction_pairs": interaction_pairs
    }

# =============================================================================
# 5. Stable Normalization and Validation Likelihood Calculations
# =============================================================================
def compute_Z_pruned(theta_pruned, grid_T1, grid_T2, interaction_pairs, selected_indices,
                     n_points=50, integration_grid_T1=None, integration_grid_T2=None):
    grid_eval, int_t1, int_t2, weights = get_integration_grid(integration_grid_T1, integration_grid_T2, n_points)
    X_grid = create_bivariate_basis_functions(grid_eval, grid_T1, grid_T2, interaction_pairs, selected_indices)
    area_elements = weights.ravel()
    log_f_grid = X_grid @ theta_pruned
    log_Z = logsumexp(log_f_grid + np.log(area_elements))
    Z = np.exp(log_Z)
    return Z, log_Z

def validation_log_prob_bivariate(row, theta_pruned, grid_T1, grid_T2, interaction_pairs, selected_indices,
                                  n_points=50, integration_grid_T1=None, integration_grid_T2=None):
    """
    Compute the log–probability that (T1,T2) falls in the coarsening set for one observation.
    The integration uses the supplied (or uniform) integration grid.
    """
    Z, log_Z = compute_Z_pruned(theta_pruned, grid_T1, grid_T2, interaction_pairs, selected_indices,
                                n_points=n_points, integration_grid_T1=integration_grid_T1, integration_grid_T2=integration_grid_T2)
    t1_obs = row['T1_tilde']
    t2_obs = row['T2_tilde']
    if row['delta1'] == 1 and row['delta2'] == 1:
        df_pt = pd.DataFrame({'T1': [t1_obs], 'T2': [t2_obs]})
        X_pt = create_bivariate_basis_functions(df_pt, grid_T1, grid_T2, interaction_pairs, selected_indices)
        log_f_pt = X_pt @ theta_pruned
        return log_f_pt[0] - log_Z
    elif row['delta1'] == 1 and row['delta2'] == 0:
        # integrate over T2 in [t2_obs,1]
        if integration_grid_T2 is None:
            t2_grid = np.linspace(t2_obs, 1, n_points)
            dt = (1 - t2_obs) / (n_points - 1)
            weights_1d = np.full_like(t2_grid, dt)
        else:
            t2_grid = np.array(integration_grid_T2)
            t2_grid = t2_grid[t2_grid >= t2_obs]
            if len(t2_grid) < 2:
                t2_grid = np.linspace(t2_obs, 1, n_points)
            weights_1d = compute_integration_weights(t2_grid)
        T1_arr = np.full_like(t2_grid, t1_obs)
        df_temp = pd.DataFrame({'T1': T1_arr, 'T2': t2_grid})
        X_temp = create_bivariate_basis_functions(df_temp, grid_T1, grid_T2, interaction_pairs, selected_indices)
        log_vals = X_temp @ theta_pruned
        log_integral = logsumexp(log_vals + np.log(weights_1d))
        return log_integral - log_Z
    elif row['delta1'] == 0 and row['delta2'] == 1:
        # integrate over T1 in [t1_obs,1]
        if integration_grid_T1 is None:
            t1_grid = np.linspace(t1_obs, 1, n_points)
            dt = (1 - t1_obs) / (n_points - 1)
            weights_1d = np.full_like(t1_grid, dt)
        else:
            t1_grid = np.array(integration_grid_T1)
            t1_grid = t1_grid[t1_grid >= t1_obs]
            if len(t1_grid) < 2:
                t1_grid = np.linspace(t1_obs, 1, n_points)
            weights_1d = compute_integration_weights(t1_grid)
        T2_arr = np.full_like(t1_grid, row['T2_tilde'])
        df_temp = pd.DataFrame({'T1': t1_grid, 'T2': T2_arr})
        X_temp = create_bivariate_basis_functions(df_temp, grid_T1, grid_T2, interaction_pairs, selected_indices)
        log_vals = X_temp @ theta_pruned
        log_integral = logsumexp(log_vals + np.log(weights_1d))
        return log_integral - log_Z
    else:
        # integrate over both T1 in [t1_obs,1] and T2 in [t2_obs,1]
        if integration_grid_T1 is None or integration_grid_T2 is None:
            t1_grid = np.linspace(t1_obs, 1, n_points)
            t2_grid = np.linspace(t2_obs, 1, n_points)
            dt1 = (1 - t1_obs) / (n_points - 1)
            dt2 = (1 - t2_obs) / (n_points - 1)
            weights_2d = np.full((n_points, n_points), dt1*dt2)
        else:
            t1_grid = np.array(integration_grid_T1)
            t2_grid = np.array(integration_grid_T2)
            t1_grid = t1_grid[t1_grid >= t1_obs]
            t2_grid = t2_grid[t2_grid >= t2_obs]
            if len(t1_grid) < 2 or len(t2_grid) < 2:
                t1_grid = np.linspace(t1_obs, 1, n_points)
                t2_grid = np.linspace(t2_obs, 1, n_points)
                dt1 = (1 - t1_obs) / (n_points - 1)
                dt2 = (1 - t2_obs) / (n_points - 1)
                weights_2d = np.full((n_points, n_points), dt1*dt2)
            else:
                w1 = compute_integration_weights(t1_grid)
                w2 = compute_integration_weights(t2_grid)
                weights_2d = np.outer(w2, w1)
        T1_mesh, T2_mesh = np.meshgrid(t1_grid, t2_grid)
        df_temp = pd.DataFrame({'T1': T1_mesh.ravel(), 'T2': T2_mesh.ravel()})
        X_temp = create_bivariate_basis_functions(df_temp, grid_T1, grid_T2, interaction_pairs, selected_indices)
        log_vals = X_temp @ theta_pruned
        log_integral = logsumexp(log_vals + np.log(weights_2d.ravel()))
        return log_integral - log_Z

def compute_validation_risk_bivariate(data, model, n_points=50, integration_grid_T1=None, integration_grid_T2=None):
    total_log_prob = 0.0
    for _, row in data.iterrows():
        total_log_prob += validation_log_prob_bivariate(row, model["theta_pruned"],
                                                        model["grid_T1"],
                                                        model["grid_T2"],
                                                        model["interaction_pairs"],
                                                        model["selected_indices"],
                                                        n_points=n_points,
                                                        integration_grid_T1=integration_grid_T1,
                                                        integration_grid_T2=integration_grid_T2)
    return total_log_prob

# =============================================================================
# 6. Cross–Validation Procedure for the Initial Fit
# =============================================================================
def split_data_k_folds(data, k):
    n = len(data)
    indices = np.arange(n)
    np.random.shuffle(indices)
    fold_size = n // k
    folds = []
    for i in range(k):
        test_idx = indices[i*fold_size:(i+1)*fold_size]
        train_idx = np.setdiff1d(indices, test_idx)
        train_data = data.iloc[train_idx].reset_index(drop=True)
        test_data = data.iloc[test_idx].reset_index(drop=True)
        folds.append((train_data, test_data))
    return folds

def compute_cv_risk_for_lambda_bivariate(args):
    """
    For one candidate lambda (L1 norm constraint), perform k–fold CV.
    """
    lamb, data, k, grid_T1, grid_T2, interaction_pairs, threshold, n_points, integration_grid_T1, integration_grid_T2 = args
    folds = split_data_k_folds(data, k)
    risks = []
    for train_data, valid_data in folds:
        model = initial_fit_bivariate(train_data, norm_constraint=lamb,
                                      grid_T1=grid_T1, grid_T2=grid_T2,
                                      interaction_pairs=interaction_pairs,
                                      threshold=threshold, n_points=n_points,
                                      integration_grid_T1=integration_grid_T1,
                                      integration_grid_T2=integration_grid_T2)
        risk = compute_validation_risk_bivariate(valid_data, model, n_points=n_points,
                                                 integration_grid_T1=integration_grid_T1,
                                                 integration_grid_T2=integration_grid_T2)
        risks.append(risk)
    mean_risk = np.mean(risks)
    return lamb, mean_risk


def CV_initial_bivariate(data, k, lambda_values, grid_T1, grid_T2, interaction_pairs, threshold, n_points, n_jobs=-1,
                         integration_grid_T1=None, integration_grid_T2=None):
    args_list = [(lamb, data, k, grid_T1, grid_T2, interaction_pairs, threshold, n_points,
                  integration_grid_T1, integration_grid_T2)
                 for lamb in lambda_values]
    
    # If n_jobs is 1, or if we're already in a child process, run sequentially.
    if n_jobs == 1 or hasattr(mp.current_process(), 'daemon') and mp.current_process().daemon:
        results = list(map(compute_cv_risk_for_lambda_bivariate, args_list))
    else:
        from multiprocessing import Pool
        with Pool(processes=n_jobs) as pool:
            results = pool.map(compute_cv_risk_for_lambda_bivariate, args_list)
    mean_risks = {l: risk for l, risk in results}
    best_lambda = max(mean_risks, key=mean_risks.get)
    return best_lambda, mean_risks


# =============================================================================
# 7. EM Algorithm on the Pruned Model (Using Observed Log–Likelihood)
# =============================================================================
def E_step_bivariate_pruned(data, theta_pruned, grid_T1, grid_T2, interaction_pairs, selected_indices,
                            num_samples=5, n_points=50, integration_grid_T1=None, integration_grid_T2=None):
    """
    For each observation impute missing coordinates from the conditional distribution.
    """
    augmented_samples = []
    # Fully observed:
    fully_obs = data[(data['delta1'] == 1) & (data['delta2'] == 1)].copy()
    fully_obs['T1'] = fully_obs['T1_tilde']
    fully_obs['T2'] = fully_obs['T2_tilde']
    fully_obs['weights'] = 1.0
    augmented_samples.append(fully_obs[['T1','T2','weights']])
    # Case 1: delta1==1, delta2==0 (impute T2)
    case_10 = data[(data['delta1'] == 1) & (data['delta2'] == 0)]
    for idx, row in case_10.iterrows():
        T1_val = row['T1_tilde']
        T2_min = row['T2_tilde']
        if integration_grid_T2 is None:
            t2_grid = np.linspace(T2_min, 1, n_points)
            dt = (1 - T2_min) / (n_points - 1)
            weights_1d = np.full_like(t2_grid, dt)
        else:
            t2_grid = np.array(integration_grid_T2)
            t2_grid = t2_grid[t2_grid >= T2_min]
            if len(t2_grid) < 2:
                t2_grid = np.linspace(T2_min, 1, n_points)
            weights_1d = compute_integration_weights(t2_grid)
        df_temp = pd.DataFrame({'T1': np.full(len(t2_grid), T1_val), 'T2': t2_grid})
        dens = np.exp(create_bivariate_basis_functions(df_temp, grid_T1, grid_T2, interaction_pairs, selected_indices) @ theta_pruned)
        prob = dens / np.sum(dens * weights_1d)
        cdf = np.cumsum(prob * weights_1d)
        cdf /= cdf[-1]
        imputed_T2 = []
        for _ in range(num_samples):
            u = np.random.rand()
            j = np.searchsorted(cdf, u)
            imputed_T2.append(t2_grid[min(j, len(t2_grid)-1)])
        df_imputed = pd.DataFrame({'T1': T1_val, 'T2': imputed_T2})
        df_imputed['weights'] = 1.0 / num_samples
        augmented_samples.append(df_imputed)
    # Case 2: delta1==0, delta2==1 (impute T1)
    case_01 = data[(data['delta1'] == 0) & (data['delta2'] == 1)]
    for idx, row in case_01.iterrows():
        T2_val = row['T2_tilde']
        T1_min = row['T1_tilde']
        if integration_grid_T1 is None:
            t1_grid = np.linspace(T1_min, 1, n_points)
            dt = (1 - T1_min) / (n_points - 1)
            weights_1d = np.full_like(t1_grid, dt)
        else:
            t1_grid = np.array(integration_grid_T1)
            t1_grid = t1_grid[t1_grid >= T1_min]
            if len(t1_grid) < 2:
                t1_grid = np.linspace(T1_min, 1, n_points)
            weights_1d = compute_integration_weights(t1_grid)
        df_temp = pd.DataFrame({'T1': t1_grid, 'T2': np.full(len(t1_grid), T2_val)})
        dens = np.exp(create_bivariate_basis_functions(df_temp, grid_T1, grid_T2, interaction_pairs, selected_indices) @ theta_pruned)
        prob = dens / np.sum(dens * weights_1d)
        cdf = np.cumsum(prob * weights_1d)
        cdf /= cdf[-1]
        imputed_T1 = []
        for _ in range(num_samples):
            u = np.random.rand()
            j = np.searchsorted(cdf, u)
            imputed_T1.append(t1_grid[min(j, len(t1_grid)-1)])
        df_imputed = pd.DataFrame({'T1': imputed_T1, 'T2': T2_val})
        df_imputed['weights'] = 1.0 / num_samples
        augmented_samples.append(df_imputed)
    # Case 3: delta1==0, delta2==0 (impute both)
    case_00 = data[(data['delta1'] == 0) & (data['delta2'] == 0)]
    for idx, row in case_00.iterrows():
        T1_min = row['T1_tilde']
        T2_min = row['T2_tilde']
        if integration_grid_T1 is None or integration_grid_T2 is None:
            t1_grid = np.linspace(T1_min, 1, n_points)
            t2_grid = np.linspace(T2_min, 1, n_points)
            dt1 = (1 - T1_min) / (n_points - 1)
            dt2 = (1 - T2_min) / (n_points - 1)
            weights_2d = np.full((n_points, n_points), dt1*dt2)
        else:
            t1_grid = np.array(integration_grid_T1)
            t2_grid = np.array(integration_grid_T2)
            t1_grid = t1_grid[t1_grid >= T1_min]
            t2_grid = t2_grid[t2_grid >= T2_min]
            if len(t1_grid) < 2 or len(t2_grid) < 2:
                t1_grid = np.linspace(T1_min, 1, n_points)
                t2_grid = np.linspace(T2_min, 1, n_points)
                dt1 = (1 - T1_min) / (n_points - 1)
                dt2 = (1 - T2_min) / (n_points - 1)
                weights_2d = np.full((n_points, n_points), dt1*dt2)
            else:
                w1 = compute_integration_weights(t1_grid)
                w2 = compute_integration_weights(t2_grid)
                weights_2d = np.outer(w2, w1)
        T1_mesh, T2_mesh = np.meshgrid(t1_grid, t2_grid)
        df_temp = pd.DataFrame({'T1': T1_mesh.ravel(), 'T2': T2_mesh.ravel()})
        dens = np.exp(create_bivariate_basis_functions(df_temp, grid_T1, grid_T2, interaction_pairs, selected_indices) @ theta_pruned)
        prob = dens / np.sum(dens * weights_2d.ravel())
        cdf = np.cumsum(prob * weights_2d.ravel())
        cdf /= cdf[-1]
        imputed_T1 = []
        imputed_T2 = []
        for _ in range(num_samples):
            u = np.random.rand()
            j = np.searchsorted(cdf, u)
            imputed_T1.append(df_temp.iloc[j]['T1'])
            imputed_T2.append(df_temp.iloc[j]['T2'])
        df_imputed = pd.DataFrame({'T1': imputed_T1, 'T2': imputed_T2})
        df_imputed['weights'] = 1.0 / num_samples
        augmented_samples.append(df_imputed)
    augmented_data = pd.concat(augmented_samples, ignore_index=True)
    return augmented_data

def M_step_bivariate_pruned(augmented_data, theta_old, grid_T1, grid_T2, interaction_pairs, selected_indices,
                            norm_constraint, n_points=50, integration_grid_T1=None, integration_grid_T2=None):
    """
    M–step update using the pruned basis.
    """
    X_aug = create_bivariate_basis_functions(augmented_data, grid_T1, grid_T2, interaction_pairs, selected_indices)
    weights_data = augmented_data['weights'].values
    n_weighted = np.sum(weights_data)
    grid_eval, int_t1, int_t2, weights = get_integration_grid(integration_grid_T1, integration_grid_T2, n_points)
    X_grid = create_bivariate_basis_functions(grid_eval, grid_T1, grid_T2, interaction_pairs, selected_indices)
    area_elements = weights.ravel()
    p = X_aug.shape[1]
    theta = cp.Variable(p)
    first_term = -cp.sum(cp.multiply(weights_data, X_aug @ theta))
    log_density_grid = X_grid @ theta + cp.Constant(np.log(area_elements))
    log_Z = cp.log_sum_exp(log_density_grid)
    second_term = n_weighted * log_Z
    loss = first_term + second_term
    objective = cp.Minimize(loss)
    constraints = [cp.norm1(theta[1:]) <= norm_constraint]
    prob = cp.Problem(objective, constraints)
    theta.value = theta_old
    prob.solve(solver="SCS", warm_start=True)
    theta_new = theta.value
    return theta_new

def compute_observed_log_likelihood_bivariate_pruned(data, theta_pruned, grid_T1, grid_T2, interaction_pairs,
                                                     selected_indices, n_points, integration_grid_T1, integration_grid_T2):
    total_ll = 0.0
    for _, row in data.iterrows():
        total_ll += validation_log_prob_bivariate(row, theta_pruned, grid_T1, grid_T2,
                                                  interaction_pairs, selected_indices, n_points=n_points,
                                                  integration_grid_T1=integration_grid_T1,
                                                  integration_grid_T2=integration_grid_T2)
    return total_ll

def EM_HAL_algorithm_bivariate_pruned(data, initial_model, norm_constraint, num_samples=5, tolerance=1e-3,
                                      max_iterations=50, n_points=50, integration_grid_T1=None, integration_grid_T2=None):
    """
    Run the EM algorithm using the pruned model.
    """
    theta_current = initial_model["theta_pruned"]
    selected_indices = initial_model["selected_indices"]
    grid_T1 = initial_model["grid_T1"]
    grid_T2 = initial_model["grid_T2"]
    interaction_pairs = initial_model["interaction_pairs"]
    log_likelihoods = []
    for it in range(max_iterations):
        print(f"EM iteration {it+1}")
        augmented_data = E_step_bivariate_pruned(data, theta_current, grid_T1, grid_T2, interaction_pairs,
                                                 selected_indices, num_samples=num_samples, n_points=n_points,
                                                 integration_grid_T1=integration_grid_T1, integration_grid_T2=integration_grid_T2)
        theta_new = M_step_bivariate_pruned(augmented_data, theta_current, grid_T1, grid_T2, interaction_pairs,
                                            selected_indices, norm_constraint, n_points=n_points,
                                            integration_grid_T1=integration_grid_T1, integration_grid_T2=integration_grid_T2)
        obs_ll = compute_observed_log_likelihood_bivariate_pruned(data, theta_new, grid_T1, grid_T2, interaction_pairs,
                                                                 selected_indices, n_points,integration_grid_T1,integration_grid_T2)




        log_likelihoods.append(obs_ll)
        print(f"  Observed log–likelihood: {obs_ll:.4f}")
        if it > 0 and abs(obs_ll - log_likelihoods[-2]) < tolerance:
            print("Convergence achieved.")
            break
        theta_current = theta_new
    final_model = {
        "theta_pruned": theta_current,
        "selected_indices": selected_indices,
        "grid_T1": grid_T1,
        "grid_T2": grid_T2,
        "interaction_pairs": interaction_pairs
    }
    return final_model, log_likelihoods
# =============================================================================
# 9. Targeting M step
# =============================================================================
import numpy as np
import pandas as pd
import torch
import cvxpy as cp
import time

def create_targeting_basis_functions_bivariate(data, targeting_pairs):
    """
    Create a bivariate targeting basis using indicator functions.

    For each targeting pair (t1, t2) in targeting_pairs, this function creates a column
    that equals 1 when both data['T1'] >= t1 and data['T2'] >= t2, and 0 otherwise.

    Parameters
    ----------
    data : pd.DataFrame
        DataFrame with at least columns 'T1' and 'T2'.
    targeting_pairs : list of tuples
        Each tuple is of the form (t1, t2).

    Returns
    -------
    basis_tensor : torch.Tensor
        A tensor of shape (n_samples, number_of_targeting_pairs).
    """
    indicators = {}
    for i, (t1, t2) in enumerate(targeting_pairs):
        col_name = f"targeting_indicator_{i}"
        # Create indicator column: 1 if (T1 >= t1) and (T2 >= t2), else 0.
        indicators[col_name] = ((data['T1'] >= t1) & (data['T2'] >= t2)).astype(int)
    indicators_df = pd.DataFrame(indicators, index=data.index)
    basis_tensor = torch.tensor(indicators_df.values, dtype=torch.float32)
    return basis_tensor

def targeting_M_step_bivariate(augmented_data, results, old_theta, targeting_pairs,
                               norm_constraint=20, n_points=50,
                               integration_grid_T1=None, integration_grid_T2=None):
    """
    Perform a targeting M-step update for the bivariate pruned model.

    The density model is defined as:

        f(T1, T2) = exp(fixed(T1, T2) + targeting(T1, T2)) / Z,

    where:

        fixed(T1, T2) = X_fixed * old_theta,   (built using create_bivariate_basis_functions)
        targeting(T1, T2) = X_targeting * alpha,

    and alpha is the only parameter being updated here.

    Parameters
    ----------
    augmented_data : pd.DataFrame
        Data on which to build the design matrices. Must contain columns 'T1', 'T2', and 'weights'.
    results : dict
        Dictionary with keys:
          - 'grid_T1'
          - 'grid_T2'
          - 'interaction_pairs'
          - 'selected_indices'
        These are used to construct the fixed (pruned) design matrix.
    old_theta : np.ndarray
        Fixed parameter vector from the previous (or pruned) model.
    targeting_pairs : list of tuples
        List of (t1, t2) pairs specifying the new targeting basis functions.
    norm_constraint : float, optional
        L1-norm constraint for the targeting coefficients.
    n_points : int, optional
        Number of integration grid points for the normalization integral.
    integration_grid_T1, integration_grid_T2 : array-like, optional
        If provided, these are used to create the integration grid.

    Returns
    -------
    updated_results : dict
        A dictionary containing the fixed parameters, targeting parameters, and an updated
        estimated density among other things.
    """
    start_time = time.time()

    # Retrieve fixed-design parameters from results
    grid_T1 = results['grid_T1']
    grid_T2 = results['grid_T2']
    interaction_pairs = results['interaction_pairs']
    selected_indices = results['selected_indices']

    # Build the fixed (pruned) design matrix on the data.
    X_fixed_data = create_bivariate_basis_functions(augmented_data, grid_T1, grid_T2,
                                                      interaction_pairs, selected_indices)
    # Build the targeting design matrix on the data.
    X_targeting_data = create_targeting_basis_functions_bivariate(augmented_data, targeting_pairs)

    # Build an integration grid for the normalization term.
    # (Assume get_integration_grid returns: grid_eval, int_t1, int_t2, weights)
    grid_eval, int_t1, int_t2, weights_grid = get_integration_grid(integration_grid_T1, integration_grid_T2, n_points)
    # Evaluate the fixed design on the grid.
    X_fixed_grid = create_bivariate_basis_functions(grid_eval, grid_T1, grid_T2,
                                                    interaction_pairs, selected_indices)
    # Evaluate the targeting design on the grid.
    X_targeting_grid = create_targeting_basis_functions_bivariate(grid_eval, targeting_pairs)

    end_time = time.time()
    print(f"Targeting M-step design matrix time (sec): {end_time - start_time:.4f}")

    # Fixed part of the linear predictor on data and grid.
    fixed_data = X_fixed_data @ old_theta
    fixed_grid = X_fixed_grid @ old_theta

    # Data weights and total weighted sample size.
    weights_data = augmented_data['weights'].values
    n_weighted = np.sum(weights_data)

    # area_elements are the integration weights (assumed to be given in weights_grid).
    area_elements = weights_grid.ravel()

    # Set up the optimization for the targeting coefficients alpha.
    r = X_targeting_data.shape[1]  # number of targeting basis functions
    alpha = cp.Variable(r)

    # Define the full predictor (fixed + targeting) on data and on the grid.
    L_data = fixed_data + X_targeting_data @ alpha
    L_grid = fixed_grid + X_targeting_grid @ alpha

    # Define the loss function.
    # The data term is the (weighted) negative log-likelihood on the data.
    data_term = -cp.sum(cp.multiply(weights_data, L_data))
    # The normalization term uses a log-sum-exp over the integration grid.
    norm_term = n_weighted * cp.log_sum_exp(cp.Constant(np.log(area_elements)) + L_grid)
    loss = data_term + norm_term

    constraints = [cp.norm1(alpha) <= norm_constraint]
    prob = cp.Problem(cp.Minimize(loss), constraints)

    # Warm-start with zeros.
    alpha.value = np.zeros(r)
    try:
        prob.solve(solver="ECOS")
    except Exception as e:
        print("ECOS solver failed: ", e, "\nUsing SCS instead.")
        prob.solve(solver="SCS")

    theta_targeting = alpha.value

    updated_results = {
        "old_theta": old_theta,                 # fixed part remains unchanged
        "theta_targeting": theta_targeting,       # new targeting coefficients
        "theta_pruned": old_theta,                # naming as in your pruned model
        "selected_indices": selected_indices,
        "grid_T1": grid_T1,
        "grid_T2": grid_T2,
        "interaction_pairs": interaction_pairs,
        "targeting_pairs": targeting_pairs
    }

    return updated_results

# =============================================================================
# 10. Targeting E step
# =============================================================================
def compute_Z_targeting(old_theta, theta_targeting, grid_T1, grid_T2, interaction_pairs,
                         selected_indices, targeting_pairs, n_points=50,
                         integration_grid_T1=None, integration_grid_T2=None):
    """
    Compute the normalization constant Z (and log Z) for the full (targeted) model.
    The full linear predictor is defined as
        L = X_fixed @ old_theta + X_targeting @ theta_targeting.
    """
    grid_eval, _, _, weights = get_integration_grid(integration_grid_T1, integration_grid_T2, n_points)
    X_fixed_grid = create_bivariate_basis_functions(grid_eval, grid_T1, grid_T2, interaction_pairs, selected_indices)
    X_target_grid = create_targeting_basis_functions_bivariate(grid_eval, targeting_pairs)
    if isinstance(X_target_grid, torch.Tensor):
        X_target_grid = X_target_grid.numpy()
    log_linpred = X_fixed_grid @ old_theta + X_target_grid @ theta_targeting
    log_Z = logsumexp(log_linpred + np.log(weights.ravel()))
    return np.exp(log_Z), log_Z

def validation_log_prob_bivariate_targeting(row, old_theta, theta_targeting, grid_T1, grid_T2,
                                            interaction_pairs, selected_indices, targeting_pairs,
                                            n_points=50, integration_grid_T1=None, integration_grid_T2=None):
    """
    Compute the log–probability that (T1, T2) (or the corresponding region)
    is observed under the full targeted model.
    """
    _, log_Z = compute_Z_targeting(old_theta, theta_targeting, grid_T1, grid_T2,
                                   interaction_pairs, selected_indices, targeting_pairs,
                                   n_points, integration_grid_T1, integration_grid_T2)
    t1_obs = row['T1_tilde']
    t2_obs = row['T2_tilde']

    # CASE 1: Fully observed
    if row['delta1'] == 1 and row['delta2'] == 1:
        df_pt = pd.DataFrame({'T1': [t1_obs], 'T2': [t2_obs]})
        X_fixed_pt = create_bivariate_basis_functions(df_pt, grid_T1, grid_T2, interaction_pairs, selected_indices)
        X_target_pt = create_targeting_basis_functions_bivariate(df_pt, targeting_pairs)
        if isinstance(X_target_pt, torch.Tensor):
            X_target_pt = X_target_pt.numpy()
        log_f_pt = X_fixed_pt @ old_theta + X_target_pt @ theta_targeting
        return log_f_pt[0] - log_Z

    # CASE 2: T1 observed, T2 missing (integrate T2 from t2_obs to 1)
    elif row['delta1'] == 1 and row['delta2'] == 0:
        if integration_grid_T2 is None:
            t2_grid = np.linspace(t2_obs, 1, n_points)
            dt = (1 - t2_obs) / (n_points - 1)
            weights_1d = np.full_like(t2_grid, dt)
        else:
            t2_grid = np.array(integration_grid_T2)
            t2_grid = t2_grid[t2_grid >= t2_obs]
            if len(t2_grid) < 2:
                t2_grid = np.linspace(t2_obs, 1, n_points)
            weights_1d = compute_integration_weights(t2_grid)
        T1_arr = np.full_like(t2_grid, t1_obs)
        df_temp = pd.DataFrame({'T1': T1_arr, 'T2': t2_grid})
        X_fixed_temp = create_bivariate_basis_functions(df_temp, grid_T1, grid_T2, interaction_pairs, selected_indices)
        X_target_temp = create_targeting_basis_functions_bivariate(df_temp, targeting_pairs)
        if isinstance(X_target_temp, torch.Tensor):
            X_target_temp = X_target_temp.numpy()
        log_vals = X_fixed_temp @ old_theta + X_target_temp @ theta_targeting
        log_integral = logsumexp(log_vals + np.log(weights_1d))
        return log_integral - log_Z

    # CASE 3: T1 missing, T2 observed (integrate T1 from t1_obs to 1)
    elif row['delta1'] == 0 and row['delta2'] == 1:
        if integration_grid_T1 is None:
            t1_grid = np.linspace(t1_obs, 1, n_points)
            dt = (1 - t1_obs) / (n_points - 1)
            weights_1d = np.full_like(t1_grid, dt)
        else:
            t1_grid = np.array(integration_grid_T1)
            t1_grid = t1_grid[t1_grid >= t1_obs]
            if len(t1_grid) < 2:
                t1_grid = np.linspace(t1_obs, 1, n_points)
            weights_1d = compute_integration_weights(t1_grid)
        T2_arr = np.full_like(t1_grid, t2_obs)
        df_temp = pd.DataFrame({'T1': t1_grid, 'T2': T2_arr})
        X_fixed_temp = create_bivariate_basis_functions(df_temp, grid_T1, grid_T2, interaction_pairs, selected_indices)
        X_target_temp = create_targeting_basis_functions_bivariate(df_temp, targeting_pairs)
        if isinstance(X_target_temp, torch.Tensor):
            X_target_temp = X_target_temp.numpy()
        log_vals = X_fixed_temp @ old_theta + X_target_temp @ theta_targeting
        log_integral = logsumexp(log_vals + np.log(weights_1d))
        return log_integral - log_Z

    # CASE 4: Both T1 and T2 missing (integrate over both)
    else:
        if integration_grid_T1 is None or integration_grid_T2 is None:
            t1_grid = np.linspace(t1_obs, 1, n_points)
            t2_grid = np.linspace(t2_obs, 1, n_points)
            dt1 = (1 - t1_obs) / (n_points - 1)
            dt2 = (1 - t2_obs) / (n_points - 1)
            weights_2d = np.full((n_points, n_points), dt1 * dt2)
        else:
            t1_grid = np.array(integration_grid_T1)
            t2_grid = np.array(integration_grid_T2)
            t1_grid = t1_grid[t1_grid >= t1_obs]
            t2_grid = t2_grid[t2_grid >= t2_obs]
            if len(t1_grid) < 2 or len(t2_grid) < 2:
                t1_grid = np.linspace(t1_obs, 1, n_points)
                t2_grid = np.linspace(t2_obs, 1, n_points)
                dt1 = (1 - t1_obs) / (n_points - 1)
                dt2 = (1 - t2_obs) / (n_points - 1)
                weights_2d = np.full((n_points, n_points), dt1 * dt2)
            else:
                w1 = compute_integration_weights(t1_grid)
                w2 = compute_integration_weights(t2_grid)
                weights_2d = np.outer(w2, w1)
        T1_mesh, T2_mesh = np.meshgrid(t1_grid, t2_grid)
        df_temp = pd.DataFrame({'T1': T1_mesh.ravel(), 'T2': T2_mesh.ravel()})
        X_fixed_temp = create_bivariate_basis_functions(df_temp, grid_T1, grid_T2, interaction_pairs, selected_indices)
        X_target_temp = create_targeting_basis_functions_bivariate(df_temp, targeting_pairs)
        if isinstance(X_target_temp, torch.Tensor):
            X_target_temp = X_target_temp.numpy()
        log_vals = X_fixed_temp @ old_theta + X_target_temp @ theta_targeting
        log_integral = logsumexp(log_vals + np.log(weights_2d.ravel()))
        return log_integral - log_Z

def compute_observed_log_likelihood_bivariate_targeting(data, old_theta, theta_targeting, grid_T1, grid_T2,
                                                        interaction_pairs, selected_indices, targeting_pairs,
                                                        n_points=50, integration_grid_T1=None, integration_grid_T2=None):
    total_ll = 0.0
    for _, row in data.iterrows():
        total_ll += validation_log_prob_bivariate_targeting(row, old_theta, theta_targeting,
                                                            grid_T1, grid_T2, interaction_pairs,
                                                            selected_indices, targeting_pairs,
                                                            n_points, integration_grid_T1, integration_grid_T2)
    return total_ll

def E_step_bivariate_targeting(data, old_theta, theta_targeting, grid_T1, grid_T2,
                               interaction_pairs, selected_indices, targeting_pairs,
                               num_samples=5, n_points=50, integration_grid_T1=None, integration_grid_T2=None):
    """
    E–step for the targeted model: For each observation, impute missing coordinates
    from the full model f(T1,T2) = exp(fixed + targeting) / Z.
    """
    augmented_samples = []

    # Fully observed observations:
    fully_obs = data[(data['delta1'] == 1) & (data['delta2'] == 1)].copy()
    fully_obs['T1'] = fully_obs['T1_tilde']
    fully_obs['T2'] = fully_obs['T2_tilde']
    fully_obs['weights'] = 1.0
    augmented_samples.append(fully_obs[['T1', 'T2', 'weights']])

    # Case 1: T1 observed, T2 missing
    case_10 = data[(data['delta1'] == 1) & (data['delta2'] == 0)]
    for idx, row in case_10.iterrows():
        T1_val = row['T1_tilde']
        T2_min = row['T2_tilde']
        if integration_grid_T2 is None:
            t2_grid = np.linspace(T2_min, 1, n_points)
            dt = (1 - T2_min) / (n_points - 1)
            weights_1d = np.full_like(t2_grid, dt)
        else:
            t2_grid = np.array(integration_grid_T2)
            t2_grid = t2_grid[t2_grid >= T2_min]
            if len(t2_grid) < 2:
                t2_grid = np.linspace(T2_min, 1, n_points)
            weights_1d = compute_integration_weights(t2_grid)
        df_temp = pd.DataFrame({'T1': np.full(len(t2_grid), T1_val), 'T2': t2_grid})
        X_fixed = create_bivariate_basis_functions(df_temp, grid_T1, grid_T2, interaction_pairs, selected_indices)
        X_target = create_targeting_basis_functions_bivariate(df_temp, targeting_pairs)
        if isinstance(X_target, torch.Tensor):
            X_target = X_target.numpy()
        dens = np.exp(X_fixed @ old_theta + X_target @ theta_targeting)
        prob = dens / np.sum(dens * weights_1d)
        cdf = np.cumsum(prob * weights_1d)
        cdf /= cdf[-1]
        imputed_T2 = []
        for _ in range(num_samples):
            u = np.random.rand()
            j = np.searchsorted(cdf, u)
            imputed_T2.append(t2_grid[min(j, len(t2_grid)-1)])
        df_imputed = pd.DataFrame({'T1': T1_val, 'T2': imputed_T2})
        df_imputed['weights'] = 1.0 / num_samples
        augmented_samples.append(df_imputed)

    # Case 2: T1 missing, T2 observed
    case_01 = data[(data['delta1'] == 0) & (data['delta2'] == 1)]
    for idx, row in case_01.iterrows():
        T2_val = row['T2_tilde']
        T1_min = row['T1_tilde']
        if integration_grid_T1 is None:
            t1_grid = np.linspace(T1_min, 1, n_points)
            dt = (1 - T1_min) / (n_points - 1)
            weights_1d = np.full_like(t1_grid, dt)
        else:
            t1_grid = np.array(integration_grid_T1)
            t1_grid = t1_grid[t1_grid >= T1_min]
            if len(t1_grid) < 2:
                t1_grid = np.linspace(T1_min, 1, n_points)
            weights_1d = compute_integration_weights(t1_grid)
        df_temp = pd.DataFrame({'T1': t1_grid, 'T2': np.full(len(t1_grid), T2_val)})
        X_fixed = create_bivariate_basis_functions(df_temp, grid_T1, grid_T2, interaction_pairs, selected_indices)
        X_target = create_targeting_basis_functions_bivariate(df_temp, targeting_pairs)
        if isinstance(X_target, torch.Tensor):
            X_target = X_target.numpy()
        dens = np.exp(X_fixed @ old_theta + X_target @ theta_targeting)
        prob = dens / np.sum(dens * weights_1d)
        cdf = np.cumsum(prob * weights_1d)
        cdf /= cdf[-1]
        imputed_T1 = []
        for _ in range(num_samples):
            u = np.random.rand()
            j = np.searchsorted(cdf, u)
            imputed_T1.append(t1_grid[min(j, len(t1_grid)-1)])
        df_imputed = pd.DataFrame({'T1': imputed_T1, 'T2': T2_val})
        df_imputed['weights'] = 1.0 / num_samples
        augmented_samples.append(df_imputed)

    # Case 3: Both T1 and T2 missing
    case_00 = data[(data['delta1'] == 0) & (data['delta2'] == 0)]
    for idx, row in case_00.iterrows():
        T1_min = row['T1_tilde']
        T2_min = row['T2_tilde']
        if integration_grid_T1 is None or integration_grid_T2 is None:
            t1_grid = np.linspace(T1_min, 1, n_points)
            t2_grid = np.linspace(T2_min, 1, n_points)
            dt1 = (1 - T1_min) / (n_points - 1)
            dt2 = (1 - T2_min) / (n_points - 1)
            weights_2d = np.full((n_points, n_points), dt1 * dt2)
        else:
            t1_grid = np.array(integration_grid_T1)
            t2_grid = np.array(integration_grid_T2)
            t1_grid = t1_grid[t1_grid >= T1_min]
            t2_grid = t2_grid[t2_grid >= T2_min]
            if len(t1_grid) < 2 or len(t2_grid) < 2:
                t1_grid = np.linspace(T1_min, 1, n_points)
                t2_grid = np.linspace(T2_min, 1, n_points)
                dt1 = (1 - T1_min) / (n_points - 1)
                dt2 = (1 - T2_min) / (n_points - 1)
                weights_2d = np.full((n_points, n_points), dt1 * dt2)
            else:
                w1 = compute_integration_weights(t1_grid)
                w2 = compute_integration_weights(t2_grid)
                weights_2d = np.outer(w2, w1)
        T1_mesh, T2_mesh = np.meshgrid(t1_grid, t2_grid)
        df_temp = pd.DataFrame({'T1': T1_mesh.ravel(), 'T2': T2_mesh.ravel()})
        X_fixed = create_bivariate_basis_functions(df_temp, grid_T1, grid_T2, interaction_pairs, selected_indices)
        X_target = create_targeting_basis_functions_bivariate(df_temp, targeting_pairs)
        if isinstance(X_target, torch.Tensor):
            X_target = X_target.numpy()
        dens = np.exp(X_fixed @ old_theta + X_target @ theta_targeting)
        prob = dens / np.sum(dens * weights_2d.ravel())
        cdf = np.cumsum(prob * weights_2d.ravel())
        cdf /= cdf[-1]
        imputed_T1 = []
        imputed_T2 = []
        for _ in range(num_samples):
            u = np.random.rand()
            j = np.searchsorted(cdf, u)
            imputed_T1.append(df_temp.iloc[j]['T1'])
            imputed_T2.append(df_temp.iloc[j]['T2'])
        df_imputed = pd.DataFrame({'T1': imputed_T1, 'T2': imputed_T2})
        df_imputed['weights'] = 1.0 / num_samples
        augmented_samples.append(df_imputed)

    augmented_data = pd.concat(augmented_samples, ignore_index=True)
    return augmented_data

# =============================================================================
# 11. EM Targeting
# =============================================================================
def EM_targeting_algorithm_bivariate(data, initial_model, targeting_pairs, norm_constraint_targeting,
                                     num_samples=5, tolerance=1e-3, max_iterations=50, n_points=50,
                                     integration_grid_T1=None, integration_grid_T2=None):
    """
    Perform an iterative EM procedure for updating the targeting (additional) basis coefficients.
    The fixed (pruned) coefficients remain fixed.

    Parameters:
      - data: DataFrame with columns 'T1_tilde', 'T2_tilde', 'delta1', 'delta2'
      - initial_model: Dictionary (as returned by your initial_fit/EM_HAL_algorithm) containing
                       the fixed (pruned) parameters and grid information.
      - targeting_pairs: List of (t1, t2) pairs defining the targeting basis.
      - norm_constraint_targeting: L1–norm constraint for the targeting coefficients.
      - num_samples, tolerance, max_iterations, n_points, integration_grid_T1, integration_grid_T2:
           Options for the imputation/integration steps.

    Returns:
      - final_targeted_model: Dictionary containing the fixed part (old_theta) and updated targeting coefficients.
      - log_likelihoods: A list with the observed log–likelihood at each iteration.
    """
    # Fixed part from the pruned model:
    old_theta = initial_model["theta_pruned"]
    selected_indices = initial_model["selected_indices"]
    grid_T1 = initial_model["grid_T1"]
    grid_T2 = initial_model["grid_T2"]
    interaction_pairs = initial_model["interaction_pairs"]

    # Initialize targeting coefficients (e.g. zeros)
    r = len(targeting_pairs)
    theta_targeting_current = np.zeros(r)

    log_likelihoods = []

    for it in range(max_iterations):
        print(f"Targeting EM iteration {it+1}")
        # E-step: augment the data using the current full model (fixed + targeting)
        augmented_data = E_step_bivariate_targeting(
            data, old_theta, theta_targeting_current, grid_T1, grid_T2, interaction_pairs,
            selected_indices, targeting_pairs, num_samples, n_points, integration_grid_T1, integration_grid_T2
        )
        # M-step: update the targeting coefficients using your targeting M–step routine.
        # (Here we call your previously defined targeting_M_step_bivariate.)
        updated_results = targeting_M_step_bivariate(
            augmented_data, initial_model, old_theta, targeting_pairs, norm_constraint=norm_constraint_targeting,
            n_points=n_points, integration_grid_T1=integration_grid_T1, integration_grid_T2=integration_grid_T2
        )
        theta_targeting_new = updated_results["theta_targeting"]

        # Compute the observed log–likelihood for the full (targeted) model:
        obs_ll = compute_observed_log_likelihood_bivariate_targeting(
            data, old_theta, theta_targeting_new, grid_T1, grid_T2, interaction_pairs,
            selected_indices, targeting_pairs, n_points, integration_grid_T1, integration_grid_T2
        )
        log_likelihoods.append(obs_ll)
        print(f"  Observed log–likelihood: {obs_ll:.4f}")

        # Check for convergence:
        if it > 0 and abs(log_likelihoods[-1] - log_likelihoods[-2]) < tolerance:
            print("Convergence achieved in targeting EM.")
            break

        theta_targeting_current = theta_targeting_new

    final_targeted_model = {
        "old_theta": old_theta,                   # fixed part (unchanged)
        "theta_targeting": theta_targeting_current, # updated targeting coefficients
        "theta_pruned": old_theta,                # for compatibility with your naming
        "selected_indices": selected_indices,
        "grid_T1": grid_T1,
        "grid_T2": grid_T2,
        "interaction_pairs": interaction_pairs,
        "targeting_pairs": targeting_pairs
    }

    return final_targeted_model, log_likelihoods


# =============================================================================
# 12. A "Safe" Exponential for Plotting
# =============================================================================
def safe_exp(x, clip_min=-700, clip_max=700):
    return np.exp(np.clip(x, clip_min, clip_max))


# =============================================================================
# Helper: Compute Full Log Density (Fixed + Targeting)
# =============================================================================
def compute_full_log_density(model, grid_eval):
    """
    Compute the full linear predictor on grid_eval. This is the sum of the fixed (pruned)
    part plus, if present, the targeting part.
    """
    # Fixed (pruned) part:
    X_fixed = create_bivariate_basis_functions(
        grid_eval,
        model["grid_T1"],
        model["grid_T2"],
        model["interaction_pairs"],
        model["selected_indices"]
    )
    log_fixed = X_fixed @ model["theta_pruned"]

    # Check if a targeting component exists:
    if "theta_targeting" in model and "targeting_pairs" in model:
        X_target = create_targeting_basis_functions_bivariate(grid_eval, model["targeting_pairs"])
        if hasattr(X_target, "numpy"):
            X_target = X_target.numpy()
        log_target = X_target @ model["theta_targeting"]
        return log_fixed + log_target
    else:
        return log_fixed


# =============================================================================
# 13. Utility Functions for Model Summary and Density/Survival Computation
# =============================================================================

def compute_density(model, n_points=50, integration_grid_T1=None, integration_grid_T2=None):
    """
    Compute the estimated density on a grid using the full (fixed + targeting, if present)
    model. Returns the integration grid (as a DataFrame), grid values for T1 and T2,
    and a 2D array of estimated densities.
    """
    grid_eval, t1_vals, t2_vals, weights = get_integration_grid(integration_grid_T1, integration_grid_T2, n_points)
    area_elements = weights.ravel()
    log_f = compute_full_log_density(model, grid_eval)
    f = safe_exp(log_f)
    Z = np.sum(f * area_elements)
    density = f / Z
    density = density.reshape(weights.shape)
    return grid_eval, t1_vals, t2_vals, density


def compute_survival(model, n_points=50, integration_grid_T1=None, integration_grid_T2=None):
    """
    Compute the survival function S(t1,t2)=P(T1 > t1, T2 > t2) from the estimated density.
    Uses the inclusion-exclusion formula:
         S(t1,t2) = 1 - F_T1(t1) - F_T2(t2) + F(t1,t2)
    """
    # Get density and grid information.
    _, t1_vals, t2_vals, density = compute_density(model, n_points=n_points,
                                                   integration_grid_T1=integration_grid_T1,
                                                   integration_grid_T2=integration_grid_T2)
    _, _, _, weights = get_integration_grid(integration_grid_T1, integration_grid_T2, n_points)

    # Compute joint CDF by cumulative summation.
    cdf = np.cumsum(np.cumsum(density * weights, axis=0), axis=1)
    F1 = cdf[-1, :]  # marginal CDF for T1 (last row)
    F2 = cdf[:, -1]  # marginal CDF for T2 (last column)
    survival = 1 - F1[np.newaxis, :] - F2[:, np.newaxis] + cdf
    return t1_vals, t2_vals, survival


# =============================================================================
# 14-0. True density and survival
# =============================================================================

def compute_true_density_bivariate(t1_vals, t2_vals, mean=[0.5, 0.5], cov=[[0.05, 0.0], [0.0, 0.05]]):
    """
    Compute the true density of a truncated bivariate normal distribution over the grid defined by t1_vals and t2_vals.

    Parameters
    ----------
    t1_vals : 1D array
        Grid values for T1.
    t2_vals : 1D array
        Grid values for T2.
    mean : list, optional
        Mean vector of the bivariate normal.
    cov : 2x2 array, optional
        Covariance matrix.

    Returns
    -------
    density : 2D array
        True density evaluated on the meshgrid of t1_vals and t2_vals.
    """
    rv = multivariate_normal(mean=mean, cov=cov)
    # Compute normalization constant: probability mass inside [0,1]^2
    Z = rv.cdf([1, 1]) - rv.cdf([1, 0]) - rv.cdf([0, 1]) + rv.cdf([0, 0])

    T1, T2 = np.meshgrid(t1_vals, t2_vals)
    pos = np.dstack((T1, T2))
    pdf_vals = rv.pdf(pos)
    density = pdf_vals / Z
    return density

def compute_true_survival_bivariate(t1_vals, t2_vals, mean=[0.5, 0.5], cov=[[0.05, 0.0], [0.0, 0.05]]):
    """
    Compute the true survival function S(t1,t2)=P(T1 > t1, T2 > t2) on the grid defined by t1_vals and t2_vals.

    This is done by computing the true density using compute_true_density_bivariate,
    then obtaining the joint CDF via cumulative summation with appropriate integration weights,
    and finally applying the inclusion–exclusion formula.

    Parameters
    ----------
    t1_vals : 1D array
        Grid values for T1.
    t2_vals : 1D array
        Grid values for T2.
    mean : list, optional
        Mean vector.
    cov : 2x2 array, optional
        Covariance matrix.

    Returns
    -------
    survival : 2D array
        The survival function evaluated on the grid.
    """
    # Use the provided grid as the integration grid:
    grid_df, t1_grid, t2_grid, weights = get_integration_grid(t1_vals, t2_vals, n_points=len(t1_vals))
    true_density = compute_true_density_bivariate(t1_grid, t2_grid, mean, cov)

    # Compute the joint CDF by cumulative summation (make sure weights are applied)
    cdf = np.cumsum(np.cumsum(true_density * weights, axis=0), axis=1)
    # F_T1(t1): last row; F_T2(t2): last column
    F1 = cdf[-1, :]
    F2 = cdf[:, -1]
    survival = 1 - F1[np.newaxis, :] - F2[:, np.newaxis] + cdf
    return survival

# =============================================================================
# 14. Get true and estimated density/survival surfaces
# =============================================================================
import numpy as np
import pandas as pd
# =============================================================================
# 14. Get true and estimated density/survival surfaces
# =============================================================================
import numpy as np
import pandas as pd


def get_density_surfaces_dataframe_multiple(models, truth_params=None, n_points=50,
                                            integration_grid_T1=None, integration_grid_T2=None):
    """
    Compute bivariate density surfaces for multiple models and return a DataFrame.
    
    Parameters:
      models: dict
          Dictionary of models with keys as model names.
      truth_params: dict (optional)
          Dictionary with keys 'mean' and 'cov' for computing the true density.
      n_points: int
          Number of points in each dimension.
      integration_grid_T1, integration_grid_T2: array-like (optional)
          Custom grids for T1 and T2.
          
    Returns:
      df: pandas.DataFrame
          DataFrame with columns 'T1', 'T2' and one column for each model’s density
          (and 'true_density' if truth_params is provided).
    """
    # Obtain integration grid values and weights.
    grid_eval, t1_vals, t2_vals, weights = get_integration_grid(integration_grid_T1, integration_grid_T2, n_points)
    T1, T2 = np.meshgrid(t1_vals, t2_vals)
    
    # Create a dictionary to collect the data.
    data = {'T1': T1.ravel(), 'T2': T2.ravel()}
    
    # If truth parameters are provided, compute the true density.
    if truth_params is not None:
        mean = truth_params.get('mean', [0.5, 0.5])
        cov = truth_params.get('cov', [[0.05, 0.0], [0.0, 0.05]])
        
        # Compute the true density on [0, 1]x[0, 1].
        def compute_true_density_bivariate(t1_vals, t2_vals, mean, cov):
            rv = multivariate_normal(mean=mean, cov=cov)
            # Compute the normalizing constant over the unit square.
            Z = rv.cdf([1, 1]) - rv.cdf([1, 0]) - rv.cdf([0, 1]) + rv.cdf([0, 0])
            T1_grid, T2_grid = np.meshgrid(t1_vals, t2_vals)
            pdf_vals = rv.pdf(np.dstack((T1_grid, T2_grid)))
            return pdf_vals / Z
        
        true_density = compute_true_density_bivariate(t1_vals, t2_vals, mean, cov)
        data['true_density'] = true_density.ravel()
    
    # For each model, compute the normalized density surface.
    for name, model in models.items():
        # Compute the full log density evaluated on the grid.
        log_f = compute_full_log_density(model, grid_eval)
        # Convert log density to density.
        f = safe_exp(log_f)
        # Normalize using the integration weights.
        Z = np.sum(f * weights.ravel())
        density = (f / Z).reshape(weights.shape)
        data[name] = density.ravel()
        
    # Return the results as a DataFrame.
    df = pd.DataFrame(data)
    return df

####################################################################################################
def create_full_basis_functions(data, model):
    """
    Build the full design matrix for a model.
    If targeting components exist (i.e. if model contains 'theta_targeting' and 'targeting_pairs'),
    the full design is the horizontal concatenation of the fixed design (via create_bivariate_basis_functions)
    and the targeting design (via create_targeting_basis_functions_bivariate).
    Otherwise, it returns the fixed design.
    """
    X_fixed = create_bivariate_basis_functions(data, model["grid_T1"], model["grid_T2"],
                                               model["interaction_pairs"], model["selected_indices"])
    if "theta_targeting" in model and "targeting_pairs" in model:
        X_target = create_targeting_basis_functions_bivariate(data, model["targeting_pairs"])
        if hasattr(X_target, "numpy"):
            X_target = X_target.numpy()
        return np.hstack([X_fixed, X_target])
    else:
        return X_fixed


def integrate_full_design(row, model, n_points=50, integration_grid_T1=None, integration_grid_T2=None):
    """
    For a single observation (row), compute the conditional expectation S_i of the full design
    vector (i.e. the integrated full design vector) over the observation’s coarsening set.
    
    The full design vector is obtained by create_full_basis_functions, which concatenates the fixed
    and, if present, targeting components.
    
    Parameters
    ----------
    row : pandas Series
        Must contain at least 'T1_tilde', 'T2_tilde', 'delta1', 'delta2'.
    model : dict
        Contains fixed keys ("theta_pruned", "grid_T1", "grid_T2", "interaction_pairs", "selected_indices")
        and, optionally, targeting keys ("theta_targeting", "targeting_pairs").
    n_points : int, optional
        Number of integration grid points.
    integration_grid_T1, integration_grid_T2 : array-like, optional
        Custom integration grids; if None a uniform grid on [0,1] is used.
    
    Returns
    -------
    S_i : numpy array
        The conditional expectation (a vector with the same dimension as the full design) for the observation.
    """
    # Construct the full parameter vector.
    if "theta_targeting" in model and "targeting_pairs" in model:
        theta_full = np.concatenate([model["theta_pruned"], model["theta_targeting"]])
    else:
        theta_full = model["theta_pruned"]
    
    # CASE 1: Fully observed: integrate over a singleton.
    if row['delta1'] == 1 and row['delta2'] == 1:
        df_pt = pd.DataFrame({'T1': [row['T1_tilde']], 'T2': [row['T2_tilde']]})
        X_full = create_full_basis_functions(df_pt, model)
        return X_full[0]
    
    # CASE 2: T1 observed, T2 censored.
    elif row['delta1'] == 1 and row['delta2'] == 0:
        t1_val = row['T1_tilde']
        t2_min = row['T2_tilde']
        if integration_grid_T2 is None:
            t2_grid = np.linspace(t2_min, 1, n_points)
            dt = (1 - t2_min) / (n_points - 1)
            weights = np.full_like(t2_grid, dt)
        else:
            t2_grid = np.array(integration_grid_T2)
            t2_grid = t2_grid[t2_grid >= t2_min]
            if len(t2_grid) < 2:
                t2_grid = np.linspace(t2_min, 1, n_points)
                dt = (1 - t2_min) / (n_points - 1)
                weights = np.full_like(t2_grid, dt)
            else:
                weights = compute_integration_weights(t2_grid)
        df_temp = pd.DataFrame({'T1': np.full(len(t2_grid), t1_val), 'T2': t2_grid})
        X_full = create_full_basis_functions(df_temp, model)
        f_vals = np.exp(X_full @ theta_full)
        weight_sum = np.sum(f_vals * weights)
        if weight_sum == 0:
            return np.zeros(X_full.shape[1])
        S_i = np.sum((f_vals * weights)[:, None] * X_full, axis=0) / weight_sum
        return S_i
    
    # CASE 3: T1 censored, T2 observed.
    elif row['delta1'] == 0 and row['delta2'] == 1:
        t2_val = row['T2_tilde']
        t1_min = row['T1_tilde']
        if integration_grid_T1 is None:
            t1_grid = np.linspace(t1_min, 1, n_points)
            dt = (1 - t1_min) / (n_points - 1)
            weights = np.full_like(t1_grid, dt)
        else:
            t1_grid = np.array(integration_grid_T1)
            t1_grid = t1_grid[t1_grid >= t1_min]
            if len(t1_grid) < 2:
                t1_grid = np.linspace(t1_min, 1, n_points)
                dt = (1 - t1_min) / (n_points - 1)
                weights = np.full_like(t1_grid, dt)
            else:
                weights = compute_integration_weights(t1_grid)
        df_temp = pd.DataFrame({'T1': t1_grid, 'T2': np.full(len(t1_grid), t2_val)})
        X_full = create_full_basis_functions(df_temp, model)
        f_vals = np.exp(X_full @ theta_full)
        weight_sum = np.sum(f_vals * weights)
        if weight_sum == 0:
            return np.zeros(X_full.shape[1])
        S_i = np.sum((f_vals * weights)[:, None] * X_full, axis=0) / weight_sum
        return S_i
    
    # CASE 4: Both T1 and T2 censored.
    else:
        t1_min = row['T1_tilde']
        t2_min = row['T2_tilde']
        if integration_grid_T1 is None or integration_grid_T2 is None:
            t1_grid = np.linspace(t1_min, 1, n_points)
            t2_grid = np.linspace(t2_min, 1, n_points)
            dt1 = (1 - t1_min) / (n_points - 1)
            dt2 = (1 - t2_min) / (n_points - 1)
            weights_2d = np.full((n_points, n_points), dt1 * dt2)
        else:
            t1_grid = np.array(integration_grid_T1)
            t2_grid = np.array(integration_grid_T2)
            t1_grid = t1_grid[t1_grid >= t1_min]
            t2_grid = t2_grid[t2_grid >= t2_min]
            if len(t1_grid) < 2 or len(t2_grid) < 2:
                t1_grid = np.linspace(t1_min, 1, n_points)
                t2_grid = np.linspace(t2_min, 1, n_points)
                dt1 = (1 - t1_min) / (n_points - 1)
                dt2 = (1 - t2_min) / (n_points - 1)
                weights_2d = np.full((n_points, n_points), dt1 * dt2)
            else:
                w1 = compute_integration_weights(t1_grid)
                w2 = compute_integration_weights(t2_grid)
                weights_2d = np.outer(w2, w1)
        T1_mesh, T2_mesh = np.meshgrid(t1_grid, t2_grid)
        df_temp = pd.DataFrame({'T1': T1_mesh.ravel(), 'T2': T2_mesh.ravel()})
        X_full = create_full_basis_functions(df_temp, model)
        f_vals = np.exp(X_full @ theta_full)
        weights_2d_flat = weights_2d.ravel()
        weight_sum = np.sum(f_vals * weights_2d_flat)
        if weight_sum == 0:
            return np.zeros(X_full.shape[1])
        S_i = np.sum((f_vals * weights_2d_flat)[:, None] * X_full, axis=0) / weight_sum
        return S_i


def compute_scores_unified(data, model, n_points=50, integration_grid_T1=None, integration_grid_T2=None):
    """
    Compute full score vectors for the model.
    For each observation i, the score is defined as:
         score_i = S_i - E_full,
    where S_i is the conditional expectation (over the integration region defined by censoring)
    of the full design vector and E_full is the overall expectation computed over [0,1]^2.
    
    This function works for both the initial (fixed-only) and the targeted (fixed+targeting) models.
    """
    # Build a full integration grid.
    grid_eval, _, _, weights = get_integration_grid(integration_grid_T1, integration_grid_T2, n_points)
    weights_flat = weights.ravel()
    # Build the full design on the grid.
    X_full_grid = create_full_basis_functions(grid_eval, model)
    if "theta_targeting" in model and "targeting_pairs" in model:
        theta_full = np.concatenate([model["theta_pruned"], model["theta_targeting"]])
    else:
        theta_full = model["theta_pruned"]
    f_full = np.exp(X_full_grid @ theta_full)
    Z = np.sum(f_full * weights_flat)
    E_full = np.sum((f_full * weights_flat)[:, None] * X_full_grid, axis=0) / Z
    scores = []
    for _, row in data.iterrows():
        S_i = integrate_full_design(row, model, n_points, integration_grid_T1, integration_grid_T2)
        scores.append(S_i - E_full)
    return np.vstack(scores)


def get_survival_surfaces_with_CI_dataframe_multiple(models, data, truth_params=None, n_points=50,
                                                      integration_grid_T1=None, integration_grid_T2=None,
                                                      ridge=1e-4):
    """
    Compute bivariate survival surfaces and corresponding 95% confidence intervals
    for multiple models on a grid.
    
    For each model, this function uses compute_scores_unified to form an empirical
    information matrix for the full parameter vector. Then for each grid point (t1,t2),
    it computes the survival probability via survival_and_gradient_unified and applies the delta method
    to obtain standard errors and 95% Wald-type confidence intervals.
    
    Parameters
    ----------
    models : dict
        Dictionary of models with keys as model names. Each model must contain at least the keys
        used in the unified functions (for the fixed part, and optionally, targeting keys).
    data : pd.DataFrame
        The data used for model fitting (must include columns 'T1_tilde', 'T2_tilde', 'delta1', 'delta2').
    truth_params : dict, optional
        Dictionary with keys 'mean' and 'cov' for computing the true survival.
    n_points : int
        Number of grid points in each dimension.
    integration_grid_T1, integration_grid_T2 : array-like, optional
        Custom grids for T1 and T2; if None, uniform grids over [0,1] are used.
    ridge : float, default 1e-4
        Ridge penalty added to the empirical information matrix.
    
    Returns
    -------
    df : pandas DataFrame
        DataFrame with columns 'T1', 'T2' and for each model three columns:
        "<model>_S", "<model>_CI_lower", and "<model>_CI_upper". Also includes 'true_survival'
        if truth_params is provided.
    """
    survival_dict = {}
    ci_lower_dict = {}
    ci_upper_dict = {}
    model_names = list(models.keys())
    
    # Define grid.
    if integration_grid_T1 is None or integration_grid_T2 is None:
        t1_vals = np.linspace(0, 1, n_points)
        t2_vals = np.linspace(0, 1, n_points)
    else:
        t1_vals = np.array(integration_grid_T1)
        t2_vals = np.array(integration_grid_T2)
    T1, T2 = np.meshgrid(t1_vals, t2_vals)
    
    # Optionally compute the true survival.
    df_dict = {'T1': T1.ravel(), 'T2': T2.ravel()}
    if truth_params is not None:
        true_surv = compute_true_survival_bivariate(t1_vals, t2_vals, 
                                                    mean=truth_params.get('mean', [0.5, 0.5]),
                                                    cov=truth_params.get('cov', [[0.05, 0.0], [0.0, 0.05]]))
        df_dict['true_survival'] = true_surv.ravel()
    
    # For each model, compute the empirical covariance matrix via the unified score function.
    for name in model_names:
        mod = models[name]

        #Compute the survival
        t1_vals, t2_vals, survival = compute_survival(
            models[name], n_points=n_points,
            integration_grid_T1=integration_grid_T1,
            integration_grid_T2=integration_grid_T2)
        # Compute the score matrix on the observed data.
        score_matrix = compute_scores_unified(data, mod, n_points=n_points,
                                              integration_grid_T1=integration_grid_T1,
                                              integration_grid_T2=integration_grid_T2)
        n_obs = data.shape[0]
        I_hat = (score_matrix.T @ score_matrix) / n_obs
        cov_theta = np.linalg.inv(I_hat + ridge * np.eye(I_hat.shape[0]))
        
        # Now, for each grid point, compute survival and its gradient.
        S_vals = []
        CI_lower_vals = []
        CI_upper_vals = []
        # Here we use survival_and_gradient_unified (defined below) to compute survival and gradient.
        survival_flat = survival.ravel() 
        idx=0
        for t1 in t1_vals:
            for t2 in t2_vals:
                S_hat, grad_full = survival_and_gradient_unified(mod, t1, t2, n_points=n_points,
                                                                 integration_grid_T1=integration_grid_T1,
                                                                 integration_grid_T2=integration_grid_T2)
                S_hat=survival_flat[idx]
                se = np.sqrt(grad_full.T @ cov_theta @ grad_full)
                S_vals.append(S_hat)
                CI_lower_vals.append(S_hat - 1.96 * se)
                CI_upper_vals.append(S_hat + 1.96 * se)
                idx=idx+1
        survival_dict[name] = np.array(S_vals).reshape(len(t2_vals), len(t1_vals))
        ci_lower_dict[name] = np.array(CI_lower_vals).reshape(len(t2_vals), len(t1_vals))
        ci_upper_dict[name] = np.array(CI_upper_vals).reshape(len(t2_vals), len(t1_vals))
    
    # Build final DataFrame.
    df = pd.DataFrame({'T1': T1.ravel(), 'T2': T2.ravel()})
    for name in model_names:
        df[name + '_S'] = survival_dict[name].ravel()
        df[name + '_CI_lower'] = ci_lower_dict[name].ravel()
        df[name + '_CI_upper'] = ci_upper_dict[name].ravel()
    if 'true_survival' in df_dict:
        df['true_survival'] = df_dict['true_survival']
    return df


def survival_and_gradient_unified(model, t1_threshold, t2_threshold, n_points=50, 
                                  integration_grid_T1=None, integration_grid_T2=None):
    """
    Compute the survival probability S(t1,t2) and the gradient with respect to the full parameter
    vector. This function works for both the initial model (only fixed components) and the targeted
    model (fixed + targeting components). If targeting components are present in model (i.e. if
    'theta_targeting' and 'targeting_pairs' exist), they are included in the full design.
    
    Parameters
    ----------
    model : dict
        Contains the fixed model information (keys "theta_pruned", "grid_T1", "grid_T2", "interaction_pairs",
        "selected_indices") and, optionally, targeting information (keys "theta_targeting", "targeting_pairs").
    t1_threshold, t2_threshold : float
        The thresholds at which to evaluate the survival function.
    n_points : int, optional
        Number of grid points for integration.
    integration_grid_T1, integration_grid_T2 : array-like, optional
        Custom integration grids; if None, a uniform grid over [0,1] is used.
    
    Returns
    -------
    S : float
        The survival probability estimate at (t1_threshold, t2_threshold).
    grad_full : numpy array
        The gradient of S with respect to the full parameter vector.
    """
    grid_df, _, _, weights = get_integration_grid(integration_grid_T1, integration_grid_T2, n_points)
    weights_flat = weights.ravel()
    X_fixed = create_bivariate_basis_functions(grid_df, model["grid_T1"], model["grid_T2"],
                                               model["interaction_pairs"], model["selected_indices"])
    if "theta_targeting" in model and "targeting_pairs" in model:
        X_target = create_targeting_basis_functions_bivariate(grid_df, model["targeting_pairs"])
        if hasattr(X_target, "numpy"):
            X_target = X_target.numpy()
        X_full = np.hstack([X_fixed, X_target])
        theta_full = np.concatenate([model["theta_pruned"], model["theta_targeting"]])
    else:
        X_full = X_fixed
        theta_full = model["theta_pruned"]
    f_full = np.exp(X_full @ theta_full)
    Z = np.sum(f_full * weights_flat)

    # Identify grid points within the survival region: {T1 >= t1_threshold, T2 >= t2_threshold}.
    grid_T1_vals = grid_df['T1']
    grid_T2_vals = grid_df['T2']
    region_mask1 = (grid_T1_vals <= t1_threshold) 
    region_mask2 = (grid_T2_vals <= t2_threshold)
    region_mask12 = (grid_T1_vals <= t1_threshold) & (grid_T2_vals <= t2_threshold)
    
    # Compute A = ∫_{region} exp{X(u)^T theta} du.
    A1 = np.sum(f_full[region_mask1] * weights_flat[region_mask1])
    A2 = np.sum(f_full[region_mask2] * weights_flat[region_mask2])
    A12 = np.sum(f_full[region_mask12] * weights_flat[region_mask12])
    
    S1 = A1/ Z
    S2 = A2/ Z
    S12 = A12/ Z
    S=1-S1-S2+S12
    
    # Compute gradients:
    region_mask = (grid_T1_vals > t1_threshold) & (grid_T2_vals > t2_threshold)
    grad_A = np.sum((f_full[region_mask] * weights_flat[region_mask])[:, None] * X_full[region_mask, :], axis=0)
    grad_Z = np.sum((f_full * weights_flat)[:, None] * X_full, axis=0)
    grad_full = (grad_A - S * grad_Z) / Z
    return S, grad_full





####################################################################################################


# =============================================================================
# Helper function: Sample from a truncated bivariate normal
# =============================================================================
def sample_truncated_bivariate_normal(n_samples, mean, cov, lower, upper):
    """
    Sample from a bivariate normal distribution and reject samples that fall
    outside the rectangular region defined by lower and upper bounds.

    Parameters
    ----------
    n_samples : int
        Number of desired samples.
    mean : list or array-like of length 2
        Mean vector (e.g. [0.5, 0.5]).
    cov : 2x2 array-like
        Covariance matrix.
    lower : list or array-like of length 2
        Lower bounds for T1 and T2 (e.g. [0, 0]).
    upper : list or array-like of length 2
        Upper bounds for T1 and T2 (e.g. [1, 1]).

    Returns
    -------
    samples : np.ndarray, shape (n_samples, 2)
        The accepted samples.
    """
    samples = []
    while len(samples) < n_samples:
        candidate = multivariate_normal.rvs(mean=mean, cov=cov)
        if np.all(candidate >= lower) and np.all(candidate <= upper):
            samples.append(candidate)
    return np.array(samples)

# =============================================================================
# 8. Main: Data Simulation, initial and EM Model Fitting
# =============================================================================

def simulation_run(sim, n_samples):
        # Optionally, set a unique seed per simulation so the results differ.
        np.random.seed(4250 + sim)
        # Parameters for the bivariate normal (peak around [0.5, 0.5])
        mean = [0.5, 0.5]
        # Adjust the covariance matrix to control spread.
        # Here we use a diagonal covariance matrix with a relatively small variance.
        cov = [[0.05, 0.0], [0.0, 0.05]]
        lower = [0, 0]
        upper = [1, 1]
        samples = sample_truncated_bivariate_normal(n_samples, mean, cov, lower, upper)
        T1_full = samples[:, 0]
        T2_full = samples[:, 1]

        C1 = np.random.uniform(5, 6, n_samples)
        C2 = np.random.uniform(5, 6, n_samples)
        T1_tilde = np.minimum(T1_full, C1)
        T2_tilde = np.minimum(T2_full, C2)
        delta1 = (T1_full <= C1).astype(int)
        delta2 = (T2_full <= C2).astype(int)
        data_biv = pd.DataFrame({
            "T1_tilde": T1_tilde,
            "delta1": delta1,
            "T2_tilde": T2_tilde,
            "delta2": delta2
        })

        ######FOR CV ONLY######
        # --- Construct Basis Grids ---
        K_main = 10
        grid_T1_main = np.percentile(data_biv['T1_tilde'], np.linspace(0, 100, K_main))
        grid_T2_main = np.percentile(data_biv['T2_tilde'], np.linspace(0, 100, K_main))
        K_interact = 2
        grid_T1_interact = np.percentile(data_biv['T1_tilde'], np.linspace(0, 100, K_interact))
        grid_T2_interact = np.percentile(data_biv['T2_tilde'], np.linspace(0, 100, K_interact))
        interaction_pairs = [(t1, t2) for t1 in grid_T1_interact for t2 in grid_T2_interact]
        grid_T1 = grid_T1_main
        grid_T2 = grid_T2_main

        # --- Define Custom Integration Grids (if desired) ---
        # For example, here we use uniform grids of 50 points, but you could supply non–uniform arrays.
        n_points_cv = 10
        custom_integration_T1 = np.sort(np.unique(np.concatenate((grid_T1_main, grid_T1_interact,np.linspace(0, 1, n_points_cv)))))
        custom_integration_T2 = np.sort(np.unique(np.concatenate((grid_T2_main, grid_T2_interact,np.linspace(0, 1, n_points_cv)))))


        # --- CV Parameters ---
        lambda_values = [2,5, 10, 15, 20, 25, 40, 60, 80, 100, 120]
        k_folds = 3
        threshold = 1e-4

        print("Running initial CV to select lambda...")
        best_lambda, mean_risks = CV_initial_bivariate(data_biv, k=k_folds, lambda_values=lambda_values,
                                                        grid_T1=grid_T1, grid_T2=grid_T2,
                                                        interaction_pairs=interaction_pairs,
                                                        threshold=threshold, n_points=n_points_cv,
                                                        integration_grid_T1=custom_integration_T1,
                                                        integration_grid_T2=custom_integration_T2, 
                                                        n_jobs=1)  # Use 1 job to disable parallel processing.
        print("Best lambda from CV:", best_lambda)
        for l, risk in mean_risks.items():
            print(f"  Lambda = {l}: Mean validation log–prob = {risk:.4f}")



        ######FOR THE INITIAL######
        # --- Construct Basis Grids ---
        K_main = 20
        grid_T1_main = np.percentile(data_biv['T1_tilde'], np.linspace(0, 100, K_main))
        grid_T2_main = np.percentile(data_biv['T2_tilde'], np.linspace(0, 100, K_main))
        K_interact = 5
        grid_T1_interact = np.percentile(data_biv['T1_tilde'], np.linspace(0, 100, K_interact))
        grid_T2_interact = np.percentile(data_biv['T2_tilde'], np.linspace(0, 100, K_interact))
        interaction_pairs = [(t1, t2) for t1 in grid_T1_interact for t2 in grid_T2_interact]
        grid_T1 = grid_T1_main
        grid_T2 = grid_T2_main

        # --- Define Custom Integration Grids (if desired) ---
        # For example, here we use uniform grids of 50 points, but you could supply non–uniform arrays.
        n_points_cv = 20
        custom_integration_T1 = np.sort(np.unique(np.concatenate((grid_T1_main, grid_T1_interact,np.linspace(0, 1, n_points_cv)))))
        custom_integration_T2 = np.sort(np.unique(np.concatenate((grid_T2_main, grid_T2_interact,np.linspace(0, 1, n_points_cv)))))

        # --- Initial Fit on Full Data ---
        initial_model = initial_fit_bivariate(data_biv, norm_constraint=best_lambda,
                                                grid_T1=grid_T1, grid_T2=grid_T2,
                                                interaction_pairs=interaction_pairs,
                                                threshold=threshold, n_points=n_points_cv,
                                                integration_grid_T1=custom_integration_T1,
                                                integration_grid_T2=custom_integration_T2)

        # --- Run Full EM Algorithm ---
        norm_constraint_EM = 5 * best_lambda
        print("\nRunning full EM algorithm using the selected (pruned) model...")
        final_model, ll_history = EM_HAL_algorithm_bivariate_pruned(data_biv, initial_model,
                                                                    norm_constraint=norm_constraint_EM,
                                                                    num_samples=20,
                                                                    tolerance=1e-1,
                                                                    max_iterations=50,
                                                                    n_points=n_points_cv,
                                                                    integration_grid_T1=custom_integration_T1,
                                                                    integration_grid_T2=custom_integration_T2)
        print("\nEM algorithm completed.")
        print("Log–likelihood history:", ll_history)

        targeting_pairs = [(t1, t2) for t1 in [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
                                for t2 in [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]]

        norm_constraint_targeting = 5 * best_lambda  # or another value as desired

        ##########################################
        ## TARGETING FROM THE INITIAL MODEL
        ##########################################
        final_targeted_model, log_likelihoods_targeting = EM_targeting_algorithm_bivariate(
            data_biv, initial_model, targeting_pairs, norm_constraint_targeting, num_samples=20,
            tolerance=1e-1, max_iterations=100, n_points=n_points_cv,
            integration_grid_T1=custom_integration_T1, integration_grid_T2=custom_integration_T2
        )


        #Only evaluate on a grid of 0.02*0.02
        # Get the density surfaces (interactive Plotly figure).

        all_density_models = {"Initial_1": initial_model,
                              "Final_5": final_model,
                              "NPMLE_Targeted": final_targeted_model
                             }

        n_points=10

        df_density = get_density_surfaces_dataframe_multiple(all_density_models,
                                                        truth_params={'mean': [0.5, 0.5],
                                                                        'cov': [[0.05, 0.0], [0.0, 0.05]]},
                                                        n_points=n_points,
                                                        integration_grid_T1=None,
                                                        integration_grid_T2=None)
        # To plot survival surfaces interactively:
        n_points=200
        df_survival = get_survival_surfaces_with_CI_dataframe_multiple(all_density_models,
                                                                        data=data_biv,
                                                                        truth_params={'mean': [0.5, 0.5],
                                                                                    'cov': [[0.05, 0.0], [0.0, 0.05]]},
                                                                        n_points=n_points,
                                                                        integration_grid_T1=None,
                                                                        integration_grid_T2=None,
                                                                        ridge=1e-3)

        return df_density, df_survival


import os
import pickle
from multiprocessing import Pool, cpu_count
import multiprocessing as mp


if __name__ == '__main__':
    B = 100
    n_samples_value = 500  # You can adjust this as needed.
    results_all = []  # This will store all simulation results.

    # Process the simulations in chunks of 10.
    chunk_size = 10
    for chunk_start in range(0, B, chunk_size):
        chunk_end = min(chunk_start + chunk_size, B)
        # Create argument tuples for this chunk.
        args_chunk = [(sim, n_samples_value) for sim in range(chunk_start, chunk_end)]
        
        # Run simulations for the current chunk.
        with Pool(processes=cpu_count()) as pool:
            chunk_results = pool.starmap(simulation_run, args_chunk)
        results_all.extend(chunk_results)
        
        # Unzip the results into two lists (assuming simulation_run returns a tuple).
        density_dfs, survival_dfs = zip(*results_all)
        
        # Build filenames that include the current round (chunk_end).
        density_filename = os.path.join("out", f"FineGridEval_{chunk_end}_TargetFromInitial_NPMLE_uncensored_density_result_TargetingGRID0.1s_nSamples{n_samples_value}.pkl")
        survival_filename = os.path.join("out", f"FineGridEval_{chunk_end}_TargetFromInitial_NPMLE_uncensored_survival_results_TargetingGRID0.1_nSamples{n_samples_value}.pkl")
        
        # Save the current results.
        with open(density_filename, 'wb') as f:
            pickle.dump(density_dfs, f)
        with open(survival_filename, 'wb') as f:
            pickle.dump(survival_dfs, f)
        
        print(f"Intermediate results saved after {chunk_end} rounds.")