# -*- coding: utf-8 -*-
"""RC_Draft.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pNebs-Kox9612dv0feMkk5Z6vI_RyZHP
"""

import numpy as np
import pandas as pd
from scipy.stats import truncnorm
from scipy.interpolate import interp1d
import matplotlib.pyplot as plt
import cvxpy as cp
import torch
from lifelines import KaplanMeierFitter
from multiprocessing import Pool
import time
from functools import partial
from scipy.stats import norm

# ---------------------------
# Data Generation Functions
# ---------------------------
def generate_truncated_normal(n_samples, mean=0.5, std=0.1, lower=0, upper=1):
    """Generate event times from a truncated normal distribution on [lower, upper]."""
    a, b = (lower - mean) / std, (upper - mean) / std
    return truncnorm.rvs(a, b, loc=mean, scale=std, size=n_samples)

def generate_uniform(n_samples):
    """Generate censoring times from a uniform distribution on [0,1]."""
    return np.random.uniform(0, 1, n_samples)

def convert_to_survival_data(T, C):
    """
    Given true event times T and censoring times C, create right-censored observations.
    Returns a DataFrame with columns:
      - T_tilde: observed time = min(T, C)
      - delta: event indicator (1 if event is observed, 0 if censored)
    """
    T_tilde = np.minimum(T, C)
    delta = (T <= C).astype(int)
    return pd.DataFrame({"T_tilde": T_tilde, "delta": delta})

# ---------------------------
# First-Order HAL Density Estimation Functions
# ---------------------------
def create_cumulative_indicators_ge(series, grid_points, prefix):
    indicators_dict = {}
    counter = 1
    for value in grid_points:
        counter += 1
        indicator_col = f"{prefix}_ge_{value:.4f}_{counter}"
        indicators_dict[indicator_col] = (series >= value).astype(int)
    return pd.DataFrame(indicators_dict, index=series.index)


def create_basis_functions(data, grid_points, smoothness_order=1,prefix='W1'):
    """
    Create first-order basis functions defined as (x - g)_+ = max(0, x - g)
    for each knot g in grid_points. Returns a torch tensor.
    """
    if smoothness_order == 0:
        # Zero–order HAL: use cumulative indicator functions.
        indicators = create_cumulative_indicators_ge(data[prefix], grid_points, prefix)
        basis_df = pd.concat([indicators], axis=1)
        return torch.tensor(basis_df.values, dtype=torch.float32)
    elif smoothness_order == 1:
        # First–order HAL: use ramp functions (x - g)_+.
        basis_cols = []
        for g in grid_points:
            # (x - g)_+ = max(0, x - g)
            basis_col = np.maximum(data[prefix].values - g, 0)
            basis_cols.append(basis_col)
        basis_array = np.array(basis_cols).T  # shape: (n_samples, number of knots)
        return torch.tensor(basis_array, dtype=torch.float32)
    else:
        raise ValueError("order must be 0 (zero–order) or 1 (first–order).")


def IPCW_HAL_init(data, threshold=1e-4, norm_constraint=3,smoothness_order=1):
    """
    First–order HAL estimator for the density from right–censored data using inverse probability censoring weights.
    Basis functions are (x - g)_+.
    Returns a dictionary with estimated parameters and evaluation grid.
    """
    # Fit a Kaplan–Meier model on the censoring process (1-delta)
    kmf = KaplanMeierFitter()
    kmf.fit(durations=data['T_tilde'], event_observed=1 - data['delta'])

    # Restrict to uncensored data
    uncensored = data[data['delta'] == 1].copy()
    uncensored['W1'] = uncensored['T_tilde']
    uncensored['ipcw_weight'] = uncensored['T_tilde'].apply(lambda t: 1 / kmf.survival_function_at_times(t).values[0])

    # Define knots from uncensored event times plus boundaries 0 and 1.
    grid_points_hal = np.unique(np.concatenate(([0], uncensored['W1'].values, [1])))


    #Knot points are selected as the percentiles.
    # Compute the number of percentiles as the nearest integer of 10*sqrt(n_samples)
    num_percentiles = int(np.rint(10 * np.sqrt(len(data))))
    grid_points_hal = np.percentile(grid_points_hal, np.linspace(0, 100, num_percentiles))

    # Compute basis for the uncensored data
    basis_tensor = create_basis_functions(uncensored, grid_points_hal,smoothness_order)
    b_ik = basis_tensor.numpy()

    # Create an integration grid for normalization
    grid_eval = np.linspace(0, 1, 200)
    grid_midpoints = (grid_eval[:-1] + grid_eval[1:]) / 2
    data_grid = pd.DataFrame({'W1': grid_midpoints})
    basis_grid_tensor = create_basis_functions(data_grid, grid_points_hal,smoothness_order)
    b_jk = basis_grid_tensor.numpy()

    K = len(grid_points_hal) + 1  # intercept plus basis functions
    theta = cp.Variable(K)

    weights = uncensored['ipcw_weight'].values
    n_weighted = np.sum(weights)

    first_term = -cp.sum((theta[0] + b_ik @ theta[1:]) @ weights)
    delta_j = grid_eval[1:] - grid_eval[:-1]
    log_delta_j = np.log(delta_j)
    log_density_grid = theta[0] + b_jk @ theta[1:]
    log_terms = log_delta_j + log_density_grid
    log_Z = cp.log_sum_exp(log_terms)
    second_term = n_weighted * log_Z
    loss = first_term + second_term
    constraints = [cp.norm1(theta) <= norm_constraint]
    problem = cp.Problem(cp.Minimize(loss), constraints)

    try:
        problem.solve(solver="ECOS")
    except Exception as e:
        print("ECOS solver failed in IPCW_HAL_init, falling back to SCS:", e)
        problem.solve(solver="SCS")

    # Prune small coefficients
    theta_pruned = np.copy(theta.value)
    theta_pruned[1:] = np.where(np.abs(theta.value[1:]) > threshold, theta.value[1:], 0)
    non_zero = np.nonzero(theta_pruned)[0]

    # Select knots corresponding to nonzero coefficients (excluding intercept)
    grid_points_hal_selected = grid_points_hal[non_zero[1:] - 1]

    # Re-evaluate the density on a fine grid
    grid_eval = np.linspace(0, 1, 1000)
    grid_midpoints = (grid_eval[:-1] + grid_eval[1:]) / 2
    data_grid = pd.DataFrame({'W1': grid_midpoints})
    basis_grid_tensor = create_basis_functions(data_grid, grid_points_hal,smoothness_order)
    b_jk = basis_grid_tensor.numpy()
    delta_j = grid_eval[1:] - grid_eval[:-1]

    b_jk_pruned = b_jk[:, non_zero[1:] - 1]
    theta_selected = theta_pruned[non_zero[1:]]
    theta_intercept = theta_pruned[0]

    estimated_log_density = theta_pruned[0] + b_jk_pruned @ theta_selected
    estimated_density = np.exp(estimated_log_density)
    estimated_density /= np.sum(estimated_density * delta_j)

    theta_value = theta_pruned[non_zero]
    return {
        "theta_value": theta_value,
        "optimized_theta": theta.value,
        "pruned_theta": theta_pruned,
        "theta_intercept": theta_intercept,
        "estimated_density": estimated_density,
        "grid_midpoints": grid_midpoints,
        "grid_points_hal_selected": grid_points_hal_selected,
        "theta_selected": theta_selected,
        "b_jk": b_jk_pruned,
        "delta_j": delta_j,
        "grid_eval": grid_eval
    }

def compute_total_log_likelihood(data, results):
    """
    Compute the total log-likelihood of the observed data given the estimated density.
    """
    estimated_density = results['estimated_density']
    grid_midpoints = results['grid_midpoints']
    delta_j = results['delta_j']

    uncensored = data[data['delta'] == 1]
    censored = data[data['delta'] == 0]

    density_interp = interp1d(grid_midpoints, estimated_density, kind='linear',
                               bounds_error=False, fill_value=(estimated_density[0], estimated_density[-1]))
    ll_uncensored = np.sum(np.log(density_interp(uncensored['T_tilde'].values)))

    cdf = np.cumsum(estimated_density * delta_j)
    survival = 1 - cdf
    survival_interp = interp1d(grid_midpoints, survival, kind='linear',
                               bounds_error=False, fill_value=(1, 0))
    ll_censored = np.sum(np.log(survival_interp(censored['T_tilde'].values)))
    return ll_uncensored + ll_censored

# Helper functions
def split_data_k_folds(data, k):
    """
    Split data into k folds for cross-validation and yield training and test sets.

    Parameters:
    - data: pd.DataFrame, the dataset to split
    - k: int, number of folds

    Yields:
    - data_train: pd.DataFrame, training data for the current fold
    - data_valid: pd.DataFrame, validation data for the current fold
    """
    n = len(data)
    indices = np.arange(n)
    np.random.shuffle(indices)
    fold_size = n // k

    for i in range(k):
        test_indices = indices[i * fold_size: (i + 1) * fold_size]
        train_indices = np.setdiff1d(indices, test_indices)
        data_train = data.iloc[train_indices].reset_index(drop=True)
        data_valid = data.iloc[test_indices].reset_index(drop=True)
        yield data_train, data_valid

def compute_validation_risk_for_lambda(args):
    """
    Compute mean validation log-likelihood (risk) for a given lambda.
    """
    lamb, data, k, threshold,smoothness_order = args
    risks = []
    for train, valid in split_data_k_folds(data, k):
        res = IPCW_HAL_init(train, threshold=threshold, norm_constraint=lamb,smoothness_order=smoothness_order)
        risk = compute_total_log_likelihood(valid, res)
        risks.append(risk)
    return lamb, np.mean(risks)

def CV_IPCW_HAL(data, k, lambda_values, threshold=1e-4, n_jobs=-1,smoothness_order=1):
    """
    Perform k-fold cross-validation over candidate lambda values and return the best lambda.
    """
    args = [(lamb, data, k, threshold,smoothness_order) for lamb in lambda_values]
    if n_jobs == 1:
        results = [compute_validation_risk_for_lambda(arg) for arg in args]
    else:
        with Pool(processes=n_jobs if n_jobs != -1 else None) as pool:
            results = pool.map(compute_validation_risk_for_lambda, args)
    mean_risks = dict(results)
    best_lambda = max(mean_risks, key=mean_risks.get)
    return best_lambda, mean_risks


def precompute_global_cdf(theta_selected, grid_points_hal_selected, n_grid=500,smoothness_order=1):
    """
    Precompute the density and CDF on a global grid from 0 to 1.

    Parameters:
    -----------
    theta_selected : np.ndarray
        The estimated HAL coefficients.
    grid_points_hal_selected : np.ndarray
        The knots / grid points used for the HAL basis.
    n_grid : int
        Number of points in the global evaluation grid from 0 to 1.

    Returns:
    --------
    global_grid : np.ndarray
        Sorted points in [0, 1] (length ~ n_grid + len(grid_points_hal_selected)).
    global_cdf : np.ndarray
        CDF values corresponding to each point in global_grid, scaled to end at 1.
    """
    # Create a base grid [0, 1] plus the HAL knots
    linspace_grid = np.linspace(0, 1, n_grid)
    combined_grid = np.concatenate((linspace_grid, grid_points_hal_selected))
    global_grid = np.unique(combined_grid)
    global_grid = np.sort(global_grid)

    # Midpoints for density approximation
    midpoints = (global_grid[:-1] + global_grid[1:]) / 2
    data_grid = pd.DataFrame({'W1': midpoints})

    # Create basis and evaluate log-density
    basis_tensor = create_basis_functions(data_grid, grid_points_hal_selected,smoothness_order)  # your HAL basis
    b_jk = basis_tensor.numpy()
    estimated_log_density = b_jk @ theta_selected
    estimated_density = np.exp(estimated_log_density)

    # Delta between adjacent grid points
    delta = global_grid[1:] - global_grid[:-1]

    # Normalize so the integral is 1
    integral = np.sum(estimated_density * delta)
    estimated_density /= integral

    # Build the CDF
    cdf_values = np.cumsum(estimated_density * delta)
    # We ensure final cdf is exactly 1.0
    cdf_values[-1] = 1.0

    # We store the CDF at the right endpoints, i.e. global_grid[1:].
    # For convenience, let's make them the same length.
    # Let global_grid_right = global_grid[1:] (endpoints).
    # Then cdf at that point is cdf_values.
    # We'll keep them the same length to use np.interp nicely.
    global_grid_right = global_grid[1:]

    return global_grid_right, cdf_values


def truncated_invert_sampling(coarsening_start, global_grid, global_cdf, num_samples=5):
    """
    Sample from the truncated distribution on [coarsening_start, 1].

    Parameters:
    -----------
    coarsening_start : float
        The lower bound for truncation.
    global_grid : np.ndarray
        The grid over [0, 1], sorted, length N.
    global_cdf : np.ndarray
        The precomputed global CDF values at global_grid, length N.
    num_samples : int
        Number of samples to draw.

    Returns:
    --------
    samples : np.ndarray
        Array of shape (num_samples,) containing the truncated samples.
    """
    # If coarsening_start >= 1, no space to sample
    if coarsening_start >= 1:
        return np.full(num_samples, 1.0)

    # Find the CDF at coarsening_start (via interpolation)
    cdf_start = np.interp(coarsening_start, global_grid, global_cdf)

    # We'll sample from the truncated portion [cdf_start, 1].
    # So we draw uniform random numbers in that range
    random_probs = cdf_start + (1 - cdf_start) * np.random.rand(num_samples)

    # Invert using the global CDF
    samples = np.interp(random_probs, global_cdf, global_grid)
    return samples



def E_step(data, result, num_samples=5, n_grid=500,smoothness_order=1):
    """
    In the E-step, for each censored observation, impute latent event times
    via truncated inverse sampling from the estimated density.
    """
    uncensored = data[data['delta'] == 1].copy()
    censored = data[data['delta'] == 0].copy()

    theta_sel = result['theta_selected']
    knots_sel = result['grid_points_hal_selected']

    # Precompute the global CDF over a fine grid
    global_grid, global_cdf = precompute_global_cdf(theta_sel, knots_sel, n_grid=n_grid,smoothness_order=smoothness_order)

    imputed_list = []
    t0 = time.time()
    for idx, row in censored.iterrows():
        t = row['T_tilde']
        # Sample num_samples points from the truncated density on [t,1]
        samples = truncated_invert_sampling(t, global_grid, global_cdf, num_samples=num_samples)
        samples_df = pd.DataFrame({'T_tilde': samples, 'delta': 1, 'weights': 1/num_samples})
        imputed_list.append(samples_df)
    t1 = time.time()
    print(f"E-step sampling loop time: {t1 - t0:.4f} sec")

    if imputed_list:
        imputed = pd.concat(imputed_list, ignore_index=True)
    else:
        imputed = pd.DataFrame(columns=['T_tilde','delta','weights'])

    uncensored['weights'] = 1
    uncensored['W1'] = uncensored['T_tilde']
    imputed['W1'] = imputed['T_tilde']

    augmented = pd.concat([uncensored[['T_tilde','delta','weights','W1']], imputed], ignore_index=True)
    return augmented

def M_step(augmented, results, old_theta, norm_constraint=20,smoothness_order=1):
    """
    The M-step re–estimates the density parameters using the augmented (imputed) data.
    """
    t0 = time.time()
    knots_sel = results['grid_points_hal_selected']
    # Build design matrix for augmented data
    basis_tensor = create_basis_functions(augmented, knots_sel,smoothness_order)
    b_ik = basis_tensor.detach().numpy()

    # Use a full evaluation grid for normalization
    grid_eval = np.linspace(0, 1, 200)
    combined = np.concatenate((grid_eval, knots_sel))
    grid_eval = np.sort(np.unique(combined))
    grid_midpoints = (grid_eval[:-1] + grid_eval[1:]) / 2
    data_grid = pd.DataFrame({'W1': grid_midpoints})
    basis_grid_tensor = create_basis_functions(data_grid, knots_sel,smoothness_order)
    b_jk = basis_grid_tensor.numpy()

    t1 = time.time()
    print(f"M-step Design Matrix Calculation time (sec): {t1-t0:.4f}")

    t0_opt = time.time()
    K = len(knots_sel) + 1
    theta = cp.Variable(K)
    weights = augmented['weights'].values
    n_weighted = np.sum(weights)
    first_term = -cp.sum((theta[0] + b_ik @ theta[1:]) @ weights)
    delta_j = grid_eval[1:] - grid_eval[:-1]
    log_delta_j = np.log(delta_j)
    log_density_grid = theta[0] + b_jk @ theta[1:]
    log_terms = log_delta_j + log_density_grid
    log_Z = cp.log_sum_exp(log_terms)
    second_term = n_weighted * log_Z
    loss = first_term + second_term
    constraints = [cp.norm1(theta) <= norm_constraint]
    prob = cp.Problem(cp.Minimize(loss), constraints)
    theta.value = old_theta

    try:
        prob.solve(solver="ECOS", warm_start=True)
    except Exception as e:
        print("ECOS solver failed in M_step, falling back to SCS:", e)
        prob.solve(solver="SCS", warm_start=True)

    t1_opt = time.time()
    print(f"M-step CVXPY optimize time (sec): {t1_opt-t0_opt:.4f}")

    theta_val = theta.value
    theta_intercept = theta_val[0]
    theta_sel_new = theta_val[1:]

    grid_eval = np.linspace(0, 1, 1000)
    grid_midpoints = (grid_eval[:-1] + grid_eval[1:]) / 2
    data_grid = pd.DataFrame({'W1': grid_midpoints})
    basis_grid_tensor = create_basis_functions(data_grid, knots_sel,smoothness_order)
    b_jk = basis_grid_tensor.numpy()
    delta_j = grid_eval[1:] - grid_eval[:-1]
    estimated_log_density = theta_intercept + b_jk @ theta_sel_new
    estimated_density = np.exp(estimated_log_density)
    estimated_density /= np.sum(estimated_density * delta_j)

    updated = {
        "theta_value": theta_val,
        "theta_selected": theta_sel_new,
        "theta_intercept": theta_intercept,
        "estimated_density": estimated_density,
        "grid_midpoints": grid_midpoints,
        "grid_points_hal_selected": knots_sel,
        "b_jk": b_jk,
        "delta_j": delta_j,
        "grid_eval": grid_eval
    }
    return updated

def EM_HAL_algorithm(data, initial_results, tolerance=1e-6, max_iterations=100, num_samples=5, norm_constraint=20,smoothness_order=1):
    """
    Performs the EM algorithm for first-order HAL density estimation.
    """
    iteration = 0
    previous_ll = None
    log_likelihoods = []
    current = initial_results

    init_ll = compute_total_log_likelihood(data, current)
    print(f"Initial Log-Likelihood: {init_ll}")
    log_likelihoods.append(init_ll)

    while iteration < max_iterations:
        print(f"Iteration {iteration+1}")
        t0 = time.time()
        augmented = E_step(data, current, num_samples=num_samples,smoothness_order=smoothness_order)
        t1 = time.time()
        print(f"E-step time (sec): {t1-t0:.4f}")

        t2 = time.time()
        old_theta = current.get("theta_value", None)
        updated = M_step(augmented, current, old_theta, norm_constraint=norm_constraint,smoothness_order=smoothness_order)
        t3 = time.time()
        print(f"M-step time (sec): {t3-t2:.4f}")

        total_ll = compute_total_log_likelihood(data, updated)
        print(f"Total Log-Likelihood: {total_ll}")
        log_likelihoods.append(total_ll)

        if previous_ll is not None:
            if abs(total_ll - previous_ll) < tolerance:
                print(f"Convergence achieved at iteration {iteration+1}")
                break
        previous_ll = total_ll
        current = updated
        iteration += 1
    print("EM algorithm completed.")
    return current, log_likelihoods

# ---------------------------
# Survival Function Estimation
# ---------------------------
def compute_survival_from_density(estimator_dict, smoothness_order=1, grid_eval=None):
    """
    Compute the survival function from the estimated density using exact integration
    under the assumption that the log-density is modeled as a first-order (linear) spline.

    Returns the survival function evaluated on the grid.

    Parameters:
    -----------
    estimator_dict : dict
        Dictionary containing the estimated density information. It should include:
          - 'grid_eval' or a default grid will be used,
          - 'grid_points_hal_selected': knots for the HAL basis,
          - 'theta_intercept' and 'theta_selected' (or 'theta_value') for the density model.
    smoothness_order : int, default 1
        The order of smoothness for the HAL basis functions.
    grid_eval : array-like, optional
        Grid points over which to evaluate the survival function.
        If None, defaults to np.linspace(0, 1, 1000).

    Returns:
    --------
    survival : np.ndarray
        The survival function evaluated on grid_eval.
    grid_eval : np.ndarray
        The grid used for evaluation.
    """
    if grid_eval is None:
        grid_eval = estimator_dict.get('grid_eval', np.linspace(0, 1, 1000))
    data_grid = pd.DataFrame({'W1': grid_eval})
    knots = estimator_dict['grid_points_hal_selected']
    basis_tensor = create_basis_functions(data_grid, knots, smoothness_order)
    b_jk = basis_tensor.numpy()

    if 'theta_intercept' in estimator_dict:
        theta_intercept = estimator_dict['theta_intercept']
    else:
        theta_intercept = estimator_dict['theta_value'][0]
    if 'theta_selected' in estimator_dict:
        theta_selected = estimator_dict['theta_selected']
    else:
        theta_selected = estimator_dict['theta_value'][1:]

    log_density = theta_intercept + b_jk @ theta_selected
    cdf = np.zeros_like(grid_eval)
    cumulative = 0.0
    for i in range(len(grid_eval) - 1):
        L, R = grid_eval[i], grid_eval[i + 1]
        logf_L, logf_R = log_density[i], log_density[i + 1]
        B = (logf_R - logf_L) / (R - L)
        if np.abs(B) < 1e-8:
            # When B is nearly zero, use a simple rectangle rule.
            integral = np.exp(logf_L) * (R - L)
        else:
            delta = R - L
            # Use np.expm1 for numerical stability: exp(B*delta) - 1
            integral = np.exp(logf_L) / B * np.expm1(B * delta)
        cumulative += integral
        cdf[i + 1] = cumulative

    total_int = cumulative
    if total_int <= 0:
        raise ValueError("Total integral of the density is non-positive.")
    cdf /= total_int
    survival = 1 - cdf
    return survival, grid_eval


def compute_survival_probabilities(estimator_dict, evaluation_points, smoothness_order=1,grid_eval=None):
    """
    Compute survival probabilities at specified evaluation points based on the estimated density.
    """
    survival, grid_eval = compute_survival_from_density(estimator_dict, grid_eval=grid_eval,smoothness_order=smoothness_order)
    surv_probs = np.interp(evaluation_points, grid_eval, survival, left=1.0, right=0.0)
    return surv_probs

##############################################
# Poinwise confidence intervals for the density (Helper functions)
##############################################

##############################################
# 1. Compute individual score contributions
##############################################

def compute_individual_score(row, final_results,smoothness_order):
    """
    For a single observation, compute the score contribution (i.e. the derivative of the log-likelihood
    with respect to the non-intercept coefficients) under your model.

    For an uncensored observation (delta==1):
        s_i = φ(T_tilde) - E[φ(X)]
    For a censored observation (delta==0):
        s_i = E[φ(X) | X ≥ T_tilde] - E[φ(X)]

    Parameters:
    -----------
    row : Series
        A row of the data containing at least 'T_tilde' and 'delta'.
    final_results : dict
        Dictionary from the EM algorithm containing at least:
          - "grid_midpoints": 1D array of grid midpoints used for integration.
          - "estimated_density": estimated density on those midpoints.
          - "delta_j": integration weights (grid differences).
          - "grid_points_hal_selected": the knots used for the selected HAL basis.
          - "b_jk": basis functions evaluated on the grid midpoints.
            (Each row corresponds to a grid point and each column to a basis function.)

    Returns:
    --------
    score : 1D numpy array (length = number of selected basis functions)
    """
    T_tilde = row['T_tilde']
    delta = row['delta']
    # Compute the expectation E[φ(X)] on the grid:
    E_phi = np.sum(final_results["b_jk"].T * final_results["estimated_density"] * final_results["delta_j"], axis=1)

    if delta == 1:
        # For an uncensored observation: evaluate the basis at T_tilde.
        df_T = pd.DataFrame({'W1': [T_tilde]})
        phi_T = create_basis_functions(df_T, final_results["grid_points_hal_selected"],smoothness_order=smoothness_order).numpy().flatten()
        score = phi_T - E_phi
    else:
        # For a censored observation: compute the conditional expectation E[φ(X) | X ≥ T_tilde].
        grid = final_results["grid_midpoints"]
        mask = grid >= T_tilde
        if np.sum(mask) == 0:
            score = -E_phi
        else:
            num = np.sum(final_results["b_jk"][mask, :].T * final_results["estimated_density"][mask] * final_results["delta_j"][mask], axis=1)
            den = np.sum(final_results["estimated_density"][mask] * final_results["delta_j"][mask])
            cond_exp = num / den
            score = cond_exp - E_phi
    return score

##############################################
# 2. Estimate the covariance matrix of β̂
##############################################

def estimate_covariance_beta(data, final_results, ridge=1e-6,smoothness_order=1):
    """
    Estimate the covariance matrix of the (non-intercept) coefficients β̂.
    We compute the individual score vectors s_i and then estimate the
    Fisher information matrix as the average outer product:

         Î = (1/n) ∑ s_i s_i^T,

    and then use (asymptotically)
         Cov(β̂) ≈ Î⁻¹ / n.

    Parameters:
    -----------
    data : DataFrame
        The original dataset.
    final_results : dict
        The dictionary produced at the end of the EM algorithm.

    Returns:
    --------
    cov_beta : 2D numpy array (p × p), where p = number of selected basis functions.
    """
    scores = []
    for _, row in data.iterrows():
        s = compute_individual_score(row, final_results,smoothness_order=smoothness_order)
        scores.append(s)
    scores = np.array(scores)  # shape: (n, p)
    n = scores.shape[0]

    # Estimate the expected outer product: Î = (1/n)*∑ s_i s_i^T.
    I_hat = np.dot(scores.T, scores) / n
    I_hat_reg = I_hat + (ridge/np.sqrt(I_hat.shape[0])) * np.eye(I_hat.shape[0])
    try:
        cov_beta = np.linalg.inv(I_hat_reg) / n
    except np.linalg.LinAlgError:
        cov_beta = np.linalg.pinv(I_hat_reg) / n
    return cov_beta


##############################################
# 3. Estimate the density at an arbitrary x
##############################################

def estimated_density_at(x, final_results):
    """
    For any x ∈ [0,1] (or within the range of interest), return the estimated density.
    Here we use a simple linear interpolation on the grid midpoints stored in final_results.

    Parameters:
    -----------
    x : float or array-like
        The evaluation point(s).
    final_results : dict
        Must contain "grid_midpoints" and "estimated_density".

    Returns:
    --------
    f_x : float or array of estimated density values.
    """
    f_interp = interp1d(final_results["grid_midpoints"], final_results["estimated_density"],
                        kind="linear", bounds_error=False, fill_value="extrapolate")
    return f_interp(x)

##############################################
# 4. Compute the gradient of the density
##############################################

def compute_grad_f(x, final_results,smoothness_order):
    """
    Compute the gradient of the estimated density at x with respect to the
    (non-intercept) coefficients. That is, compute

         grad_f(x) = f(x) * [φ(x) - E[φ(X)]],

    where
         f(x) = estimated_density_at(x, final_results),
         φ(x) = the HAL basis function evaluated at x,
         E[φ(X)] = ∑_grid φ(x_grid) f(x_grid) Δx.

    Parameters:
    -----------
    x : float
        The evaluation point.
    final_results : dict
        Must contain:
          - "grid_points_hal_selected": the selected HAL knots.
          - "b_jk": basis functions evaluated on the integration grid.
          - "estimated_density": estimated density on the integration grid.
          - "delta_j": grid differences for integration.

    Returns:
    --------
    grad_f : 1D numpy array, the gradient of f at x with respect to β.
    """
    # Evaluate density at x
    f_x = estimated_density_at(x, final_results)

    # Compute φ(x)
    df_x = pd.DataFrame({'W1': [x]})
    phi_x = create_basis_functions(df_x, final_results["grid_points_hal_selected"],smoothness_order).numpy().flatten()

    # Compute E[φ(X)] using the integration grid:
    E_phi = np.sum(final_results["b_jk"].T * final_results["estimated_density"] * final_results["delta_j"], axis=1)

    grad_f = f_x * (phi_x - E_phi)
    return grad_f


##############################################
# 5. Use the delta method to compute variance
##############################################

def compute_density_variance(x, final_results, cov_beta,smoothness_order):
    """
    Compute the approximate variance of the estimated density at x via the delta method.

    Given that
         f(x) = exp(θ₀ + φ(x)^Tβ) / Z,
    its gradient with respect to β is
         grad_f(x) = f(x) * [φ(x) - E[φ(X)]],
    so that
         Var(f(x)) ≈ grad_f(x)^T Cov(β̂) grad_f(x).

    Parameters:
    -----------
    x : float
        The evaluation point.
    final_results : dict
        Must contain the necessary quantities.
    cov_beta : 2D numpy array
        Estimated covariance matrix of β̂.

    Returns:
    --------
    var_f : float, the estimated variance of f(x).
    """
    grad_f = compute_grad_f(x, final_results,smoothness_order=smoothness_order)
    var_f = np.dot(grad_f, np.dot(cov_beta, grad_f))
    return var_f

##############################################
# 6. Construct confidence intervals for a grid of x's
##############################################

def density_confidence_interval(x_values, final_results, cov_beta, alpha=0.05,smoothness_order=1):
    """
    For each evaluation point in x_values, compute the estimated density,
    its standard error (via the delta method), and the (1-α)% confidence interval.

    Parameters:
    -----------
    x_values : array-like
        Points at which to compute the inference.
    final_results : dict
        The final output from your EM algorithm.
    cov_beta : 2D numpy array
        Estimated covariance matrix of β̂.
    alpha : float
        Significance level (default 0.05 gives 95% confidence intervals).

    Returns:
    --------
    results_df : DataFrame with columns:
         'x'       : evaluation point,
         'density' : estimated density f(x),
         'se'      : standard error,
         'lower'   : lower bound,
         'upper'   : upper bound.
    """
    z = norm.ppf(1 - alpha / 2)
    results = []
    for x in x_values:
        var_f = compute_density_variance(x, final_results, cov_beta,smoothness_order=smoothness_order)
        se = np.sqrt(var_f)
        results.append({'x': x,  'se': se})
    return pd.DataFrame(results)

##############################################
# Precompute the Density Gradient on a Fine Uniform Grid
##############################################

def precompute_grad_f_grid(final_results, grid_size=1000,smoothness_order=1):
    """
    Precompute the gradient of the estimated density f(x) on a uniform grid over [0,1].

    Parameters:
      final_results : dict, the HAL estimation result (contains keys used in compute_grad_f)
      grid_size : int, number of points in the uniform grid (default: 1000)

    Returns:
      grid : numpy array of shape (grid_size,), the uniform grid points over [0,1]
      grad_f_grid : numpy array of shape (grid_size, p), where p is the number of non-intercept coefficients,
                    containing grad_f(x) at each grid point.
      delta : float, the uniform grid spacing.
    """
    grid = np.linspace(0, 1, grid_size)
    grad_f_list = []
    for x in grid:
        grad_f_list.append(compute_grad_f(x, final_results,smoothness_order))
    grad_f_grid = np.array(grad_f_list)  # shape: (grid_size, p)
    delta = grid[1] - grid[0]
    return grid, grad_f_grid, delta

##############################################
# Compute the Survival Gradient Using the Precomputed Grid
##############################################

def compute_grad_S_from_precomputed(x0, grid, grad_f_grid, delta):
    """
    Given a precomputed uniform grid and corresponding grad_f values,
    compute the survival gradient:
         ∇_β S(x0) = ∫_{x0}^1 ∇_β f(y) dy,
    by summing the precomputed gradients for grid points >= x0.

    Parameters:
      x0 : float, evaluation point.
      grid : numpy array, the precomputed uniform grid over [0,1].
      grad_f_grid : numpy array, precomputed gradient values at each grid point.
      delta : float, uniform grid spacing.

    Returns:
      grad_S : 1D numpy array, the approximate gradient vector of S(x0).
    """
    mask = grid >= x0
    grad_S = np.sum(grad_f_grid[mask], axis=0) * delta
    return grad_S

##############################################
# Survival Function and Variance via Delta Method
##############################################

def estimated_survival_at(x0, final_results):
    """
    Estimate the survival function S(x0) = ∫_{x0}^1 f(y) dy using a Riemann sum
    on the original integration grid.
    """
    grid = final_results["grid_midpoints"]
    f = final_results["estimated_density"]
    delta = final_results["delta_j"]
    mask = grid >= x0
    return np.sum(f[mask] * delta[mask])

def compute_survival_variance_precomputed(x0, final_results, cov_beta, grid, grad_f_grid, delta):
    """
    Compute the approximate variance of the survival function S(x0) using the precomputed
    survival gradient and the delta method.

    Var(S(x0)) ≈ (∇_β S(x0))ᵀ · Cov(β) · (∇_β S(x0))
    """
    grad_S = compute_grad_S_from_precomputed(x0, grid, grad_f_grid, delta)
    return np.dot(grad_S, np.dot(cov_beta, grad_S))

def survival_confidence_interval_precomputed(x_values, final_results, cov_beta, grid, grad_f_grid, delta, alpha=0.05):
    """
    For each evaluation point x0 in x_values, compute the survival function S(x0)
    and its (1-α)% confidence interval using the delta method with precomputed gradients.
    """
    z = norm.ppf(1 - alpha/2)
    results = []
    for x0 in x_values:
        S_x0 = estimated_survival_at(x0, final_results)
        var_S = compute_survival_variance_precomputed(x0, final_results, cov_beta, grid, grad_f_grid, delta)
        se = np.sqrt(np.maximum(var_S, 0))
        lower = S_x0 - z * se
        upper = S_x0 + z * se
        results.append({'x': x0, 'survival': S_x0, 'se': se, 'lower': lower, 'upper': upper})
    return pd.DataFrame(results)

# ---------------------------
# Single Experiment Function
# ---------------------------
def run_single_experiment(seed, n_samples=1000,
                          evaluation_points=np.linspace(0, 1, 100),
                          candidate_lambdas=[55, 60, 65, 70],
                          smoothness_order=1,
                          ridge=0):
    """
    Run one complete experiment:
      - Data Generation: Simulate true event times (truncated normal) and censoring times (uniform).
      - Create right–censored observations.
      - Use 5–fold cross-validation over candidate lambdas to select the best lambda.
      - Compute an initial density estimate via IPCW_HAL_init and refine it via EM_HAL_algorithm.
      - Evaluate the estimated density and compute the plug–in survival function.
    Returns a dictionary with:
      - 'initial_density': density estimates (on evaluation_points) from the initial estimator,
      - 'final_density': density estimates (on evaluation_points) from the EM–refined estimator,
      - 'initial_survival': survival probabilities (on evaluation_points) from the initial estimator,
      - 'final_survival': survival probabilities (on evaluation_points) from the refined estimator,
      - 'best_lambda': the best lambda chosen by CV,
      - 'evaluation_points': the evaluation grid.
    """
    np.random.seed(seed)
    T = generate_truncated_normal(n_samples)
    C = generate_uniform(n_samples)
    data = convert_to_survival_data(T, C)

    k = 5
    best_lambda, cv_risks = CV_IPCW_HAL(data, k, candidate_lambdas, threshold=1e-4, n_jobs=1,smoothness_order=smoothness_order)

    init_res = IPCW_HAL_init(data, threshold=1e-4, norm_constraint=best_lambda,smoothness_order=smoothness_order)
    final_res, _ = EM_HAL_algorithm(data, init_res, tolerance=0.05, max_iterations=200,
                                    num_samples=200, norm_constraint=5 * best_lambda,smoothness_order=smoothness_order)

    print('Now to get the estimates and esimated se')
    # Evaluate density by linear interpolation on the final grid
    init_density_eval = np.interp(evaluation_points, init_res["grid_midpoints"], init_res["estimated_density"])
    final_density_eval = np.interp(evaluation_points, final_res["grid_midpoints"], final_res["estimated_density"])

    init_surv_probs = compute_survival_probabilities(init_res, evaluation_points,smoothness_order)
    final_surv_probs = compute_survival_probabilities(final_res, evaluation_points,smoothness_order)



    cov_beta = estimate_covariance_beta(data, init_res, ridge = ridge,smoothness_order=smoothness_order)
    ci_density_df = density_confidence_interval(evaluation_points, init_res, cov_beta, alpha=0.05,smoothness_order=smoothness_order)
    initial_density_se=ci_density_df['se']
    grid, grad_f_grid, delta = precompute_grad_f_grid(init_res, grid_size=1000,smoothness_order=smoothness_order)
    surv_ci_df = survival_confidence_interval_precomputed(evaluation_points, init_res, cov_beta, grid, grad_f_grid, delta, alpha=0.05)
    initial_survival_se=surv_ci_df['se']

    cov_beta = estimate_covariance_beta(data, final_res, ridge = ridge,smoothness_order=smoothness_order)
    ci_density_df = density_confidence_interval(evaluation_points, final_res, cov_beta, alpha=0.05,smoothness_order=smoothness_order)
    final_density_se=ci_density_df['se']
    grid, grad_f_grid, delta = precompute_grad_f_grid(final_res, grid_size=1000,smoothness_order=smoothness_order)
    surv_ci_df = survival_confidence_interval_precomputed(evaluation_points, final_res, cov_beta, grid, grad_f_grid, delta, alpha=0.05)
    final_survival_se=surv_ci_df['se']



    return {
        "initial_density": init_density_eval,
        "final_density": final_density_eval,
        "initial_density_se": initial_density_se,
        "final_density_se": final_density_se,
        "initial_survival": init_surv_probs,
        "final_survival": final_surv_probs,
        "initial_survival_se": initial_survival_se,
        "final_survival_se": final_survival_se,
        "best_lambda": best_lambda,
        "evaluation_points": evaluation_points,
        "cv_risks": cv_risks
    }

# ---------------------------
# Multiple Experiment Runner
# ---------------------------
def run_multiple_experiments(n_experiments=10, n_samples=1000,
                             evaluation_points=np.linspace(0.02, 0.98, 20),
                             candidate_lambdas=[55, 60, 65, 70],
                             n_jobs=-1,
                             smoothness_order=1,
                             ridge=0):
    seeds = [12776 + i for i in range(n_experiments)]
    experiment_func = partial(run_single_experiment, n_samples=n_samples,
                              evaluation_points=evaluation_points,
                              candidate_lambdas=candidate_lambdas,
                              smoothness_order=smoothness_order,
                              ridge=ridge)
    with Pool(processes=n_jobs if n_jobs != -1 else None) as pool:
        results = pool.map(experiment_func, seeds)

    # Assemble density and survival estimates into DataFrames (rows: evaluation points, columns: experiments)
    exp_ids = [f"Exp_{i+1}" for i in range(n_experiments)]
    init_density_df = pd.DataFrame(np.column_stack([res["initial_density"] for res in results]),
                                   index=evaluation_points, columns=exp_ids)
    final_density_df = pd.DataFrame(np.column_stack([res["final_density"] for res in results]),
                                    index=evaluation_points, columns=exp_ids)
    init_survival_df = pd.DataFrame(np.column_stack([res["initial_survival"] for res in results]),
                                    index=evaluation_points, columns=exp_ids)
    final_survival_df = pd.DataFrame(np.column_stack([res["final_survival"] for res in results]),
                                     index=evaluation_points, columns=exp_ids)
    init_density_df_se = pd.DataFrame(np.column_stack([res["initial_density_se"] for res in results]),
                                    index=evaluation_points, columns=exp_ids)
    final_density_df_se = pd.DataFrame(np.column_stack([res["final_density_se"] for res in results]),
                                    index=evaluation_points, columns=exp_ids)
    init_survival_df_se = pd.DataFrame(np.column_stack([res["initial_survival_se"] for res in results]),
                                    index=evaluation_points, columns=exp_ids)
    final_survival_df_se = pd.DataFrame(np.column_stack([res["final_survival_se"] for res in results]),
                                    index=evaluation_points, columns=exp_ids)
    best_lambda_df = pd.DataFrame({
        "Experiment": exp_ids,
        "Best_Lambda": [res["best_lambda"] for res in results]
    })
    return init_density_df, final_density_df, init_survival_df, final_survival_df, \
    init_density_df_se,final_density_df_se, init_survival_df_se, final_survival_df_se, best_lambda_df

# Define parameters
n_samples = 800 #200, 400, 800, 1600, 3200
smoothness_order = 1
ridge = 1e-6
n_experiments = 500
candidate_lambdas_1 = [60, 65, 70, 80]
candidate_lambdas_0 = [3, 5, 8, 10]

candidate_lambdas = candidate_lambdas_1

# Run experiments with the given parameters
init_density_df, final_density_df, init_survival_df, final_survival_df, \
init_density_df_se, final_density_df_se, init_survival_df_se, final_survival_df_se, \
best_lambda_df = run_multiple_experiments(n_experiments=n_experiments,
                                          n_samples=n_samples,
                                          smoothness_order=smoothness_order,
                                          candidate_lambdas=candidate_lambdas,
                                          ridge=ridge)

# Create a base file name incorporating the parameter values
base_name = f"out/hal_n{n_samples}_smooth{smoothness_order}_ridge{ridge}"

# Save DataFrames to CSV files with modified file names
init_density_df.to_csv(f"{base_name}_initial_density.csv", index=True)
final_density_df.to_csv(f"{base_name}_final_density.csv", index=True)
init_survival_df.to_csv(f"{base_name}_initial_survival.csv", index=True)
final_survival_df.to_csv(f"{base_name}_final_survival.csv", index=True)
init_density_df_se.to_csv(f"{base_name}_initial_density_se.csv", index=True)
final_density_df_se.to_csv(f"{base_name}_final_density_se.csv", index=True)
init_survival_df_se.to_csv(f"{base_name}_initial_survival_se.csv", index=True)
final_survival_df_se.to_csv(f"{base_name}_final_survival_se.csv", index=True)
best_lambda_df.to_csv(f"{base_name}_best_lambda.csv", index=False)

# Produce a bar chart of candidate lambda selection frequency
counts = [ (best_lambda_df["Best_Lambda"] == lam).sum() for lam in candidate_lambdas ]
plt.figure(figsize=(8, 6))
plt.bar(candidate_lambdas, counts, color="skyblue", edgecolor="black")
plt.xlabel("Candidate Lambda Value")
plt.ylabel("Frequency of Selection")
plt.title("Frequency of Best Lambda Selection Across Experiments")
plt.xticks(candidate_lambdas)
plt.tight_layout()
plt.savefig(f"{base_name}_lambda_frequency.png")
plt.show()

print("Saved CSV files and lambda frequency plot.")